### ISSUE TITLE
Error When Fast Navigating "Failed to execute 'insertBefore' on 'Node'"

### ISSUE THREAD

**Issue by viandwi24** [nuxt/nuxt#13350]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.2.0`
- Nuxt Version:     `3.0.0-27404660.0f9bcbf`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `meta`, `css`, `plugins`, `build`, `buildModules`, `components`, `vite`, `intlify`, `vueuse`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/eslint-module@3.0.2`, `@pinia/nuxt@0.1.8`, `unplugin-icons/nuxt`, `@nuxtjs/svg@0.3.0`, `@intlify/nuxt3@0.1.10`, `@vueuse/nuxt@7.5.5`, `~/modules/tailwind-viewer`
------------------------------

### Reproduction

Using Minimal Nuxt 3 Template :
https://codesandbox.io/s/loving-feather-utoky

Using My Template :
https://codesandbox.io/s/github/viandwi24/nuxt3-awesome-starter

I tested on both templates above the results are the same

### Describe the bug

when navigating too fast an error appears like the log below and the application stops working.

for example when I navigate to the "about" page then quickly navigate again to the "home" page.

like the gif below:
[![preview](https://i.ibb.co/NWtFYnX/Screen-Recording-2022-02-10-at-00-31-41.gif)](https://ibb.co/qm7D1Fz)
[![preview2](https://i.ibb.co/gtwJq9p/Screen-Recording-2022-02-10-at-00-33-05.gif)](https://ibb.co/KV7W4hk)

### Logs

```shell
### **CHROME & BRAVE**

VM946 vue.js:7086 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insert (https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:7086:12)
    at move (https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:5432:9)
    at move (https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:5405:7)
    at Object.activeBranch.transition.afterLeave (https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:2273:15)
    at performRemove (https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:5509:20)
    at el._leaveCb (https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:2874:9)
    at finishLeave (https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:7713:13)
    at resolve2 (https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:7743:30)
    at whenTransitionEnds (https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:7825:12)
    at https://utoky.sse.codesandbox.io/_nuxt/node_modules/.vite/vue.js?v=71a85d57:7751:11



### **SAFARI**

[Error] NotFoundError: The object can not be found here.
	insertBefore (vue.js:7086)
	insert (vue.js:7086)
	move (vue.js:5432)
	move (vue.js:5405)
	(anonymous function) (vue.js:2273)
	performRemove (vue.js:5509)
	(anonymous function) (vue.js:2874)
	finishLeave (vue.js:7713)
	(anonymous function) (vue.js:7751)
```

**Comment by madebyfabian** [comment]
Can anyone confirm that this is still an error within the newest version of nuxt? Or if this was fixed in the RC cycle?

**Comment by vanling** [comment]
I can confirm that it still happens, when using page transitions.

**Comment by manniL** [comment]
@madebyfabian There is an upstream bug linked in https://github.com/nuxt/nuxt/issues/13350#issuecomment-1397297522, so as long as this one isn't fixed it will be a problem.

**Comment by jannejava** [comment]
The Vue-bug seems to still be present. Is there a consensus of the best workaround?

**Comment by 20Alexanderxx** [comment]
I guess the best thing is to modify your layout or App.vue and add the following:

**Comment by jannejava** [comment]
@20Alexanderxx That's the one I went for. So far, so good.

**Comment by andysay** [comment]
> @20Alexanderxx That's the one I went for. So far, so good.

its solution works from beta, but it not best solution ! layout reseted, losing animation properties for example

**Comment by jannejava** [comment]
Yes indeed. However, it’s better than a white page.

**Comment by GILD-MasayaGoto** [comment]
Transitions are a better UX, but you can develop without them.

I'm going to put up a ticket as an issue for my company and wait until the core problem is resolved, but I want it to be resolved as soon as possible. We want to give our users an experience that exceeds their expectations.

**Comment by oezkancodes** [comment]
I had already commented #12735, but the issue was already closed. I hope my experience on this helps to solve this issue.

Nuxt version: ^3.3.2

---

For me, this error only happens when I have set the page transition mode to 'out-in' and I change a page again **during a page transition** (switch pages fast).

```ts
export default defineNuxtConfig({
  ssr: false,
  app: {
    pageTransition: { name: 'page', mode: 'out-in' },
  },
  // ...
});
```

```css
.page-enter-active,
.page-leave-active {
  @apply origin-center transition-all duration-150 ease-in-out;
}
.page-leave-to {
  @apply scale-95 opacity-0;
}
.page-enter-from {
  @apply scale-105 opacity-0;
}
```

When I set the page transition mode to 'default', or disable page transitions, the error is gone.

**Comment by fabricioffa** [comment]
> I had already commented #12735, but the issue was already closed. I hope my experience on this helps to solve this issue.
> 
> Nuxt version: ^3.3.2
> 
> For me, this error only happens when I have set the page transition mode to 'out-in' and I change a page again **during a page transition** (switch pages fast).
> 
> ```ts
> export default defineNuxtConfig({
>   ssr: false,
>   app: {
>     pageTransition: { name: 'page', mode: 'out-in' },
>   },
>   // ...
> });
> ```
> 
> ```css
> .page-enter-active,
> .page-leave-active {
>   @apply origin-center transition-all duration-150 ease-in-out;
> }
> .page-leave-to {
>   @apply scale-95 opacity-0;
> }
> .page-enter-from {
>   @apply scale-105 opacity-0;
> }
> ```
> 
> When I set the page transition mode to 'default', or disable page transitions, the error is gone.

I just made this discovery myself and came to comment. In Nuxt v3.3.3 happens exactly the same.

I'm sure that, in my case, it's also not a multiple-root element problem. At first, I encountered one or two pages with this problem, but making it single-rooted didn't help much. Removing the transition mode from the config did the trick.

**Comment by vesamet** [comment]
@oezkancodes Thank you so much for your input. I was also facing this issue. I hope it will be fixed soon, because my transition is not pretty at all with the `default` mode.

**Comment by danielroe** [comment]
The issue I linked earlier may be linked, but I've reproduced more specifically within Vue core: https://github.com/vuejs/core/issues/8105. This does not seem to be an issue in `vue-router`. (cc: @posva)

**Comment by Sun-ZhenXing** [comment]
By denying users too fast routing, we can use middleware, this value should be greater than twice animation time (I tested).

```ts
// composables/states.ts
export const useLastRouteTime = () => useState<number>('lastRouteTime', () => 0)
```

```ts
// middleware/route.global.ts
export default defineNuxtRouteMiddleware((to, from) => {
  const routeTime = useLastRouteTime()
  // reject too fast route change, in 500ms
  if (new Date().getTime() - routeTime.value < 500)
    return false
  routeTime.value = new Date().getTime()
})
```
but until the perfect solution is found, perhaps we should give the user (courageous user!!) some hints, not to operate too fast (although this is counter-intuitive).

**Comment by Sun-ZhenXing** [comment]
@Sun-ZhenXing Unfortunately, this does not prevent the problem completely, but only provides an interface to prevent the user from doing so.

Is there a better way than refreshing when problems arise?

**Comment by parzychu** [comment]
@Sun-ZhenXing I had a similar workaround for that, but users like to use browser navigation and hardware button on mobile so still I was getting a lot of errors.

Currently testing this: https://github.com/nuxt/nuxt/issues/13350#issuecomment-1397297967 . It glitches animations sometimes, but it's a price I'm willing to pay.

If it doesn't work then I will add this heavy solution: https://github.com/nuxt/nuxt/issues/13350#issuecomment-1397297690

**Comment by tenfei4** [comment]
v3.5.1 still exists this problem,hope fix it soon.

**Comment by danielroe** [comment]
This is an upstream bug being tracked in the vuejs/core repository.

**Comment by Hebilicious** [comment]
@danielroe wasn't that fixed here https://github.com/vuejs/core/pull/8259 ?

**Comment by danielroe** [comment]
Unfortunately not. The issue is https://github.com/vuejs/core/issues/8105.

**Comment by Ravshanovich99** [comment]
I also confirm that it is happening, when fast navigating

**Comment by parsagholipour** [comment]
Temporarily fixed using this(Although it causes flashing on rerenders):

```js
<script setup>
const { key } = useFixPageTransition()
</script>

<template>
  <NuxtLayout :key="key" name="public-layout">
    <NuxtPage />
  </NuxtLayout>
</template>
```
```js
export default function useFixPageTransition() {
  // TODO: Remove when https://github.com/nuxt/nuxt/issues/13350 fixed
  const key = ref(0)
  const messages = [
    'Uncaught NotFoundError: Failed to execute \'insertBefore\' on \'Node\': The node before which the new node is to be inserted is not a child of this node.', // chromium based
    'NotFoundError: The object can not be found here.', // safari
  ]
  if (typeof window !== 'undefined') {
    // @ts-expect-error using arbitrary window key
    if (!window.__vue5513) {
      window.addEventListener('error', (event) => {
        if (messages.includes(event.message)) {
          event.preventDefault()
          console.warn(
            'Rerendering layout because of https://github.com/vuejs/core/issues/5513',
          )
          key.value++
        }
      })
    }

    // @ts-expect-error using arbitrary window key
    window.__vue5513 = true
  }

  return {
    key,
  }
}

```

**Comment by yuzu-qroulland** [comment]
Hi everyone 👋🏻 

I've found a temporary solution to get around this problem with a plugin. 

```javascript
export default defineNuxtPlugin({
  name: "router",
  hooks: {
    "page:start"() {
      const nuxtApp = useNuxtApp();
      nuxtApp.$router.running = false;
      nuxtApp.$router.beforeEach((to, from, next) => {
        if (nuxtApp.$router.running) {
          next(true);
        } else {
          next(false);
        }
      });
    },
    "page:transition:finish"() {
      const nuxtApp = useNuxtApp();
      nuxtApp.$router.running = true;
    },
  },
});
``` 

The plugin will disable navigation when the **'page:start'** hook is triggered, then re-enable it with the **'page:transition:finish'** hook. This way, if there's a route change during the page transition, the router won't take it into consideration 

It's not very clean, but I think it'll do the job just fine until they fix it 😁

**Comment by ymansurozer** [comment]
> nuxtApp.$router.running

This sounds a promising workaround @yuzu-qroulland! But what version of Nuxt are you using? There seems to be no `running` variable in `$router` in my setup.

**Comment by yuzu-qroulland** [comment]
> > nuxtApp.$router.running
> 
> 
> 
> This sounds a promising workaround @yuzu-qroulland! But what version of Nuxt are you using? There seems to be no `running` variable in `$router` in my setup.
> 
> 

The **running** attribute does not exist in the $router instance. I declared it myself, that permit to store the variable and get it every where in the app

**Comment by parsagholipour** [comment]
> Hi everyone 👋🏻
> 
> I've found a temporary solution to get around this problem with a plugin.
> 
> ```js
> export default defineNuxtPlugin({
>   name: "router",
>   hooks: {
>     "page:start"() {
>       const nuxtApp = useNuxtApp();
>       nuxtApp.$router.running = false;
>       nuxtApp.$router.beforeEach((to, from, next) => {
>         if (nuxtApp.$router.running) {
>           next(true);
>         } else {
>           next(false);
>         }
>       });
>     },
>     "page:transition:finish"() {
>       const nuxtApp = useNuxtApp();
>       nuxtApp.$router.running = true;
>     },
>   },
> });
> ```
> 
> The plugin will disable navigation when the **'page:start'** hook is triggered, then re-enable it with the **'page:transition:finish'** hook. This way, if there's a route change during the page transition, the router won't take it into consideration
> 
> It's not very clean, but I think it'll do the job just fine until they fix it 😁

I think it should currently be the default behavior. I made a little change to keep the last intended route so user won't lose his last click.
```js
export default defineNuxtPlugin({
  name: 'router',
  hooks: {
    'page:start': function () {
      const nuxtApp = useNuxtApp()
      nuxtApp.$router.running = false
      nuxtApp.$router.beforeEach((to, from, next) => {
        if (nuxtApp.$router.running) { next(true) }
        else {
          nuxtApp.$router.nextRoute = to.fullPath
          next(false)
        }
      })
    },
    'page:transition:finish': function () {
      const nuxtApp = useNuxtApp()
      nuxtApp.$router.running = true
      if (nuxtApp.$router.nextRoute) {
        nuxtApp.$router.push(nuxtApp.$router.nextRoute)
        nuxtApp.$router.nextRoute = null
      }
    },
  },
})

```

**Comment by flav-code** [comment]
I have the error when i enable page transition :/

**Comment by flav-code** [comment]
> > Hi everyone 👋🏻
> > I've found a temporary solution to get around this problem with a plugin.
> > ```js
> > export default defineNuxtPlugin({
> >   name: "router",
> >   hooks: {
> >     "page:start"() {
> >       const nuxtApp = useNuxtApp();
> >       nuxtApp.$router.running = false;
> >       nuxtApp.$router.beforeEach((to, from, next) => {
> >         if (nuxtApp.$router.running) {
> >           next(true);
> >         } else {
> >           next(false);
> >         }
> >       });
> >     },
> >     "page:transition:finish"() {
> >       const nuxtApp = useNuxtApp();
> >       nuxtApp.$router.running = true;
> >     },
> >   },
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The plugin will disable navigation when the **'page:start'** hook is triggered, then re-enable it with the **'page:transition:finish'** hook. This way, if there's a route change during the page transition, the router won't take it into consideration
> > It's not very clean, but I think it'll do the job just fine until they fix it 😁
> 
> I think it should currently be the default behavior. I made a little change to keep the last intended route so user won't lose his last click.
> 
> ```js
> export default defineNuxtPlugin({
>   name: 'router',
>   hooks: {
>     'page:start': function () {
>       const nuxtApp = useNuxtApp()
>       nuxtApp.$router.running = false
>       nuxtApp.$router.beforeEach((to, from, next) => {
>         if (nuxtApp.$router.running) { next(true) }
>         else {
>           nuxtApp.$router.nextRoute = to.fullPath
>           next(false)
>         }
>       })
>     },
>     'page:transition:finish': function () {
>       const nuxtApp = useNuxtApp()
>       nuxtApp.$router.running = true
>       if (nuxtApp.$router.nextRoute) {
>         nuxtApp.$router.push(nuxtApp.$router.nextRoute)
>         nuxtApp.$router.nextRoute = null
>       }
>     },
>   },
> })
> ```

It works on my side i createed a file named router in /plugins then pasth the code and restart your app

**Comment by BeTiker** [comment]
> It works on my side i createed a file named router in /plugins then pasth the code and restart your app nuxt: 3.6.0

I tried this on Nuxt 3.5.2 and it worked but after upgrading to 3.6.5 it didn't. I updated the code following the [Lifecycle Hooks Usage with Plugins Documentation](https://nuxt.com/docs/guide/going-further/hooks#usage-with-plugins) and converted it into TypeScript.

**plugins/router.ts**
```TypeScript
import { Router } from "vue-router";

interface CustomRouter extends Router {
  running?: boolean;
  nextRoute?: string | null;
}

export default defineNuxtPlugin((nuxtApp) => {
  const customRouter: CustomRouter = useNuxtApp().$router;

  nuxtApp.hook("page:start", () => {
    customRouter.running = false;
    customRouter.beforeEach((to, _from, next) => {
      if (customRouter.running) {
        next(true);
      } else {
        customRouter.nextRoute = to.fullPath;
        next(false);
      }
    });
  });
  nuxtApp.hook("page:transition:finish", () => {
    customRouter.running = true;
    if (customRouter.nextRoute) {
      customRouter.push(customRouter.nextRoute);
      customRouter.nextRoute = null;
    }
  });
});
```

**Comment by emsitkowski** [comment]
Hi, I had the same bug in my app. After hours of struggling and searching for the best solution, I ended with a plugin, middleware and custom page transitions using GSAP (ofc can use any other library or vanilla js transitions). Finally it seems to work just fine, without any flickering or browser refreshes. 

I wrapped NuxtPage component in app.vue in a div with .page-wrapper class, then animated it within the middleware and app hook. Here's my solution:

```javascript
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook("app:mounted", () => {
    useRouter().beforeEach((to, from, next) => {
      useNuxtApp().$gsap.to(".page-wrapper", {
        opacity: 0,
        y: 32,
        filter: "blur(10px)",
        duration: 0.3,
        onComplete: () => {
          next();
          useNuxtApp().$gsap.to(".page-wrapper", { opacity: 1, y: 0, filter: "blur(0px)", duration: 0.3 });
        },
      });
    });
  });
});

```

**Comment by cyrenity** [comment]
> Hi, I had the same bug in my app. After hours of struggling and searching for the best solution, I ended with a plugin, middleware and custom page transitions using GSAP (ofc can use any other library or vanilla js transitions). Finally it seems to work just fine, without any flickering or browser refreshes.
> 
> I wrapped NuxtPage component in app.vue in a div with .page-wrapper class, then animated it within the middleware and app hook. Here's my solution:
> 
> ```js
> export default defineNuxtPlugin((nuxtApp) => {
>   nuxtApp.hook("app:mounted", () => {
>     useRouter().beforeEach((to, from, next) => {
>       useNuxtApp().$gsap.to(".page-wrapper", {
>         opacity: 0,
>         y: 32,
>         filter: "blur(10px)",
>         duration: 0.3,
>         onComplete: () => {
>           next();
>           useNuxtApp().$gsap.to(".page-wrapper", { opacity: 1, y: 0, filter: "blur(0px)", duration: 0.3 });
>         },
>       });
>     });
>   });
> });
> ```



> 



> > It works on my side i createed a file named router in /plugins then pasth the code and restart your app nuxt: 3.6.0
> 
> I tried this on Nuxt 3.5.2 and it worked but after upgrading to 3.6.5 it didn't. I updated the code following the [Lifecycle Hooks Usage with Plugins Documentation](https://nuxt.com/docs/guide/going-further/hooks#usage-with-plugins) and converted it into TypeScript.
> 
> **plugins/router.ts**
> 
> ```ts
> import { Router } from "vue-router";
> 
> interface CustomRouter extends Router {
>   running?: boolean;
>   nextRoute?: string | null;
> }
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   const customRouter: CustomRouter = useNuxtApp().$router;
> 
>   nuxtApp.hook("page:start", () => {
>     customRouter.running = false;
>     customRouter.beforeEach((to, _from, next) => {
>       if (customRouter.running) {
>         next(true);
>       } else {
>         customRouter.nextRoute = to.fullPath;
>         next(false);
>       }
>     });
>   });
>   nuxtApp.hook("page:transition:finish", () => {
>     customRouter.running = true;
>     if (customRouter.nextRoute) {
>       customRouter.push(customRouter.nextRoute);
>       customRouter.nextRoute = null;
>     }
>   });
> });
> ```

Thanks for the plugin, but if i am switching layout this doesn't work and clicking links just won't work because customRouter.running is false, had to refresh the page to make it work

**Comment by miclgael** [comment]
This is what works for me. A combo of other peoples work in this thread (thanks all!)

```vue
<script setup lang="ts">
onMounted (() => {
  if(process.env.NODE_ENV !== 'development') {
    // Work around for https://github.com/nuxt/nuxt/issues/13350
    // @TODO Remove when fixed
    if (typeof window !== 'undefined') {
      window.addEventListener('error', (ev) => {
        const messages = [
          `Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`, // Chromium
          `NotFoundError: Node.insertBefore: Child to insert before is not a child of this node`, // Firefox
          `NotFoundError: The object can not be found here.` // Safari
        ]

        if (messages.some((message) => ev.message.includes(message))) {
          console.warn('Reloading due to error: https://github.com/nuxt/nuxt/issues/13350')
          ev.preventDefault()
          window.location.reload()
        }
      })
    }
  }
})
</script>
```

Its not ideal, as I think the messages varies slightly between browser versions. 

I found that if this was running on develop then hot reloading no longer worked. So wrapped in the env check.

**Comment by DarkLink13** [comment]
I had the same problem and what based on @kissu, the problem was that I had commented code in the root of the index.vue, so it seems that nuxt understood that it had more than one root node.

**Comment by bgrand-ch** [comment]
Hello, same problem with page transition and when the tab becomes inactive (when I do something else on my PC or on other tabs and then come back to the page).

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.7.6
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

**Comment by mixmav** [comment]
None of the solutions above worked for me. I got this error on any page calling `useFetch()`, and I it also threw a Vue internal scheduler flush issue warning in the console (similar to #22552).

After hours of messing around, the only solution that worked was crating a custom RouterLink component and manually disabling it with a timeout to prevent fast navigation. Works for now, but hopefully this gets fixed soon.

**CustomNuxtLink.vue**
```
<template>
    <a :href="fullPath" :class="class" @click.prevent="handleClick">
        <slot />
    </a>
</template>

<script setup lang="ts">
import { RouteLocationRaw } from '#vue-router';

const router = useNuxtApp().$router;
const disabled = ref(false);

const props = defineProps<{
    to: RouteLocationRaw;
    class?: string;
}>();

const fullPath = ref(useNuxtApp().$router.resolve(props.to).fullPath);

const handleClick = () => {
    if (disabled.value) {
        return;
    }

    disabled.value = true;
    router.push(props.to);
    router.beforeResolve(() => {
        setTimeout(() => {
            disabled.value = false;
        }, 1000);
    });
};
</script>

```

**Comment by bayramorhan** [comment]
`"nuxt": "3.8.1",`
the problem still exists. (I ve tried most of the solutions above but none of them is really fixed)

**Comment by Endermanch** [comment]
Thank you, works great on Nuxt 3.8.1! Had to slightly tweak the plugin for it to work. In the end I called it `router.client.ts`.
The initial <Suspense /> issue has been resolved on Vue's side. Nuxt maintainers, any progress on the fix?

```ts
import type { Router } from 'vue-router'

interface CustomRouter extends Router {
  running?: boolean
  nextRoute?: string | null
}

export default defineNuxtPlugin((nuxtApp) => {
  const customRouter: CustomRouter = useRouter()

  nuxtApp.hook('page:start', () => {
    customRouter.running = false
    customRouter.beforeEach((to, _from, next) => {
      if (customRouter.running) {
        next(true)
      } else {
        customRouter.nextRoute = to.fullPath
        next(false)
      }
    })
  })

  nuxtApp.hook('page:transition:finish', () => {
    customRouter.running = true
    if (customRouter.nextRoute) {
      customRouter
        .push(customRouter.nextRoute)
        .then(() => (customRouter.nextRoute = null))
    }
  })
})
```

> > It works on my side i createed a file named router in /plugins then pasth the code and restart your app nuxt: 3.6.0
> 
> I tried this on Nuxt 3.5.2 and it worked but after upgrading to 3.6.5 it didn't. I updated the code following the [Lifecycle Hooks Usage with Plugins Documentation](https://nuxt.com/docs/guide/going-further/hooks#usage-with-plugins) and converted it into TypeScript.
> 
> **plugins/router.ts**
> 
> ```ts
> import { Router } from "vue-router";
> 
> interface CustomRouter extends Router {
>   running?: boolean;
>   nextRoute?: string | null;
> }
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   const customRouter: CustomRouter = useNuxtApp().$router;
> 
>   nuxtApp.hook("page:start", () => {
>     customRouter.running = false;
>     customRouter.beforeEach((to, _from, next) => {
>       if (customRouter.running) {
>         next(true);
>       } else {
>         customRouter.nextRoute = to.fullPath;
>         next(false);
>       }
>     });
>   });
>   nuxtApp.hook("page:transition:finish", () => {
>     customRouter.running = true;
>     if (customRouter.nextRoute) {
>       customRouter.push(customRouter.nextRoute);
>       customRouter.nextRoute = null;
>     }
>   });
> });
> ```

**Comment by bayramorhan** [comment]
@Endermanch Are you really sure it works great on nuxt 3.8.1 ? Beucase I just tried with your solution and it looked like its working but after few fast navigations after and after, I reproduced the same error. Sorry. But thank you anyways. 🙏

**Comment by Endermanch** [comment]
> @Endermanch Are you really sure it works great on nuxt 3.8.1 ? Beucase I just tried with your solution and it really looked like its working but I didn't stop navigating. After few "fast" route navigations, I reproduced the same error. Sorry. But thank you anyways. 🙏


https://github.com/nuxt/nuxt/assets/44542704/ca4dc477-ef68-4508-a42a-602ca9997884

**Comment by bayramorhan** [comment]
> > @Endermanch Are you really sure it works great on nuxt 3.8.1 ? Beucase I just tried with your solution and it really looked like its working but I didn't stop navigating. After few "fast" route navigations, I reproduced the same error. Sorry. But thank you anyways. 🙏
> 
> It does for me, here's the showcase: https://youtu.be/avSFaf0ww94
> 
> P. S. Don't mind the IDE showing errors, the JetBrains IDE is going wild sometimes

Do you have any async request on your pages that you navigating around?

**Comment by Endermanch** [comment]
> > > @Endermanch Are you really sure it works great on nuxt 3.8.1 ? Beucase I just tried with your solution and it really looked like its working but I didn't stop navigating. After few "fast" route navigations, I reproduced the same error. Sorry. But thank you anyways. 🙏
> > 
> > 
> > It does for me, here's the showcase: https://youtu.be/avSFaf0ww94
> > P. S. Don't mind the IDE showing errors, the JetBrains IDE is going wild sometimes
> 
> Do you have any async request on your pages that you navigating around?
> 
> Edit BTW I should tell that looks promising (99% Works) but im getting same error on 1% chance. and its enough for me not using it. :(

Nope, no async requests.

**Comment by bayramorhan** [comment]
> > > > @Endermanch Are you really sure it works great on nuxt 3.8.1 ? Beucase I just tried with your solution and it really looked like its working but I didn't stop navigating. After few "fast" route navigations, I reproduced the same error. Sorry. But thank you anyways. 🙏
> > > 
> > > 
> > > It does for me, here's the showcase: https://youtu.be/avSFaf0ww94
> > > P. S. Don't mind the IDE showing errors, the JetBrains IDE is going wild sometimes
> > 
> > 
> > Do you have any async request on your pages that you navigating around?
> > Edit BTW I should tell that looks promising (99% Works) but im getting same error on 1% chance. and its enough for me not using it. :(
> 
> Nope, no async requests.

async requests are highly increasing the chance of this problem occurs. (almost 70%)

**Comment by YozhikR** [comment]
В моем случае я столкнулся с такими проблемами:
Эта ошибка возникает когда в компоненте из хранилища или в самом компоненте я использую `useFetch`. Поэтому добавление `key` для ближайшего уровня `<NuxtPage>` решает мою проблему, но **_теряется анимация_**.
```vue
<NuxtPage :key="$route.fullPath"/>
```
Поэтому, я использую (костыль?). Я не могу найти точно, где в документации говорится что так делать не рекомендуется.
```vue
<Transition name="page" mode="out-in">
	<div :key="$route.fullPath">
		<NuxtPage />
	</div>
</Transition>
```
В моем случае это работает, и вроде бы ничего не ломается.

**Comment by CodeLearningSlayer** [comment]
> В моем случае я столкнулся с такими проблемами: Эта ошибка возникает когда в компоненте из хранилища или в самом компоненте я использую `useFetch`. Поэтому добавление `key` для ближайшего уровня `<NuxtPage>` решает мою проблему, но **_теряется анимация_**.
> 
> ```
> <NuxtPage :key="$route.fullPath"/>
> ```
> 
> Поэтому, я использую (костыль?). Я не могу найти точно, где в документации говорится что так делать не рекомендуется.
> 
> ```
> <Transition name="page" mode="out-in">
> 	<div :key="$route.fullPath">
> 		<NuxtPage />
> 	</div>
> </Transition>
> ```
> 
> В моем случае это работает, и вроде бы ничего не ломается.

https://nuxt.com/docs/api/components/nuxt-page#example - тут приведен правильный вариант, потому что использование $route может привести к проблемам с <Suspense>

**Comment by YozhikR** [comment]
Agree. But, странно конечно, 2024 год почти, я тоже во многом использую встроенные переводчики для китайского и английского. Но, разводить лишнюю беседу, не хочу. kekw

**Comment by dargmuesli** [comment]
[Vue 3.3.10](https://github.com/vuejs/core/releases/tag/v3.3.10) was just released :tada: 

- containing https://github.com/vuejs/core/pull/9309
- which resolved https://github.com/vuejs/core/issues/8105

As this issues was linked to the issue I mentioned, there is a good chance this issue could be resolved by updating Vue to `v3.3.10`. Would anyone affected please verify?

**Comment by leo91000** [comment]
> [Vue 3.3.10](https://github.com/vuejs/core/releases/tag/v3.3.10) was just released 🎉
> 
> * containing [fix(runtime-core): Suspense get anchor properly in Transition vuejs/core#9309](https://github.com/vuejs/core/pull/9309)
> * which resolved [`<Transition>` wrapped by `<Suspense>` breaks entirely if interrupted before it completes vuejs/core#8105](https://github.com/vuejs/core/issues/8105)
> 
> As this issues was linked to the issue I mentioned, there is a good chance this issue could be resolved by updating Vue to `v3.3.10`. Would anyone affected please verify?

Just tested quickly, it seems to work to have fix the issue !

**Comment by sdr0x07b6** [comment]
I'm glad I subscribed to this thread!

**Comment by MaxLikesCode** [comment]
Got an E-Mail Notification for every reply here and after 1 year and 4 months it's finally fixed 🥹

**Comment by dargmuesli** [comment]
Great! I understand the previous answers as confirmation, so I'll go ahead an close this issue :tada: 
If there are related issues please consider opening a new issue or - of course - we can reopen this issue if the issue would in fact turn out to not be resolved after all.

**Comment by ayitinya** [comment]
> Got an E-Mail Notification for every reply here and after 1 year and 4 months it's finally fixed 🥹

Same here, I can't even remember what brought me here in the first place

**Comment by daniluk4000** [comment]
> > Got an E-Mail Notification for every reply here and after 1 year and 4 months it's finally fixed 🥹
> 
> Same here, I can't even remember what brought me here in the first place

Random unknown issue in console maybe? :D

**Comment by pdahlenburg** [comment]
Using Nuxt 3.8.2 and still got the error. Using an async $fetch and the layout gets messed up 🥺

**Comment by bgrand-ch** [comment]
@pdahlenburg Nuxt 3.8.2 does not have the latest version of Vue. Please update Vue or wait for a new version of Nuxt.

**Comment by xushnudbek20** [comment]
> try setting a key to the top level `NuxtPage` in `app.vue` like so:
> 
> ```
> <template>
>   <NuxtLayout>
>     <NuxtPage :key="$route.fullPath"/>
>   </NuxtLayout>
> </template>
> ```

It brings another problem. If you want to add query on your currwnt route, o=full page will be reload

**Comment by bgrand-ch** [comment]
> [Vue 3.3.10](https://github.com/vuejs/core/releases/tag/v3.3.10) was just released 🎉
> 
> * containing [fix(runtime-core): Suspense get anchor properly in Transition vuejs/core#9309](https://github.com/vuejs/core/pull/9309)
> * which resolved [`<Transition>` wrapped by `<Suspense>` breaks entirely if interrupted before it completes vuejs/core#8105](https://github.com/vuejs/core/issues/8105)
> 
> As this issues was linked to the issue I mentioned, there is a good chance this issue could be resolved by updating Vue to `v3.3.10`. Would anyone affected please verify?

Works perfectly! Thanks

**Comment by IvanWala** [comment]
With Ubuntu 18.19 and this assets

"devDependencies": {
    "@nuxt-alt/proxy": "^2.4.9",
    "@nuxt/devtools": "^1.0.6",
    "@nuxt/kit": "^3.9.0",
    "@nuxtjs/strapi": "^1.10.1",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@tato30/vue-pdf": "^1.9.1",
    "@types/markdown-it": "^13.0.7",
    "@vue-leaflet/vue-leaflet": "^0.10.1",
    "@vueuse/core": "^10.7.1",
    "@vueuse/nuxt": "^10.7.1",
    "axios": "^1.6.3",
    "leaflet": "^1.9.4",
    "luxon": "^3.4.4",
    "markdown-it": "^14.0.0",
    "markdown-it-attrs": "^4.1.6",
    "nuxt": "^3.9.0",
    "nuxt-swiper": "^1.2.2",
    "pinia": "^2.1.7",
    "qs": "^6.11.2",
    "sass": "^1.69.7",
    "vue": "^3.4.3",
    "vue-icomoon": "^0.6.1",
    "vue-recaptcha-v3": "^2.0.1",
    "vue-router": "^4.2.5",
    "vue3-google-login": "^2.0.25"
  },
  "dependencies": {
    "@mdi/font": "^7.4.47",
    "@nuxtjs/i18n": "^8.0.0",
    "vite-plugin-vuetify": "^2.0.1",
    "vuetify": "^3.4.9"
  }

Stills fails for us.

**Comment by manniL** [comment]
If you can reproduce the issue, then please create a new issue (and feel free to link to this one) @IvanWala 
**Please make sure to include a minimal reproduction though**. Saying "I use this and this packages" or dumping the whole project is not a valid repro.

**Comment by miclgael** [comment]
Fixed in this release for me https://github.com/nuxt/nuxt/releases/tag/v3.9.1

**Comment by fedikan** [comment]
Still facing this issue while using router.replace with nuxt@3.10.2.

**Comment by miclgael** [comment]
> Still facing this issue while using router.replace with nuxt@3.10.2.

hi @fedikan - do you happen to have traces of the older vue still in your project?

**Comment by fedikan** [comment]
> > Still facing this issue while using router.replace with nuxt@3.10.2.
> 
> hi @fedikan - do you happen to have traces of the older vue still in your project?

No, i have fully cleaned .nuxt, node_modules and package-lock. But seems like router is fully broken after update.

**Comment by fedikan** [comment]
> > Still facing this issue while using router.replace with nuxt@3.10.2.
> 
> hi @fedikan - do you happen to have traces of the older vue still in your project?

Yeah, i have fully cleared node_modules, .nuxt and package-lock. But seems like the issue is related to mounting algorithm changes, or to some hydration problems. Still figuring out :/

**Comment by akirarika** [comment]
I've encountered a similar issue, but it wasn't caused by having multiple root nodes. Instead, it was due to the presence of teleport, which resulted in multiple nodes being inserted into the root. I'm leaving this comment to let others who might come across this issue know:

You can check if the parent node of your <NuxtPage /> has multiple child nodes. This might not necessarily be caused by your page having multiple root nodes—it could also be due to teleport inserting multiple child nodes.
