### ISSUE TITLE
Nuxt 3, sourcemap points to missing file warning, when using external script files in vue template. 

### ISSUE THREAD

**Issue by bootsmann1995** [nuxt/nuxt#14124]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.3.0`
- Builder:          `vite`
- User Config:      `privateRuntimeConfig`, `publicRuntimeConfig`, `pageTransition`, `css`, `app`, `algolia`, `components`, `router`, `modules`, `build`, `vite`, `hooks`, `nitro`
- Runtime Modules:  `@vueuse/nuxt@8.6.0`, `~/modules/sitemap`, `@nuxtjs/algolia@0.9.2`, `~/modules/robots`, `~/modules/staticWebApp`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-jbyf5k-sa9vua?file=pages%2Findex.vue

### Describe the bug

When using external script files it gives an warning pr. import in my solution: 

"Sourcemap for "C:/Folder/repo/filepath.page.ts" points to missing source files ."

![image](https://user-images.githubusercontent.com/65391517/172868024-d79eb683-e7c0-4ab1-a905-473d66cd6291.png)

Is there a confirguration to disable sourcemap for at certain suffix file? I think this is poitning to vite in nuxt.
 

### Additional context

I can see there is a similar issue on react regarding this warning. https://github.com/vitejs/vite/issues/5438

**Comment by BayBreezy** [comment]
Hey team,

This issue popped up again in v3.1.1. Not sure if it was resolved before.
I am using vuetify v3.1.2 with the vite-plugin-vuetify package.

**Comment by moealien** [comment]
Started getting this issue on some imports. ^3.0.0

**Comment by rashidpathiyil** [comment]
Getting this error after upgrading to Nuxt `3.3.2` and login stop working

``` 
WARN  Sourcemap for "virtual:nuxt:/Users/rashidpathiyil/<project>/.nuxt/http.plugin.mjs" points to missing source files

WARN  Sourcemap for "virtual:nuxt:/Users/rashidpathiyil/<project>/.nuxt/auth.plugin.mjs" points to missing source files
```

**Comment by danielroe** [comment]
This should be resolved in the latest Vite release via https://github.com/vitejs/vite/pull/12444. Perhaps try refreshing your lockfile and confirming?

**Comment by rashidpathiyil** [comment]
> This should be resolved in the latest Vite release (v4.2.1) via [vitejs/vite#12444](https://github.com/vitejs/vite/pull/12444). Perhaps try refreshing your lockfile and confirming?

That error is gone when I run this now
![image](https://user-images.githubusercontent.com/15140041/228217265-1ac72357-d276-41cb-be63-6bab4695dc72.png)

But the login only works after downgrading this
"@nuxt-alt/auth": "2.2.0",
"@nuxt-alt/http": "1.5.7",

Anyway thanks **Dani** 💚

**Comment by jakubhruby** [comment]
I still have the warning messages after upgrading lockfile and cleaning yarn cache and node_modules.

**Comment by leosin** [comment]
I just loaded a normal scss file.

but
I can remove warn in this way，
```js
export default defineNuxtConfig({
  sourcemap: { server: true, client: false }
})
```

**Comment by wtagain** [comment]
Same issue.

**Comment by horizon188** [comment]
Same issue.

**Comment by horizon188** [comment]
nuxt:3.5.0

**Comment by VegasChickiChicki** [comment]
Same issue.

**Comment by shynline** [comment]
Same issue.

**Comment by bootsmann1995** [comment]
@horizon188  @VegasChickiChicki @shynline  you can use sourcemap: false in nuxt.config

**Comment by AhmedKaram50** [comment]
![image](https://github.com/nuxt/nuxt/assets/64335793/69b208b7-30b4-4800-81a2-aeb29b8cc02b)

any ideas ?

i am using Nuxt 3.3 with i18n

**Comment by AndrewBogdanovTSS** [comment]
I  tried 
```
export default defineNuxtConfig({
  sourcemap: { server: true, client: false }
})
```
but still get warnings 
![image](https://github.com/nuxt/nuxt/assets/2766448/24ad04fe-1e9c-4f44-81bb-039d5a8b49da)

**Comment by mhdSid** [comment]
same issue

**Comment by selucaciu** [comment]
same issue

**Comment by rczdgbg** [comment]
![image](https://github.com/nuxt/nuxt/assets/38928451/53475116-cd65-428d-b7e3-cdd7c364a63c)

**Comment by awefeng** [comment]
what a bullshit bug, Set`sourcemap: { client: false, server: false },` ok, you lost source map feature, one set to true, fuxk, a million warnnig!

**Comment by OrbisK** [comment]
The original reproduction cannot be reproduced with the latest Nuxt version ([Stackblitz](https://stackblitz.com/edit/github-jbyf5k-us6mfwlu?file=nuxt.config.ts)). Does anyone have an up-to-date reproduction?
