### ISSUE TITLE
Using an async method inside an anonymous middleware causes a nuxt instance unavailable

### ISSUE THREAD

**Issue by ptoussai** [nuxt/nuxt#18459]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@3.3.1`
- Builder:          `vite`
- User Config:      `workspaceDir`, `vite`, `server`, `runtimeConfig`, `hooks`, `router`, `head`, `css`, `buildModules`, `render`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/postcss8@1.1.3`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-beockb?file=pages%2Findex.vue

### Describe the bug

This simple example as seen in #14269 still does not work and `nuxt instance unavailable` is thrown on the server.

```
<script setup>
definePageMeta({
  middleware: defineNuxtRouteMiddleware(async () => {
    await new Promise((resolve) => setTimeout(resolve, 200)); // having await in
    return navigateTo('/auth');
  }),
});
</script>
```

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Comment by ptoussai** [comment]
This is still a problem: https://stackblitz.com/edit/nuxt-starter-lpbyvt?file=pages%2Findex.vue
