### ISSUE TITLE
Add a way to access Cloudflare Pages Bindings

### ISSUE THREAD

**Issue by dario-piotrowicz** [nuxt/nuxt#18599]
### Describe the feature

Hi, I'm trying to create a Nuxt application and deploy it via [Cloudflare Pages](https://pages.cloudflare.com/)

When you deploy an application via Cloudflare Pages you can access other Cloudflare products via [bindings](https://developers.cloudflare.com/pages/platform/functions/bindings/) (which basically allow you to store data, etc...)

The issue is that I believe that such bindings are not made accessible by Nuxt (I expected to maybe find them in the `H3EventContext` but no luck, as you can see here: [my gh nuxt get context test](https://github.com/dario-piotrowicz/my-nuxt-app/blob/88f115dc2b99caf4b4e64403c2400314ebc92fce/server/api/test.get.ts) (deployed [here](https://my-nuxt-app-edm.pages.dev/)))

AFAIK meta-frameworks such as Nuxt all (or almost all) provide a way to access such context, like for example:
 - [Remix](https://remix.run/docs/en/v1/guides/data-loading#cloudflare-kv)
 - [SvelteKit](https://kit.svelte.dev/docs/adapter-cloudflare#environment-variables)
 - [Qwik](https://qwik.builder.io/integrations/deployments/cloudflare-pages/#context)
 - SolidStart (although I can't see that in the documentation)
 - Next (via node compatibility in the `process.env`, via [`next-on-pages`](https://github.com/cloudflare/next-on-pages))
 - etc...
 
 Would there be any chance for this context to also be available in Nuxt? :pray: 
 (Because otherwise this creates a non trivial limitation for the use of Nuxt with Cloudflare Pages)
 
 (Naturally please let me know if the context is actually available somewhere and I just missed it :sweat_smile: )

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by dario-piotrowicz** [comment]
I suspect that this limitation comes from h3, so I've created an issue there as well: https://github.com/unjs/h3/issues/309

But I wanted to create one here as well so that devs can stumble across it when trying to use Cloudflare bindings with Nuxt.

I hope this is fine :bow:

**Comment by dario-piotrowicz** [comment]
Note, the context needs to be passed by nitro first which is currently not happening: https://github.com/unjs/nitro/issues/773

**Comment by danielroe** [comment]
Yes, this likely would have to be (and should be) implemented in Nitro. See this PR: https://github.com/unjs/nitro/pull/677.

**Comment by dario-piotrowicz** [comment]
@danielroe ah cool, I missed the PR, thanks! :slightly_smiling_face:

**Comment by harlan-zw** [comment]
@dario-piotrowicz Is this solved with https://github.com/unjs/nitro/pull/927?

**Comment by dario-piotrowicz** [comment]
Hi @harlan-zw, sorry for the later reply, I totally missed your message :bow: 

Anyways no I'm sorry that didn't fix the issue, it is exposing the [cf properties](https://developers.cloudflare.com/workers//runtime-apis/request#incomingrequestcfproperties) which are a different set on cloudflare info which is not related to the bindings

If you cloud please reopen this issue that's be great :pray:

**Comment by dario-piotrowicz** [comment]
thanks a lot @harlan-zw :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment]
@harlan-zw I've opened a PR that should allow access to the bindings :slightly_smiling_face: https://github.com/unjs/nitro/pull/997

with that since fix users should be able to access the bindings via `event.context.env` (in their `H3Event`)

**Comment by dario-piotrowicz** [comment]
Closing this issue as Bindings (as well as `ctx` and `env`) are now available 🙂
