### ISSUE TITLE
Circular dependency in nuxt with nitropack

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#18789]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

and stackblitz 

### Reproduction

https://stackblitz.com/edit/nuxt-starter-kqf57y?file=README.md

### Describe the bug

Hi :wave:  !
Nuxt build in 3.1.2 logs a warning about circular dependency

### Logs

```shell-script
`
Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
````
```

**Comment by manniL** [comment]
Related https://github.com/nuxt/nuxt/issues/18766 ?

**Comment by huang-julien** [comment]
this might be related, i'm using 3.1.2 while @Barbapapazes is using 3.1.1. 
I tried to use `useHead` in a component and then build a project but this did not trigger the warning with `useHead`

**Comment by madebyfabian** [comment]
If you do a clean upgrade to both newest versions (notice you're using 3.1**.1** and 2.1**.2** here), the error does not exist for me.

**Comment by Zerro97** [comment]
There is similar [issue](https://github.com/nuxt/content/issues/1880) raised at nuxt content repo

**Comment by Zerro97** [comment]
I previously had cloudflare deployment failing with this circular dependency warning but I managed to resolve the deployment failure by specifying .output/public as the Build output directory. Previously I was using default dist folder as the output directory.

**Comment by sandercoffee** [comment]
> I [previously](https://github.com/nuxt/content/issues/1880) had cloudflare deployment failing with this circular dependency warning but I managed to resolve the deployment failure by specifying .output/public as the Build output directory. Previously I was using default dist folder as the output directory.

Can you give an example of the file and code?

**Comment by Zerro97** [comment]
So I had my [blog](https://github.com/Zerro97/khuibeom.com) failing deployment originally, so I made this [repo](https://github.com/Zerro97/cloudflare-deployment-test) with fresh nuxt setup for testing purpose. 

Both of them were failing in deployment but that was because in Cloudflare setting, I was using the default `dist` build output directory instead of specifying it as `.output/public`

**Comment by StefanoTesla** [comment]
same problem here, generated a basic ssg with only i18n static site, the static version goes in an inifinite loop loading, the ssr instead seems work correctly, but i need ssg you can check here #18876

**Comment by danielroe** [comment]
cc: @pi0

**Comment by StefanoTesla** [comment]
```
 WARN  Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

I continue to get the message

Nuxt project info:                                                                                                                                                                                                         09:03:47

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.4.2`
- Builder:          `vite`
- User Config:      `pages`, `css`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9-27926914.891e694`
- Build Modules:    `-`
------------------------------

**Comment by madebyfabian** [comment]
@StefanoTesla probably because the fix not released yet, just merged, right?

**Comment by StefanoTesla** [comment]
> @StefanoTesla probably because the fix not released yet, just merged, right?
> 
> Edit: oh I see a new nuxt version has been released 1hr ago.. awesome 💚💚🎉🎉

I seen the merged changes reflected to the My repo.
I update now to the last version but warning isnt disappeared

**Comment by Barbapapazes** [comment]
Fix is released in nitro 2.2.1 but nuxt 3.2.0 use nitro 2.2.0

**Comment by StefanoTesla** [comment]
> Fix is released in nitro 2.2.1 but nuxt 3.2.0 use nitro 2.2.0


Nuxt 3.2.0 dependency use `"nitropack": "^2.2.1"`

`"node_modules/nuxt": {
      "version": "3.2.0",
      "resolved": "https://registry.npmjs.org/nuxt/-/nuxt-3.2.0.tgz",
      "integrity": "sha512-8jAYyjU1Ht+MXPLLDIdIUmV56KiI0g7KusKwzvqn+vlzyCNtSHg2W/VBCGw5QWplb/MXruogcMl2sDenlQRZFg==",
      "dev": true,
      "dependencies": {
[..]
        "nitropack": "^2.2.1",
        "nuxi": "3.2.0",
[..]
      },`









- Operating System: `Windows_NT`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.4.2`
- Builder:          `vite`
- User Config:      `pages`, `css`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9-27926914.891e694`
- Build Modules:    `-`

**Comment by pi0** [comment]
I hope issue is fixed in last release. You can try nuxi upgrade —force 

in cast of 2.2.1 reproducing issues, please ping me with a reproduction to reopen :)

**Comment by ram-you** [comment]
Hi @pi0 
I have the latest version though.
Nuxi 3.2.0
Nuxt 3.2.0 with Nitro 2.2.1
but still have the warning:
```
Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```
Thank you

**Comment by manniL** [comment]
@ram-you Could you please provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by StefanoTesla** [comment]
> @ram-you Could you please provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

https://github.com/StefanoTesla/nuxtproject

**Comment by ram-you** [comment]
Hi @manniL 
My code was working fine from early versions of Nuxt3 up to v3.1.2.
The warning message started after updating to Nuxt 3.2.0 and I think I'm not the only one.
If some more people could verify that would be great!

**Comment by wallchr** [comment]
Same issue here with Nuxt 3.2.0 and Nitro 2.2.1 on Netlify and local build

```
8:06:34 AM: Export "useNitroApp" of module "../../node_modules/.pnpm/nitropack@2.2.1/node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "../../node_modules/.pnpm/nitropack@2.2.1/node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
8:06:34 AM: Either change the import in "../../node_modules/.pnpm/nuxt@3.2.0/node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

**Comment by emaia** [comment]
> Same issue here with Nuxt 3.2.0 and Nitro 2.2.1 on Netlify and local build
> 
> ```
> 8:06:34 AM: Export "useNitroApp" of module "../../node_modules/.pnpm/nitropack@2.2.1/node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "../../node_modules/.pnpm/nitropack@2.2.1/node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
> 8:06:34 AM: Either change the import in "../../node_modules/.pnpm/nuxt@3.2.0/node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
> ```

Same issue here.

**Comment by manniL** [comment]
> > @ram-you Could you please provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> [StefanoTesla/nuxtproject](https://github.com/StefanoTesla/nuxtproject)

Thanks! Can be reproduced with this repo + `npm build`

**Comment by steve-r-lewis** [comment]
# Possible bug still present?
@danielroe this is all new to me so please excuse me if my post is irrelevant.  I'm still getting this warning.  Most things seem to be working so I'm not sure if it is a problem and I lack the skill or knowledge to understand if I should be concerned or not. I'd be grateful if someone could clarify this for me please.

## Environment
- Operating System: Debian GNU/Linux 11 (bullseye)
- Node Version:    19.6.0
- Package Manager: npm@9.4.2
- Package Manager: pnpm@7.27.0
- (npm@9.4.2)
- Nuxi Version:  3.2.0    
- Nuxt Version:  3.2.0
- Nitro Version: 2.2.1
- Builder: vite@4.1.1

## Reproduction
[https://stackblitz.com/edit/nuxt-starter-xdi2wg?file=README.md](https://stackblitz.com/edit/nuxt-starter-xdi2wg?file=README.md)

## Logs
`Export "useNitroApp" of module "node_modules/.pnpm/nitropack@2.2.1/node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/.pnpm/nitropack@2.2.1/node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.`

`Either change the import in "node_modules/.pnpm/nuxt@3.2.0/node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.`

**Comment by StefanoTesla** [comment]
I confirm the persistence of the warning in building and generation process

**Comment by danielroe** [comment]
Indeed, it's still present in 3.2.0, but it should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

**Comment by StefanoTesla** [comment]
Thank you for clarification 🙂

**Comment by fabianwohlfart** [comment]
I get this error with a fresh package and the `build` command.
Do we have any solutions to it?

```
Nuxt 3.6.5 with Nitro 2.6.0 

✔ Generated public .output/public                                                                                                                                         nitro 11:34:52
ℹ Building Nitro Server (preset: node-server)                                                                                                                             nitro 11:34:52
Export "useNitroApp" of module "../../../node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "../../../node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/api/test.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
✔ Nitro server built  
``` 

### server/api/test.js
```
export default defineEventHandler(async (event) => {
  const nitroApp = useNitroApp()
  console.log(nitroApp)
  return true
})
```

**Comment by danielroe** [comment]
Thanks for the report. Raised https://github.com/nuxt/nuxt/pull/22785.

**Comment by cshomo11** [comment]
I'm seeing a similar circular dependency in Nuxt 3.8.2 with Nitro 2.8.1 (and Nuxt 3.8.0 before I tried an update) where `useRuntimeConfig` is being flagged.

```
 ERROR  [worker reload] [worker init] Cannot access '_sharedRuntimeConfig' before initialization                                                             12:33:34 PM

  at useRuntimeConfig (node_modules/nitropack/dist/runtime/config.mjs:13:5)
  at <anonymous> (node_modules/nitropack/dist/runtime/route-rules.mjs:11:16)
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

And these errors when I run the build command

```
Export "useRuntimeConfig" of module "node_modules/nitropack/dist/runtime/config.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt/dist/core/runtime/nitro/paths.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "getRouteRules" of module "node_modules/nitropack/dist/runtime/route-rules.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt/dist/core/runtime/nitro/renderer.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "useRuntimeConfig" of module "node_modules/nitropack/dist/runtime/config.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt/dist/core/runtime/nitro/renderer.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "useRuntimeConfig" of module "node_modules/nitropack/dist/runtime/config.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in ".nuxt/dist/server/server.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

At first, I suspected this was due to a use of `useRuntimeConfig` in a Nitro hook plugin. But I rewrote that plugin to remove the use of the runtime config, and it was still being flagged in the build and when trying to run dev.

**Comment by dargmuesli** [comment]
I also started seeing this again (reference https://github.com/harlan-zw/nuxt-og-image/issues/122).

**Comment by cshomo11** [comment]
To provide a little more context for [my previous comment,](https://github.com/nuxt/nuxt/issues/18789#issuecomment-1847591330) I did some digging in the generated `.nuxt/dev/index.mjs`. It looks to be referencing `useRuntimeConfig` well before it is defined in the file.

In my file it starts with this block at line 920:
```
const config$1 = useRuntimeConfig();
const _routeRulesMatcher = toRouteMatcher(
  createRouter({ routes: config$1.nitro.routeRules })
);
function createRouteRulesHandler(ctx) {
  return eventHandler((event) => {
    const routeRules = getRouteRules(event);
    if (routeRules.headers) {
      setHeaders(event, routeRules.headers);
    }
    if (routeRules.redirect) {
      return sendRedirect(
        event,
        routeRules.redirect.to,
        routeRules.redirect.statusCode
      );
    }
    if (routeRules.proxy) {
      let target = routeRules.proxy.to;
      if (target.endsWith("/**")) {
        let targetPath = event.path;
        const strpBase = routeRules.proxy._proxyStripBase;
        if (strpBase) {
          targetPath = withoutBase(targetPath, strpBase);
        }
        target = joinURL(target.slice(0, -3), targetPath);
      } else if (event.path.includes("?")) {
        const query = getQuery(event.path);
        target = withQuery(target, query);
      }
      return proxyRequest(event, target, {
        fetch: ctx.localFetch,
        ...routeRules.proxy
      });
    }
  });
}
```

That is being imported from `nitropack/dist/runtime/route-rules.mjs`.

However the definition of `useRuntimeConfig` that is found in `nitropack/dist/runtime/config.mjs` is not injected into my `dev/index.mjs` until line 1795.

```
const _sharedRuntimeConfig = _deepFreeze(
  _applyEnv(klona(_inlineRuntimeConfig))
);
function useRuntimeConfig(event) {
  if (!event) {
    return _sharedRuntimeConfig;
  }
  if (event.context.nitro.runtimeConfig) {
    return event.context.nitro.runtimeConfig;
  }
  const runtimeConfig = klona(_inlineRuntimeConfig);
  _applyEnv(runtimeConfig);
  event.context.nitro.runtimeConfig = runtimeConfig;
  return runtimeConfig;
}
const _sharedAppConfig = _deepFreeze(klona(appConfig));
function useAppConfig(event) {
  if (!event) {
    return _sharedAppConfig;
  }
  if (event.context.nitro.appConfig) {
    return event.context.nitro.appConfig;
  }
  const appConfig$1 = klona(appConfig);
  event.context.nitro.appConfig = appConfig$1;
  return appConfig$1;
}
```

This is currently blocking us from running the dev environment locally and I cannot tell if this is just a import or reference I need to move around or if this is something inside of Nitro.

If it is helpful I can move this to a new bug report but I just wanted to check and see if this was something I was maybe doing or not.

**Comment by dargmuesli** [comment]
Given the detailed description, I reopen this issue.

**Comment by danielroe** [comment]
That looks like it might be a nitropack issue...

What do you think @pi0?

**Comment by pi0** [comment]
Is there a recent minimal reproduction based on either Nuxt or Nitro?

**Comment by cshomo11** [comment]
I can try to track down a minimal reproduction of the issue. I am not sure exactly what triggered the issue originally as it occured during my projects transition from Nuxt 2 to Nuxt 3. I suspect maybe it was when we introduced custom router rules but I will see if I can make a new repo with the issue.

**Comment by cshomo11** [comment]
Ah I found the issue. We had a config that was being imported into our core layer's app config. That config was importing composable functions. When I commented those out the error went away. I'm going to rework the config so that we don't directly import those composables into the config. Just a casualty of converting a lot of JSON based configs into one main app.config.ts file.

**Comment by dargmuesli** [comment]
So, it was a project-specific issue, not something to fix in Nuxt? Then I'd close this issue again :raised_hands:

**Comment by cshomo11** [comment]
Yes this can be closed out again. Sorry for the confusion

**Comment by tberk** [comment]
Getting the same errors on my build too, which uses nitro plugins..

**Comment by pi0** [comment]
please open a new issue with reproduction 🙏🏼

**Comment by fabianwohlfart** [comment]
Did you guys try this? https://github.com/nuxt/nuxt/pull/22785#issuecomment-1697171634

`import { useNitroApp } from '#internal/nitro/app'`

**Comment by noook** [comment]
@fabianwohlfart This indeed suppressed the error
