### ISSUE TITLE
Hot reload is not working

### ISSUE THREAD

**Issue by mrniamster** [nuxt/nuxt#18964]
Issue#1: 
Changes from code editor is not reflecting on the app, Clearing Cache / Reloading the page manually do work.

Issue#2- linked:  
When ever there is an exception , say 500 / module not found, after correcting the code, the page don't reload itself, have to restart server.

Files located inside - pages directory,
System: windows 10,
Nuxi 3.2.0                                                                        
Nuxt 3.2.0 with Nitro 2.2.1  

What i have tried? 
- Modified nuxt.config.js as per [one of solution](https://lightrun.com/answers/nuxt-framework-hmr-does-not-pick-up-updates-to-data)
```
  ssr:false,
  vite: {
    server: {
      watch: {
        usePolling: true,
      },
    },
  },
```

Demo:

https://user-images.githubusercontent.com/52563039/218277543-0596cca6-bb2f-42f8-adb9-2238bc6d60a1.mp4

**Comment by manniL** [comment]
Does that happen on a new project too?

Also sounds a little like https://github.com/nuxt/nuxt/issues/18897

**Comment by mrniamster** [comment]
@manniL  Hello Alex,

Yes, it does happen in new project to , 

Another thing i noticed when there is a v-for , and key is provided, during these scenarios also the changes are not reflecting, when changes are done to to child

```
<parent v-for="i in 10" :key="i">
<child id="i">
</parent>
```

Previously while i tried the  "experimental nuxt icon" , the preview in the vscode -  did work good, but after some time it also stopped working.

**Comment by VladStepanov** [comment]
Have a question just to clarify. Is project in docker container?
Also provide please logs of devtools console

**Comment by mrniamster** [comment]
@VladStepanov No, this is not a docker container,

In devtools i'm not getting any logs yet, 

unlike nuxt 2 , i'm facing this issue during fresh install of nuxt 3.2

**Comment by volk234** [comment]
I have same issue.
HMR works only on client. After some changes in components, the server initially renders the old content. Then client replaces it with updated content.

Nuxt 3.2

**Comment by nakorndev** [comment]
> I have same issue. HMR works only on client. After some changes in components, the server initially renders the old content. Then client replaces it with updated content.
> 
> Nuxt 3.2

Confirmed. I have the same on this issue. After saving some new code then the client render will be updated. But the server does not. So I always have to stop the dev server by `Ctrl + C` and then re-run `npm run dev` most of the time to make the server content to be updated.

But I can't reproduce this issue even though I faced problems. My project uses a lot of code and it is private repo. If I find some simple bug I will make an example for you and may open new issues.

**Comment by nimens55** [comment]
I also have this problem. When saving, the changes are applied only on the client, the old content is displayed on the server.

I tried to install a new project, the result is the same. I'll try it today on another computer, I'll write about the results

**Comment by CuteCubed** [comment]
Can confirm the same Problem, happened after upgrading to 3.2, 3.0  was working fine

**Comment by volk234** [comment]
> Can confirm the same Problem, happened after upgrading to 3.2, 3.0 was working fine

To clarify, I also had this problem with RC builds.
My projects have pinia and windicss dependencies.

**Comment by nimens55** [comment]
I checked it on my home PC (Windows 11), the same thing

**Comment by Eflyax** [comment]
I have same issue.

Update from 3.0.0 to 3.2.0 break SSR changes. Everything works on client side but SSR is not reflecting any changes.

Nuxt 3.2.0

**Comment by roccojanse** [comment]
Same here, seems like a Nitro server issue, Nuxt 3.0.0 doesn't have problems. Downgrading from Nuxt 3.2 to 3.1 doesn't fix it, because it still depends on Nitro 2.2.1.

**Comment by renardsas** [comment]
I have same issue.
3.2.0 break SSR changes with new project or update from 3.0.0 to 3.2.0.
Everything works on client side but SSR is not reflecting any changes.
Nuxt 3.2.0
Nitro 2.2.1.
Window 11

✅ Nuxt 3.0.0
❌ Nuxt 3.1.0
❌ Nuxt 3.2.0

**Comment by nvkhai603** [comment]
I have same issue with 3.2.0

**Comment by Beachman4** [comment]
I managed to temporarily resolve this by adding

```
nitro: {
    devServer: {
      // My files are under src, if yours are in the root you can change this to ./
      watch: ['./src']
    }
}
```

to `nuxt.config.ts`.

**Comment by danielroe** [comment]
We've just merged a fix for a very similar issue of HMR on Windows. Would anyone experiencing this be happy to test the fix via the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/)?

**Comment by renardsas** [comment]
> We've just merged a fix for a very similar issue of HMR on Windows. Would anyone experiencing this be happy to test the fix via the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/)?

I actually already tested the fix via the edge channel and it seems to be working for me. Thanks for the quick resolution of this issue ! 🙏🙏🙏

**Comment by Quineone** [comment]
> We've just merged a fix for a very similar issue of HMR on Windows. Would anyone experiencing this be happy to test the fix via the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/)?

Still don't work for me, even via the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/)
![image](https://user-images.githubusercontent.com/15320933/220604246-0fbdfb79-004f-4226-ac1a-b6a7433782e2.png)

**Comment by Monty9120** [comment]
Might be unrelated, but my hot reload issue was fixed by removing the `extractCSS` property in `nuxt.config`

Credit to this reddit post:
https://www.reddit.com/r/Nuxt/comments/b7tkbm/disablefix_hot_module_reloading/

**Comment by jkd77** [comment]
The feedback is much appreciated. My nuxt.config.ts only has:

`export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss'],
});`

**Comment by renardsas** [comment]
> The feedback is much appreciated. My nuxt.config.ts only has:
> 
> `export default defineNuxtConfig({ modules: ['@nuxtjs/tailwindcss'], });`

Hi,
This issue is for Windows and for Nuxt version >= 3.0.1.
Have you tried to test the fix via the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) ?
If yes, and it's still not working, you can open a new issue.

**Comment by jkd77** [comment]
I did try the edge channel fix and it didn't work. I suppose I'll open a new issue...

**Comment by mklueh** [comment]
Where is the old content even coming from? Because I've deleted the .nuxt folder and I thought there was the caching happening

**Comment by roccojanse** [comment]
Hi, I recently updated Nuxt to 3.2.3 and Nitro to 2.2.3 and the hydration/reloading issues are fixed in my project, without changing sourcecode. Maybe this combination of Nuxt and Nitro fixes things.

**Comment by mklueh** [comment]
@roccojanse maybe it's something else for me, it seems new elements are disappearing after being rendered. Not sure if it's Nuxt or something else, but I don't see errors

**Comment by briankandersen** [comment]
I have this issue still. I am using the absolute latest version of both npx nuxi and latest edge nuxt. It fails on both WSL Ubuntu and also on a native ubuntu. This is totally clean and new installations. None of the above solutions have provide any work results

**Comment by tenerecodes** [comment]
For me the problem was fixed by adding port mapping of 24678 in docker-compose.yml

``` yaml
build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-website
    ports:
      - 3000:3000
      - 24678:24678

**Comment by varna** [comment]
Getting strange behavior too:

- Have a button with `class=""`
- Delete `.nuxt` folder and start new `pnpm dev`
- Add `rounded-full px-2` classes to button
- Hot reload works properly, `rounded-full px-2` visible in page
- Add `-ml-2` class
- Hot reload failed, `-ml-2`, doesn't exist on the web.
- Do a manual reload with CMD+R.
- Button reverts to original button without ANY classes.
- Delete `.nuxt` folder and start new `pnpm dev`
- Button has ALL `rounded-full px-2 -ml-2` classes

**Comment by miketests** [comment]
I have the same issue.
I've just created fresh new Nuxt project but hot reload doesn't work when I replace `<NuxtWelcome />` component with any other HTML element in the `app.vue` file.

Node: v16.14.2
NPM: 8.5.0
Nuxi: 3.5.3
Nuxt: 3.5.3
Nitro: 2.4.1

**Comment by doubleyooz** [comment]
In my case it doesn't hot reload when I update the style tag, it works fine with the script and template tags.

**Comment by yashinshekh** [comment]
> ```yaml
> - 24678:24678
> ```

wow... this works.

**Comment by yashinshekh** [comment]
> Hot reloading fails for me when I make any changes to layouts. Is there a key I can press in the terminal to get Nuxt / Nitro to just re-compile?

if you are using docker make sure to mount the volume

volumes:
      - .:/frontend
      
the frontend should be your working directory in 

here is my Dockerfile configuration

# Use an official Node.js runtime as a parent image
FROM node:16-alpine

WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev","--","--host"]

after this the hotreload seemed to be working

**Comment by mhdSid** [comment]
@danielroe sure !! I would love to!!

**Comment by lafllamme** [comment]
Any updates on this? This is not fixed.


I have this issue for every Nuxt 3 application on Windows using WSL and Docker.
I managed to use HMR using the polling option for watch.

Sadly, it is not working for page views. Every time I add a new view under /pages, I need to restart my dev server, so it recognized my changes. Otherwise, I am not allowed to use <NuxtLink> or <NuxtPage> for a component that I just created. Adding the HMR settings made no difference.


I added this to my docker-compose:

```
version: '3.8'
services:
  bun-service:
    image: oven/bun:1 # The image name
    container_name: bun-service
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./app:/home/bun/app
    restart: always
    command: ["tail", "-f", "/dev/null"]
    environment:
      - NODE_ENV=dev
      - PATH=$PATH:/home/bun/.bun/bin
    user: bun
```
and this to my nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    devtools: {
        enabled: true,

        timeline: {
            enabled: true
        }
    },
    app: {
        pageTransition: {
            name: 'page',
            mode: 'out-in'
        }
    },
    //pages: true,
    //fix issue for docker not reflecting changes
    vite: {
        server: {
            hmr: {
                protocol: 'ws',
                host: 'localhost'
            },
            watch: {
                usePolling: true,
                interval: 1000,
            },
        },
    },
})
```

**Comment by ahmetonurslmz** [comment]
Here you can read some suggestions for the problem
[https://ahmetonursolmaz.org/nuxt-hot-reload-isnt-working/](https://ahmetonursolmaz.org/nuxt-hot-reload-isnt-working/)

**Comment by lafllamme** [comment]
This is nothing official. Also the "solution" described written down there is not applicable for us and our project.

**Comment by krmao** [comment]
hot reload got error on component in clientonly and component changed

<img width="1378" alt="image" src="https://github.com/nuxt/nuxt/assets/7344437/9d056f57-e9cb-43a1-aa26-35b50a05acbc">

**Comment by manniL** [comment]
@lafllamme This issue was closed a year ago. Please consider opening a [new issue](https://github.com/nuxt/nuxt/issues/new/choose) instead of leaving a comment here.

**Comment by Ca-tt** [comment]
@Quineone thanks, it works well for me!

**Comment by mhdSid** [comment]
Once nuxt folders are spread in a monorepo and layouts are added using nuxt/kit, then the hot-module replacement breaks. I'll try to raise a new issue about it

**Comment by Ca-tt** [comment]
@mhdSid good decision 👍

**Comment by amouratoglou** [comment]
hi, why is this issue closed?  someone ?
