### ISSUE TITLE
PUT, PATCH, and DELETE requests

### ISSUE THREAD

**Issue by howbizarre** [nuxt/nuxt#19077]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `tailwindcss`, `nitro`, `app`, `typescript`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.4.0`, `nuxt-icon@0.2.11`
- Build Modules:    `-`
------------------------------

### Reproduction

I have a variable defined like `const method = someBooleanCheck ? "PATCH": "PUT";`

I use it as `await useFetch("/api/fileName", { method: method, body: { some: data} });`

[https://stackblitz.com/edit/nuxt-patch-gjclzp](https://stackblitz.com/edit/nuxt-patch-gjclzp)

### Describe the bug

This causes a TS compiler error `Type '"PATCH" | "PUT"' is not assignable to type '"get" | "GET" | "POST" | "post" | Ref<"get" | "GET" | "POST" | "post" | undefined> | undefined'.`

### Additional context

I raised a discussions #19065 because I use the request keyword in the file name - `/server/api/fileName.patch.ts`.

Everything works as expected when I silence the compiler error with `// @ts-ignore`, but this is in the development.
I don't know if I should submit it to production like this or refactor the call to POST with some additional checks.

FYI
The project lives in a Firebase environment.

**Comment by AloisSeckar** [comment]
I think I run into similar problem recently, although with different HTTP method. I started getting TS check error upon:

`await useFetch<SearchZadostiResponse>(cmUrl + '/zadosti/search', { method: 'POST', body: getZadostRequest })`

TS complains about `method` saying that:

```
Type '"POST"' is not assignable to type '"get" | "GET" | Ref<"get" | "GET">'.ts(2322)
index.d.ts(61, 5): The expected type comes from property 'method' which is declared here on type 'UseFetchOptions<{ uuids?: string[]; }, (res: { uuids?: string[]; }) => { uuids?: string[]; }, KeyOfRes<(res: { uuids?: string[]; }) => { uuids?: string[]; }>, NitroFetchRequest, "get">'
```

It used to work with no problem for months. Also technically it still works good and it is fetching the data as intended. Unfortunatelly I haven`t noticed the exact moment when this start happening, I just know it is bothering me for a few days now, so I cannot confirm whether it started happening after updating to 3.2.0 or it was already present in previus version, or there is some other external factor.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by AloisSeckar** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

I am not sure how to do it in this case, since the error is only shown in my VS Code. The actual code works as intended. 
![image](https://user-images.githubusercontent.com/7399922/219359501-590833f9-2eed-472f-b722-8a4bec1fa246.png)

**Comment by manniL** [comment]
Stackblitz/CodeSandbox is fine 😋

**Comment by AloisSeckar** [comment]
> Stackblitz/CodeSandbox is fine 😋

Well, I created a repo: https://stackblitz.com/edit/github-nyu5ko

Code works, but when I make `/components/UseFetchWithPost.vue` in my VS Code, I am getting the error.

I have noticed tho, that for me it occures, when `useFetch<Foo>` is type inferred, plain `useFetch` yields no such error.

**Comment by howbizarre** [comment]
👍  [https://stackblitz.com/edit/nuxt-patch-gjclzp](https://stackblitz.com/edit/nuxt-patch-gjclzp)

**Comment by Gypsophyllite** [comment]
> > Stackblitz/CodeSandbox is fine 😋
> 
> Well, I created a repo: https://stackblitz.com/edit/github-nyu5ko
> 
> Code works, but when I make `/components/UseFetchWithPost.vue` in my VS Code, I am getting the error.
> 
> I have noticed tho, that for me it occures, when `useFetch<Foo>` is type inferred, plain `useFetch` yields no such error.

```typescript
const { data } = await useFetch<SomeDataType, Error, string, 'post' | 'get'>(
    '/api/****',
    {
        method: 'post',
        params: {},
    }
)
```
well, I also wondering why, but if you want to explicitly set return data type, you can use this as a workaround.

**Comment by lucassimines** [comment]
Same error here.

```
Nuxi 3.2.1-rc.0-27940229.59a1f7b                                                 10:10:57
                                                                                 10:10:58
RootDir: /Users/lucassimines/FMCX/FMCX Dashboard/fmcx-one                        10:10:58
Nuxt project info: (copied to clipboard)                                         10:10:58

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.1-rc.0-27940229.59a1f7b`
- Nitro Version:    `2.2.1-27932137.b4d9ecc`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

**Comment by januarfonti** [comment]
I got the same issue 👀

**Comment by ReaganM02** [comment]
Experiencing the same issue.

**Comment by AloisSeckar** [comment]
I simply can't have type inferred useFetch when not using GET method:

This is not ok for TS:
![image](https://user-images.githubusercontent.com/7399922/222653903-fbf4865f-8986-4cc3-9139-ba83a5f65ff9.png)

When I give up typing useFetch and extra type the response, then it works:
![image](https://user-images.githubusercontent.com/7399922/222653840-9db92bf2-0bc6-458e-8711-d46f7125eba9.png)

**Comment by AlejandroMut** [comment]
I'm having a similar problem. Since version 3.2.0. My editor complains about having a POST method.

![Screenshot 2023-03-10 182021](https://user-images.githubusercontent.com/39420673/224430853-e41a8dd6-af6a-4dda-8041-729a47d65cde.png)

**Comment by agenordebriat** [comment]
I'm getting the same king of issue:
```
Type '"POST"' is not assignable to type '"get" | "put" | "GET" | "PUT" | Ref<"get" | "put" | "GET" | "PUT" | undefined> | undefined'.
```
I'm trying to use the `send-envelope` route, but it's thinking it's one of the two on the bottom, see:
<img width="271" alt="Screenshot 2023-03-17 at 09 31 49" src="https://user-images.githubusercontent.com/20444343/225853806-18d7652b-eab1-4ca4-a879-4a5bfcc04e8c.png">
If I remove them it's OK. Is it something on my end, should I organize my routes differently?

**Comment by provok-it** [comment]
<img width="1017" alt="Capture d’écran 2023-04-06 à 18 18 22" src="https://user-images.githubusercontent.com/37068300/230438357-18f2274a-5976-4412-bb02-31812e2b9e50.png">
<img width="621" alt="Capture d’écran 2023-04-06 à 18 18 31" src="https://user-images.githubusercontent.com/37068300/230438370-7ebe38c7-4a64-4192-adb6-20d8acee5213.png">

Same shit, and it is not OK.

This issue was opened in February. Are you planning on resolving this issue soon?
We can't get data with POST methods, which appeared in HTTP/1.1.
Not resolving this is like traveling almost 30 years back in time.

Please make Nuxt 3 stable first, then push new cool features... some people are relying on you to make a living 🙏

**Comment by ReaganM02** [comment]
> <img alt="Capture d’écran 2023-04-06 à 18 18 22" width="1017" src="https://user-images.githubusercontent.com/37068300/230438357-18f2274a-5976-4412-bb02-31812e2b9e50.png">
> 
> <img alt="Capture d’écran 2023-04-06 à 18 18 31" width="621" src="https://user-images.githubusercontent.com/37068300/230438370-7ebe38c7-4a64-4192-adb6-20d8acee5213.png">
> 
> Same shit, and it is not OK.
> 
> This issue was opened in February. Are you planning on resolving this issue soon? We can't get data with POST methods, which appeared in HTTP/1.1. Not resolving this is like traveling almost 30 years back in time.
> 
> Please make Nuxt 3 stable first, then push new cool features... some people are relying on you to make a living 🙏

Correct me if I am wrong but I think your issue is not related to the  `method` type? Also, have you tried this workaround? https://github.com/nuxt/nuxt/issues/19077#issuecomment-1434008688

**Comment by tobychidi** [comment]
I have also noticed in my codebase where ` {method: "POST"} ` and ` {method: "post"} ` return different types for data in `useFetch` with the former being a union of the types returned from the server from `handle.get.ts, handle.post.ts` and others.

I am using Nuxt 3.4.2 on Windows 11

**Comment by tobychidi** [comment]
I have also noticed in my codebase where ` {method: "POST"} ` an ` {method: "post"} ` return different types for data in `useFetch` with the former being a union of the types returned from the server from handle.get.ts and others

**Comment by AloisSeckar** [comment]
Workaround to hide the type error: https://github.com/nuxt/nuxt/issues/19077#issuecomment-1453107499

Permanent fix: I think we'll have to wait 'till the cause is uncovered and fixed in Nuxt codebase.

**Comment by danielroe** [comment]
Are you still experiencing this with the latest edge version? (With the latest Nitro?)

This is what I get when I clone the linked repo above and update:

<img width="717" alt="CleanShot 2023-05-12 at 18 14 00@2x" src="https://github.com/nuxt/nuxt/assets/28706372/5a0237c2-ca29-439d-904e-5edbc30323a5">

**Comment by Lukiticas** [comment]
I'm facing the same issue, any workaround?
![image](https://github.com/nuxt/nuxt/assets/86432484/0c2c1f47-7462-42de-bf2d-2765ea285494)

**Comment by jiangmaniu** [comment]
Same question. Want to know how it's going?

**Comment by karis** [comment]
mee too.

"nuxt": "^3.4.3",

**Comment by davide-granello** [comment]
Might not be of use in some cases, but when we need to make api PUT, POST, DELETE requests, we use $fetch instead.
$fetch has working type inferring, so we can type the returned data from the response.
Example:
```ts
const data = await $fetch<ReturnedType>(`${$config.public.apiBaseUrl}/your-api-route`, {
  method: 'POST',
  body: dataToSend
})
// data is of type ReturnedType
```

**Comment by ghislaingirardeau** [comment]
I got the same issue with "nuxt": "^3.4.2".

Succeed to solved it passing object options inside useFetch, but can't explain why :

`const body = {...}
const options = {
method: "POST",
headers: {...},
body: JSON.stringify(body),
};
const { data, error } = await useFetch<APIBody>(
url, options as object
);
console.log(data.value?.results) // work here

interface APIBody {[key: string]: any}
//Or
interface APIBody {results: {...};}`

**Comment by camille500** [comment]
Same issue here with Nuxt `v3.6.2`
<img width="985" alt="image" src="https://github.com/nuxt/nuxt/assets/8942820/da578996-2b81-410e-8cc4-856ff86c6280">

**Comment by danielroe** [comment]
If you are experiencing an issue, please raise a new issue with a reproduction 🙏

**Comment by devseckobz** [comment]
To fix this issue on vscode, you need to specify a request method on your nitro route file

On your request 
`const result: any = await $fetch('/api/user/info', {
    method: 'post'
  })
`
On your nitro route file
`/api/user/info.post.ts`

**Comment by shvchuk** [comment]
> I got the same issue with "nuxt": "^3.4.2".
> 
> Succeed to solved it passing object options inside useFetch, but can't explain why :
> 
> `const body = {...}`
> 
> ```
> const options = {
> method: "POST",
> headers: {...},
> body: JSON.stringify(body),
> };
> ```
> 
> ```
> const { data, error } = await useFetch<APIBody>(
> url, options as object
> );
> console.log(data.value?.results) // work here
> ```
> 
> ```
> interface APIBody {[key: string]: any}
> //Or
> interface APIBody {results: {...};}
> ```

Had exactly the same issue but with method="DELETE", solved with this one by passing options object into in my case `$fetch`

**Comment by alanvillalobos** [comment]
Still seeing this issue:

![Image](https://github.com/user-attachments/assets/d9507bfb-de96-4e27-9f4d-30cd145b5cba)

**Comment by danielroe** [comment]
@alanvillalobos Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/nitrojs/nitro/tree/v2/examples/hello-world)), and if so, raise [there](https://github.com/nitrojs/nitro/issues/new/choose)? 🙏 

if not, could you open a new issue with a reproduction?

**Comment by pi0** [comment]
(added to https://github.com/nuxt/nuxt/issues/19077 tracker, although sharing a repro even here might be helpful for future investigations)

**Comment by Thomas-Philippot** [comment]
Same issue on PUT method

![Image](https://github.com/user-attachments/assets/d4421740-97a9-45d7-aac4-f67f7436cbe4)

Is this happening because I have two method files on that route ?

![Image](https://github.com/user-attachments/assets/8088164e-9efd-46bb-946d-a66d5180ba35)

**Comment by feloot** [comment]
FYI until the issue is fixed, casting the method to `any` will hide the type error and work fine.

```
await $fetch('/api/document', {
    method: 'DELETE' as any
})
```

**Comment by Wetzel402** [comment]
I am seeing this issue in some of my tests with Nuxt 4. Casting as any does work to resolve the errors but isn't ideal.
