### ISSUE TITLE
"Hydration text mismatch" when using `useFetch` and `computed`

### ISSUE THREAD

**Issue by septatrix** [nuxt/nuxt#19622]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/ui@0.3.3`
- Build Modules:    `-`

(Running on codesandbox.io)

### Reproduction

https://codesandbox.io/p/sandbox/optimistic-nash-2qbr3n?file=%2Fapp.vue

### Describe the bug

Using a computed value in the template which accesses data from a `useFetch` (without top-level await) leads to a hydration mismatch error.

### Additional context

It seems like this only happens if the computed value is also accessed somewhere else in the `<script setup>` tag. Otherwise this does not seem to happen. Commenting out the dummy variable access in the above MWE therefore somehow prevents the hydration error.

### Logs

```shell-script
[Vue warn]: Hydration text mismatch:
...
Hydration completed but contains mismatches.
```
```

**Comment by danielroe** [comment]
This is a tricky one, and has to do with Vue SSR reactivity - namely, that it does not exist. Computeds are _fixed_ at the time they are first accessed. So the issue is that your computed (called before the fetch is resolved) is _fixed_ at an empty object and never updates when the fetch completes.

**Comment by septatrix** [comment]
Okay that makes sense, do you know if Vue indents to improve this behaviour in the future?

Is there any way to influence the order in which the code is resolved? I would have expected `useFetch` to resolve directly (as it is an internal call to the API route) and `computed` to be calculated afterwards as it is below in the code. Might this be due to the API route being async?

**Comment by danielroe** [comment]
Yes, it is because the route is async. I would recommend you await the useFetch call in your case

**Comment by ryansegus** [comment]
Hi, I have a similar issue, from his example I tried the suggested await but I still get the "Hydration text mismatch", @danielroe can you provide an example?

For now I am using ClientOnly to solve the issue, How are we supposed to handle computed props? using ClientOnly doesn't seem logical to me, it defeats the SSR purpose as I see it, maybe I am wrong and I am missing something.

`const { data } = await useFetch(`/api/hello/${count.value}`, {
  params: { token: 124 },
});`

**Comment by ryansegus** [comment]
> Same issue here. Awaiting useFetch before even rendering the component that consumes the computed prop and still getting hydration mismatches.

I found out that in most cases I can use ref instead, but for reactive props this won't work, let's say you have some filters that are trigger by some user action, on this scenario the computed will fit better but you will still get the hydration mismatch.

```
  const fullName = ref('')

  const { fetch } = useFetch(async () => {
      // call API here
      const user: IUser = await yourApi.get('user', { id: 'XX' })

      if (user) {
        // The problem with this is if your expect your data to be reactive you will need to trigger the fetch on a watcher maybe
        fullName.value = `${user.firstName} ${user.lastName}`
      }
    })
    ```

**Comment by Shubham-Sinn** [comment]
i did this

```
const {data} = await useFetch('url',
  {
    server: false,
  }
);
```

which forced the useFetch to work on client side not on the server, and this solved the hydration mismatch... but this this makes the content csr not ssr, ie no indexing... better solution anyone??
