### ISSUE TITLE
Hello, help me see what's going on here? How to solve it

### ISSUE THREAD

**Issue by zhizaiyunxiao** [nuxt/nuxt#19756]
### Environment

![image](https://user-images.githubusercontent.com/22257246/225799566-0a3c408c-1bc4-445c-9a7a-1481e82cfff6.png)

### Reproduction

 ERROR  Cannot read property 'name' of undefined 

### Describe the bug

 ERROR  Cannot read property 'name' of undefined

**Comment by MidTin** [comment]
me too, the same problem met after upgrade nuxt to 3.3.1

**Comment by videmann** [comment]
I got another message

> postinstall
> nuxt prepare

Nuxi 3.3.1                                                                                                                                                              08:55:55

 ERROR  Nuxt module should be a function: [object Object]                                                                                                               08:55:59  

  at normalizeModule (/C:/Users/videmanso/projects/lrp-front/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:478:11)
  at installModule (/C:/Users/videmanso/projects/lrp-front/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:450:47)
  at initNuxt (/C:/Users/videmanso/projects/lrp-front/node_modules/nuxt/dist/index.mjs:2469:13)
  at async loadNuxt (/C:/Users/videmanso/projects/lrp-front/node_modules/@nuxt/kit/dist/index.mjs:522:19)
  at async Object.invoke (/C:/Users/videmanso/projects/lrp-front/node_modules/nuxi/dist/chunks/prepare.mjs:37:18)
  at async _main (/C:/Users/videmanso/projects/lrp-front/node_modules/nuxi/dist/cli.mjs:49:20)

**Comment by danielroe** [comment]
I believe this is likely an issue triggered by the new Nuxt v3.3 feature to auto-scan your `~/modules` folder. Perhaps there's a file in there that doesn't have a default export of a Nuxt module.

(You can change this directory with `dir.modules` option in your `nuxt.config` file.)

**Comment by manniL** [comment]
> same propblem on server build

Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) then? 🙏

**Comment by AlisherNarzulloev** [comment]
> Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) then? 🙏

![Uploading 18BB8C47-B99C-4AEB-A726-977BEA52C769.jpeg…]()

**Comment by AlisherNarzulloev** [comment]
> > same propblem on server build
> 
> Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) then? 🙏

![E5745EB4-5D09-49DD-A102-D417841D9968](https://user-images.githubusercontent.com/92950485/225933096-d373bd3d-8e51-448e-ac68-d801a967200a.jpeg)

**Comment by manniL** [comment]
This is not a reproduction ☺️

> > > same propblem on server build
> > 
> > 
> > Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) then? 🙏
> 
> ![E5745EB4-5D09-49DD-A102-D417841D9968](https://user-images.githubusercontent.com/92950485/225933096-d373bd3d-8e51-448e-ac68-d801a967200a.jpeg)

**Comment by bpeab** [comment]
It seems you've already resolved the issue  81da4cf5a23ad54812d62a77091aa76f2db28d87 though. It should be resolved with a release.

**Comment by danielroe** [comment]
Good spot - sorry, issue blindness 😆

**Comment by DMaxter** [comment]
I still have a similar issue using Node v20 on the edge channel.

I am putting `protoc` generated files in the `modules` directory and when I install `google-protobuf` I have this error when installing it and when trying to run
