### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client when trying to setup redirects + handle 404

### ISSUE THREAD

**Issue by m0zz094** [nuxt/nuxt#20038]
### Environment

Nuxt project info:                                                                                                                                                                     20:41:21

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.5.4`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@storyblok/nuxt@5.3.4`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/m0zz094/storyblok-redirects-404

### Describe the bug

I created a [minimal repo](https://github.com/m0zz094/storyblok-redirects-404) here to show what's happening.

I created a global middleware to handle 301 redirects that should work like that:

- When someone visits any url mapped inside **redirects/redirects.js**, they should 301 redirects to the "dst" url
- When someone visits any url that ends with a trailing slash (exept the homepage) they should redirect to the same url without the trailing slash (example: **/products/** redirects to **/products**)

If you visit **/example** you'll be redirected correctly to **/example/redirect**
If you try to visit any random url that ends with a trailing slash (example: **/asgasg/asgasg/**) you'll get an error like that:

`[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client                                                                   20:15:52
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at setResponseHeader (file:///C:/Users/fmozz/Desktop/WEB/storyblok-redirects-404/node_modules/h3/dist/index.mjs:670:18)
    at Object.errorhandler [as onError] (file:///C:/Users/fmozz/Desktop/WEB/storyblok-redirects-404/.nuxt/dev/index.mjs:484:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server.toNodeHandle (file:///C:/Users/fmozz/Desktop/WEB/storyblok-redirects-404/node_modules/h3/dist/index.mjs:1329:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}`

In production (deployed to vercel) this throw a 500 error page.
It's been weeks without understanding what could be the problem here.

Any Idea?

**Comment by fyyyyy** [comment]
I get this with the sidebase.io default setup

[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)

**Comment by fyyyyy** [comment]
It does not seem to happen when using a button with navigateTo instead of using a.href tags. See
https://github.com/sidebase/nuxt-auth/issues/311

**Comment by m0zz094** [comment]
For anyone struggling with this, I replaced nuxt middleware that handles trailing slash + redirects with vercel.json

`
{
  "trailingSlash": false,
  "redirects": [
    {
      "source": "/example",
      "destination": "/example/redirect",
      "statusCode: 301
  ]
}
`

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/19557.

**Comment by danielroe** [comment]
This should be resolved in v3.4.1.

**Comment by fyyyyy** [comment]
I can confirm it still happens with 3.4.1 and nuxt-auth redirects

<img width="660" alt="image" src="https://user-images.githubusercontent.com/3744048/232879306-0f06ac52-9279-4b46-81cd-5dee8f3d2d1c.png">

**Comment by danielroe** [comment]
I would raise an issue with nuxt-auth, in that case.

**Comment by kecoliva** [comment]
Still happens to 3.7.1

**Comment by danielroe** [comment]
@kecoliva If this is happening for you, it's probably not a Nuxt bug. But feel free to open an issue with a reproduction and I'll take a look.
