### ISSUE TITLE
`typeCheck` config not working with typescript 5

### ISSUE THREAD

**Issue by mdanilowicz** [nuxt/nuxt#20060]
### Environment

Nuxi 3.3.3
Nuxt 3.3.3 with Nitro 2.3.2

https://stackblitz.com/edit/github-q2j3cy

### Reproduction

Create a new project with those dev dependencies.

```
    "@types/node": "^18.11.18",
    "typescript": "^5.0.0",
    "vue-tsc": "^1.3.00"
```
Set config
```
export default defineNuxtConfig({
  typescript: {
    typeCheck: true,
  },
});
```
Run app
`yarn install && yarn dev`

### Describe the bug

Error in console 
```[uncaughtException] This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Search string not found: "ts.executeCommandLine(ts.sys, ts.noop, ts.sys.args);"".```

### Additional context

The error appears only with TS v5 everything works with v4.9

**Comment by danielroe** [comment]
This is likely to be an upstream issue in `vite-plugin-checker`, which Nuxt uses under the hood.

**Comment by nam0107** [comment]
I have the same problem 🤔

**Comment by danielroe** [comment]
This is now resolved in the latest version of `vite-plugin-checker`, which you can pull in by `npm upgrade vite-plugin-checker`.

**Comment by mdanilowicz** [comment]
@danielroe Unfortunately the problem still exists even if you use the newest Nuxt and vue-tsc version.

Reproduction link https://stackblitz.com/edit/github-q2j3cy?file=package.json

I tested it by manually overriding the package and from the vite-plugin-checker@0.6.0 version everything looks ok. But I think that issue should be open until it starts working with Nuxt without any "hacks"

**Comment by danielroe** [comment]
It has been upgraded in the Nuxt deps so it should be already resolved on the Edge Channel, and present in the next release.

**Comment by mdanilowicz** [comment]
Perfect, thank you!
