### ISSUE TITLE
useNuxtApp() helper returns type unknown

### ISSUE THREAD

**Issue by atlansien** [nuxt/nuxt#20390]
### Environment

- Operating System: Darwin
- Node Version:     v18.0.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
- IDE: VSCode 1.77.3
  - volar 1.2.0

### Reproduction

https://stackblitz.com/edit/github-baumax?file=app.vue

### Describe the bug

I registered a helper from the plugin with reference to [document](https://nuxt.com/docs/guide/directory-structure/plugins#automatically-providing-helpers)

plugins/helllo.ts
```js
export default defineNuxtPlugin(() => {
  const hoge = (message: string) => `hello ${message}`;

  return {
    provide: {
      hoge
    }
  }
})
```
Later, when I used it in PAGE, the type was `unknown`.

app.vue
```js
<script setup lang="ts">
  const { $hoge } = useNuxtApp();
</script>

<template>
  <div>
    <h1>
      {{ $hoge('msg') }}
    </h1>
  </div>
</template>
```
message
```
'__VLS_ctx.$hoge'' is of type 'unknown' ts(18046)
```

In practice, however, the helper works.
Helper is the same for non-functions
Is there a required setting here?
Or is it a volar problem?

**Comment by atlansien** [comment]
@danielroe 

Thanks for the quick reply.
I tried it on another PC and the same thing happened(create`npx nuxi init <project name>`)

> This seems to be working fine for me.

In this case, type: any.
<img width="892" alt="スクリーンショット 2023-04-19 23 50 17" src="https://user-images.githubusercontent.com/46712701/233114846-a36735ee-c80f-4ad0-a4c9-fb22425e5c70.png">


The code is similar to stackblitz, but are there any other settings needed?

**Comment by danielroe** [comment]
Did you run `nuxi prepare`?

**Comment by atlansien** [comment]
I can't fix it...

VSCode extensions are
- Vue Language Features (Volar) v1.2.0
- TypeScript Vue Plugin (Volar) v1.2.0
Is this correct?

**Comment by atlansien** [comment]
Type is now hit when vetur is enabled.
But since nuxt 3.4.1, I don't think this is appropriate.
![スクリーンショット 2023-04-20 12 38 55](https://user-images.githubusercontent.com/46712701/233252318-dcd18384-0010-43e9-9dd6-09ec5f77d948.png)

**Comment by atlansien** [comment]
- Uninstall vetur
- Disable all extensions
- Reboot and activate all

This procedure worked correctly.
I had disabled it, but vetur may have been behaving in some way!
Sorry for the trouble.

**Comment by frisch-raphael** [comment]
Got the same problem and uninstalling vetur also worked. Thanks for posting your solution here @atlansien

**Comment by atlansien** [comment]
@danielroe 

We have found that installing JavaScript and TypeScript Nightly (v5.1.20230430) as an extension causes a problem.

**Comment by inoue2002** [comment]
>We have found that installing JavaScript and TypeScript Nightly (v5.1.20230430) as an extension causes a problem.
I had the same problem. Thanks for solving it by removing the extension here. @atlansien

**Comment by atlansien** [comment]
@inoue2002 
お役に立ててよかったです！😄

**Comment by SonByungjin** [comment]
The problem occurs even without `vetur` and `JavaScript and TypeScript Nightly`
Has anyone solved the problem in any other way?

**Comment by yasu-s** [comment]
I had the same problem with VSCode 1.79.

**Comment by json-jh** [comment]
https://nuxt.com/docs/guide/directory-structure/plugins#advanced

The above link solved the problem.

**Comment by yasu-s** [comment]
@json-jh 
Thanks. The link resolved the problem.

**Comment by SonByungjin** [comment]
@json-jh 
It helped me too thank you!

**Comment by ammiiir1** [comment]
this error occured after VsCode 1.79 update.
the issue is related to VsCode TypeScript version
after 1.79 version typescript version is updated and "Volar" is using the new typesript version.
to solve the issue press `ctr + shift + p` then write "Select TypeScript Version" and then choose "Use workspace version".
![image](https://github.com/nuxt/nuxt/assets/46372422/148a2439-96c3-4208-a319-5ba2438bfc6e)

**Comment by alex-eliot** [comment]
I digged into this and found the issue. For me it wasn't Nuxt, but a library that exposed a nuxt plugin without type shims. After running the nuxt dev server once, go to your `.nuxt/types/plugins.d.ts` directory, and within the `NuxtAppInjections` type, you'll find a bunch of imports. Find which one of them doesn't have a type shim (some `<name>.d.ts` file). Once you find it, you can quickly fix this by going to that file directory, and create a new `<name>.d.ts` file (`<name>` being the name of the file), with the following code:

```typescript
import { Plugin } from "nuxt/app"
// If your plugin injects stuff, use those instead of unknown
declare const plugin: Plugin<unknown>
export default plugin
```

Restart Vue (TS) server and you'll have your types again.

**Comment by ThimoDEV** [comment]
Just encountered the same issue using the sidebase cli for tRPC.

nuxi prepare didn't help, I don't have vetur installed, the type is too complex for an index.d.ts, my workspace typescript is already above 5.0, VSCode is at 1.80

**Comment by voxivoid** [comment]
I'm still facing the same issue and none of the solutions above seemed to solve the issue. This is happening with nuxt@3.6.5, Vue Language Features (Volar)@1.8.8, TypeScript Vue Plugin (Volar)@1.8.8, VSCode@1.80.2, TypeScript@5.1.6.

**Comment by danielroe** [comment]
What isn't typed? If it is something from a module, report it there; it's likely something they need to fix.

**Comment by Ghustavh97** [comment]
Same here. None of the plugins are returning their types both inside the `template` or `script` tag, even if I manually add them into the index.d.ts file.

![2](https://github.com/nuxt/nuxt/assets/20132952/6a5dc927-6122-4cc7-9cbe-c40622b8dac9)

![1](https://github.com/nuxt/nuxt/assets/20132952/b7ed6820-dd7e-420a-bfb4-af8d7e430b3d)

nuxt@3.6.4
Vue Language Features (Volar)@1.8.8
TypeScript Vue Plugin (Volar)@1.8.8
VSCode@1.80.2
TypeScript@5.1.6
vue-tsc@1.8.8

**Comment by Quatton** [comment]
Same here. Both module augmentation and uninstalling extensions did not work. The plugin gets registered and works as expected so I'm assuming this is on VSCode  & TypeScript server end.

**Comment by Ghustavh97** [comment]
Changing `#app` to `nuxt/dist/app` and `vue` to `@vue/runtime-core`  in the index.d.ts file for the project will fix the issue. idk why but I will take it.

**Comment by jkneepkens** [comment]
Same problem here, since we upgraded to Nuxt 3.6.5 and TypeScript 5.1.6 we have this problem as well with an `unknown` type for the variables we get out of the `useNuxtApp` function. 
Disabling some VSCode extensions like Volar, Nuxtr and builtin TypeScript didn't work, any ideas what it can be?

**Comment by voxivoid** [comment]
I found out I had this issue because I manually added `compilerOptions.paths` to my project `tsconfig.json`. This seems to have overridden auto-generated configuration from `./.nuxt/tsconfig.json`. I was able to solve this by adding the wanted configuration through setting `typescript.tsConfig.compilerOptions.paths` on the `nuxt.config.ts` file.

**Comment by Quatton** [comment]
Update: I tried opening the same workspace in WSL and it worked just fine. I am investigating what is causing this.

**Comment by redcodemohammed** [comment]
@voxivoid In my case that was the issue, I did exactly what you did and now it's wotking.

**Comment by zhengdelin** [comment]
I delete this line then it works fine.
This line makes type "NuxtAppInjections" become "any", so all of my plugin injections type are missing.
Every time I start my project I need to delete this line again. I don't know what's wrong with this.

![image](https://github.com/nuxt/nuxt/assets/96772226/9fdfcc30-516b-4b15-8cca-a40f78a645a2)

- nuxt@3.4.3
- Vue Language Features (Volar)@1.8.8
- TypeScript Vue Plugin (Volar)@1.8.8
- VSCode@1.81
- TypeScript@5.1.6

**Comment by danielroe** [comment]
Try updating to the latest version of Nuxt, where this issue was fixed.

**Comment by hansfuchs** [comment]
> Changing `#app` to `nuxt/dist/app` and `vue` to `@vue/runtime-core` in the index.d.ts file for the project will fix the issue. idk why but I will take it.

The problem is still occuring for me on the latest version of nuxt@3.7.3, even without Vetur involved. The above is the only thing that worked for me.

**Comment by taako-502** [comment]
I was able to get it to work by commenting out the "baseUrl": "." setting in tsconfig.json.

**Comment by FlorianWerndl** [comment]
For me removing `baseURL` and `paths` from `compilerOptions` worked.

**Comment by huypn** [comment]
> For me removing `baseURL` and `paths` from `compilerOptions` worked.

It worked for me too, thank you so much!

**Comment by togami2864** [comment]
We're currently migrating from Nuxt 2 to Nuxt 3 and we ran into a snag. We found that commenting out all the tsconfig options, except for "extends," worked for us.
```tsconfig.json
{
  "extends": "./.nuxt/tsconfig.json"
  // just commented out the other options temporarily
}
```

> For me removing baseURL and paths from compilerOptions worked.

Our configuration also includes `baseURL` and `paths`.

**Comment by skmd87** [comment]
Im creating a module that have a plugin. when I run `nuxt-module-build build --stub` it works fine. but for production when I make `nuxt-module-build build` I get '__VLS_ctx.$vv' is of type 'unknown'.

here is my plugin:

` 
  declare module "#app" {
	  interface NuxtApp {
		  $vv: Validator;
	  }
  }
  
  export default defineNuxtPlugin((nuxtApp) => {
	  const config = useRuntimeConfig();
	  return {
		  provide: {
			  'vv': (label?: string): Validator => {
				  const validator: Validator = new Validator(nuxtApp as NuxtApp, config.public.vuetifyValidation as ModuleOptions);
				  if (label)
					  validator.label(label);
				  return validator
			  }
		  },
	  };
  });`



Any idea??

**Comment by yk-sgr** [comment]
Wow, had the same problem.
For me it was @vueuse/motion

**Comment by VinnyLioni** [comment]
to anyone that still having the same problem, with this i can solve it at least momentarily

  const { $user } = useNuxtApp()
  
  interface User {
    displayName: string;
    email: string;
    photoURL: string;
    uid: string;
    metadata: {
      creationTime: string;
      lastSignInTime: string;
    };
  }
  
  const userData: User | any = $user
  
  i didnt think that is the best way to do this, but is what i can do for now with my actual skills

**Comment by justinechang39** [comment]
uninstalling Vetur worked for me

**Comment by artoryas** [comment]
Any updates on this topic? Still have this issue.
IDE: Phpstorm without vetur
nuxt@3.9.0

**Comment by artoryas** [comment]
UPDATE: it is discovered that there is a bug in Phpstorm / WebStorm IDEs. Try opening your project in another editor (for example VsCode), and typing should be there. For more about the bug itself:
https://youtrack.jetbrains.com/issue/WEB-59818/Vue-custom-global-properties-added-by-augmenting-vue-are-not-resolved

**Comment by omnichronous** [comment]
I'm also still seeing this problem with VSCode 1.90.1 and Nuxt 3.9.3. The only way helper types work for me is if I provide them as described [here](https://nuxt.com/docs/guide/directory-structure/plugins#typing-plugins). Has anyone figured out the reason for this? 🙏

**Comment by ghyath5** [comment]
any updates?
still the same issue 

I don't have Vuter and I tried to restart vscode still same problem

`unknown` type

**Comment by Vahagn-Zaqaryan** [comment]
Same here

<img width="431" alt="image" src="https://github.com/user-attachments/assets/a23467f5-2a8e-4a21-8331-375cc47ae23e">

**Comment by Vahagn-Zaqaryan** [comment]
Hi everyone, I encountered the same issue in my project. After isolating the problem, I discovered that versions `>v1.3.4` of the `nuxt-delay-hydration` package cause errors with the generated Nuxt types. Downgrading to version `1.3.3` resolved the issue.

Steps I took:

- Created a new application — no issues.
- Deleted files and packages one by one.
- Identified `nuxt-delay-hydration` as the culprit.
- Downgraded to `1.3.3` — issue fixed.
- Recreated the problem by installing only `nuxt-delay-hydration` in a new app.
- Here are the screenshots of the issue and the fix:

## Issue:
<img width="260" alt="image" src="https://github.com/user-attachments/assets/49c84a33-2656-44a3-b92e-4eb620b8abd1"><br/>

<img width="435" alt="image" src="https://github.com/user-attachments/assets/0f67e0e7-aebb-47b7-bc20-3c5857af4927">



## Fix:
<img width="268" alt="image" src="https://github.com/user-attachments/assets/d7cd857e-93c2-4e10-b99c-9e7abab78625"><br/>

<img width="935" alt="image" src="https://github.com/user-attachments/assets/4a32cedf-0be1-4f69-b638-d867fa14a594">

**Comment by hendrixthecoder** [comment]
In my case removing paths key from my tsconfig.json fixed the issue, the types were returning correctly.

**Comment by jd1378** [comment]
alex-eliot is right, and the problem started happening for me after update to nuxt 3.13.0

the offending lines in my `.nuxt\types\plugins.d.ts` file was these two lines:
```
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.3.14_bufferutil@4.0.8_rollup@4.21.0_utf-8-validate@5.0.10_vite@5.4.2_@types+node@22.5.0_terser@5.31.6_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.mjs").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.3.14_bufferutil@4.0.8_rollup@4.21.0_utf-8-validate@5.0.10_vite@5.4.2_@types+node@22.5.0_terser@5.31.6_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.mjs").default> &
```

by removing these two from the file, I get the correct types again.

**Comment by ThibaultVlacich** [comment]
> Update 2: setting devtools.enabled in nuxt settings to false fixes the issue for now.

This also fixed the issue for me, but only for `useNuxtApp()`. I also have the issue on `useRuntimeConfig()` where types are unknown.

Issue appeared when I tried upgrading from Nuxt 3.11.2 to 3.13.0

**Comment by jankohlbach** [comment]
for me it's changing from typescript 5.4.5 to 5.5.4 what causes this issue
it's damn annoying

**Comment by CMeyer19** [comment]
I am also getting this as a result of upgrading to 3.13, but for me the problematic library is primevue. My issues go away when commenting out the line containing '..@primevue/nuxt-module/dist/runtime/plugin.client.mjs").default..' line in the plugin.d.ts file

**Comment by lud-hu** [comment]
As per @danielroe this will be fixed in the upcoming 3.13.1 release of nuxt, but I unfortunately don't know when it will be released.
see https://github.com/nuxt/nuxt/issues/28779#issuecomment-2324197452

**Comment by jankohlbach** [comment]
I still have that for 3.13.1 ...
also, I don't have that issue with any plugin, I even have that issue with my own super simple plugin that I have in the plugins folder
with typescript 5.4.5 it works, 5.5.4 doesn't work anymore ...

**Comment by katerlouis** [comment]
Freshly upgraded to nuxt 3.17.2 with `$ npx nuxi upgrade`. I'm using VSCode 1.99 on macOS, npm 10.9.2, node 22.13.0
I do not have Vetur extension installed and do not have typescript installed in my package.json,

still I get the issue that all my provided plugins are `unknown` after "importing" them with `const { $hello } = useNuxtApp()`

Surprised to see this not solved after years 🤷

**Comment by danielroe** [comment]
@katerlouis  i believe this is resolved. if you can provide a reproduction i'll take a look at your code/dependencies

**Comment by zhzgao** [comment]
> * Uninstall vetur
> * Disable all extensions
> * Reboot and activate all
> 
> This procedure worked correctly. I had disabled it, but vetur may have been behaving in some way! I then installed and deactivated vetur again and the same thing did not happen Sorry for the trouble.

Those procedures solved my problem completely, thank you!
It seems that you do not need Vetur plugin when you have installed Nuxtr plugin, otherwise, the issue will exist. And then you can follow @atlansien procedures to fix it.
