### ISSUE TITLE
Nuxt  Module build failed  @babel/plugin-proposal-private-property-in-object

### ISSUE THREAD

**Issue by Eugene313** [nuxt/nuxt#21489]
### Environment

Operating System: Windows or Mac
Node Version: v16.20.0
Nuxt Version: 2.16.3

Package Manager: npm@8.19.4

User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

Use npm init nuxt-app test

cd test

npm install

npm run build

### Describe the bug

ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/.pnpm/babel-loader@8.3.0_@babel+core@7.22.5_webpack@4.46.0/node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\Users\Eugene\Desktop\prozorro.purchase-front\.nuxt\client.js: --- PLACEHOLDER PACKAGE ---
This @babel/plugin-proposal-private-property-in-object version is not meant to
be imported. Something is importing
@babel/plugin-proposal-private-property-in-object without declaring it in its
dependencies (or devDependencies) in the package.json file.
Add "@babel/plugin-proposal-private-property-in-object" to your devDependencies
to work around this error.

**Comment by danielroe** [comment]
fix in progress at https://github.com/nuxt/nuxt/pull/21488

**Comment by danielroe** [comment]
This should be resolved in the edge channel shortly (using `nuxt-edge`), or in the next release (2.17) which we plan for this weekend.

**Comment by danielroe** [comment]
This should be resolved in the latest release. Let me know if not and I'll happily reopen.

**Comment by Eugene313** [comment]
still doesn't working at 2.17.0

ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/.pnpm/babel-loader@8.3.0_@babel+core@7.22.5_webpack@4.46.0/node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\Users\Eugene\Desktop\prozorro.purchase-front\.nuxt\client.js: Cannot find module '@babel/plugin-proposal-private-property-in-object'
Require stack:
- C:\Users\Eugene\Desktop\prozorro.purchase-front\node_modules\.pnpm\@nuxt+babel-preset-app@2.15.8_vue@2.7.14\node_modules\@nuxt\babel-preset-app\src\index.js
- C:\Users\Eugene\Desktop\prozorro.purchase-front\node_modules\.pnpm\@babel+core@7.22.5\node_modules\@babel\core\lib\config\files\module-types.js
- C:\Users\Eugene\Desktop\prozorro.purchase-front\node_modules\.pnpm\@babel+core@7.22.5\node_modules\@babel\core\lib\config\files\configuration.js
- C:\Users\Eugene\Desktop\prozorro.purchase-front\node_modules\.pnpm\@babel+core@7.22.5\node_modules\@babel\core\lib\config\files\index.js
- C:\Users\Eugene\Desktop\prozorro.purchase-front\node_modules\.pnpm\@babel+core@7.22.5\node_modules\@babel\core\lib\index.js
- C:\Users\Eugene\Desktop\prozorro.purchase-front\node_modules\.pnpm\babel-loader@8.3.0_@babel+core@7.22.5_webpack@4.46.0\node_modules\babel-loader\lib\index.js
- C:\Users\Eugene\Desktop\prozorro.purchase-front\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\loadLoader.js

**Comment by danielroe** [comment]
You may need to refresh your lockfile. It works fine on a fresh install as far as I can tell.

**Comment by memlucky71** [comment]
I have the same problem.

Operating System: Ubuntu
Node Version: v14.21.3
Nuxt Version: 2.15.8

```sh
ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/mohammad/workspace/hammerhead/.nuxt/client.js: --- PLACEHOLDER PACKAGE ---
This @babel/plugin-proposal-private-property-in-object version is not meant to
be imported. Something is importing
@babel/plugin-proposal-private-property-in-object without declaring it in its
dependencies (or devDependencies) in the package.json file.
Add "@babel/plugin-proposal-private-property-in-object" to your devDependencies
to work around this error. This will make this message go away.
```

**Comment by alexcroox** [comment]
any way to solve this quickly without a migration to 2.17.0 which isn't a quick fix for our project?

**Comment by marcusaaronb** [comment]
Helpful thank you
