### ISSUE TITLE
BroadcastChannel.postMessage in useCookie has issue with ProxyObject

### ISSUE THREAD

**Issue by tommie** [nuxt/nuxt#21651]
### Environment

Using Nuxt 3 with a forked [composables/cookie.ts from main](https://gist.github.com/tommie/23539b45f55547d54eac3fdcf8d14231).

```
Google Chrome | 113.0.5672.126 (Official Build) (64-bit)
-- | --
OS | Linux
JavaScript | V8 11.3.244.11
```

### Reproduction

https://stackblitz.com/edit/github-hjpstl?file=app.vue

### Describe the bug

Caused by https://github.com/nuxt/nuxt/pull/20970

```
cookie.ts?t=1687256275358:29 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': #<Object> could not be cloned.
    at callback (http://localhost:8080/_nuxt/composables/cookie.ts?t=1687256275358:29:16)
    at watch.deep (http://localhost:8080/_nuxt/composables/cookie.ts?t=1687256275358:48:11)
    at callWithErrorHandling (http://localhost:8080/_nuxt/node_modules/.cache/vite/client/deps/chunk-RABNIDPS.js?v=3f801703:213:18)
```

If I wrap [`cookie.value`](https://gist.github.com/tommie/23539b45f55547d54eac3fdcf8d14231#file-cookie-ts-L49) in Vue's `toRaw`, the error goes away. I can't find any information about ProxyObject not being allowed in `postMessage`...

**Comment by tommie** [comment]
Added repro: https://stackblitz.com/edit/github-hjpstl?file=app.vue

**Comment by Morraycage** [comment]
Hello hope you are doing well

I'm still facing this issue actually:


```
DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': #<Object> could not be cloned.
```

Getting this error when using the `useCookie` this way

```js
useCookie('user').value = {
   ....object,
   test: "hey"
}
```

I tried to debug inside `nuxt` directly and it seems `toRaw` can be an instanceof Proxy object and need to be sometimes used with the `.value` 

Maybe a check `toRaw(cookie.value) instanceof Proxy ? toRaw(cookie.value).value : toRaw(cookie.value)`

**Comment by cmrdth** [comment]
Same here, I still got the issue.
I switched to Universal-cookie temporary but It would be amazing to just check like @Morraycage suggests.

**Comment by danielroe** [comment]
If you are experiencing this would you open a new issue with a reproduction? 🙏

**Comment by lacorde** [comment]
Can confirm I have the same issue !

**Comment by danielroe** [comment]
@lacorde could you open an issue with a reproduction?

**Comment by lacorde** [comment]
Sorry @danielroe, can't seem to reproduce it outside of my own project.
Another issue I came across while working with useCookie is addressed over here #22474
Might be related, and fixed with upcoming 3.7 ?

**Comment by danielroe** [comment]
3.7 is released - let me know if it solves things for you.

**Comment by BernardoSM** [comment]
Hey @danielroe 3.7 version doesn't change anything, I'm still having this issue. This is the error that is showing to me:

![image](https://github.com/nuxt/nuxt/assets/36281298/ebb5490e-5773-4d75-8f4d-65072b954238)

In my case I'm calling useCookie function inside a pinia store to set values and useCookie inside a middleware to read values.

The workaround I'm doing is downgrading my nuxt version to 3.5.3. I hope this helps!

**Comment by danielroe** [comment]
@BernardoSM If you can raise an issue with a reproduction then that would be very helpful.

**Comment by hendrikheil** [comment]
@danielroe We ran into the same issue, and it seems like this happens when useCookie stores a value with nested refs. toRaw is not recursive, so it might return an object that looks similar to this:

```
{
  a: string,
  b: Ref<string>,
}
```

Which is what was originally fixed. I'll post a production shortly

**Comment by hendrikheil** [comment]
@danielroe I'd be happy to send a PR. Do you think the serialize/deserialize approach makes sense? If so, I'd be happy to implement

**Comment by danielroe** [comment]
@hendrikheil Yes, I agree - and I would be delighted with a PR ❤️

**Comment by pshabanov** [comment]
nuxt 3.6 / node 16.16.0 - catch bug
nuxt 3.8 / node 18.18.1 - work
