### ISSUE TITLE
Typescript error when using Nitro plugin due to missing type for "render:html"

### ISSUE THREAD

**Issue by kimbaudi** [nuxt/nuxt#21708]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.5.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, typescript
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

I created a minimal reproduction at https://github.com/kimbaudi/nuxt-nitro.

To reproduce the issue:

```shell
git clone https://github.com/kimbaudi/nuxt-nitro

npm install
// or yarn install

npx tsc
// or yarn tsc
```

### Describe the bug

Following the nuxt doc for extending HTML template (https://nuxt.com/docs/getting-started/views#advanced-extending-the-html-template), I created `server/plugins/extend_html.ts` with the following content:

```ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook("render:html", (html, { event }) => {
    html.head.push(`<meta name="author" content="Paul Kim" />`);
    console.log(event.node.res.statusCode);
  });
});
```

And I get the following typescript errors:

- Argument of type '"render:html"' is not assignable to parameter of type 'HookKeys<NitroRuntimeHooks>'.ts(2345)
- Property 'head' does not exist on type 'Partial<RenderResponse>'.ts(2339)

Looking at `node_modules/nitropack/dist/runtime/types.d.ts`, it seems that `NitroRuntimeHooks` interface is missing `"render:html"` property

![image](https://github.com/nuxt/nuxt/assets/1864092/e9b82540-b89f-4dd2-887f-979e517e5091)

In order to resolve this issue, the `NitroRuntimeHooks` interface should be updated to include "render:html" property. (https://github.com/unjs/nitro/blob/main/src/runtime/types.ts#L23)

### Logs

```shell-script
$ npx tsc
server/plugins/extend-html.ts:2:23 - error TS2345: Argument of type '"render:html"' is not assignable to parameter of type 'HookKeys<NitroRuntimeHooks>'.

2   nitroApp.hooks.hook("render:html", (html, { event }) => {
                        ~~~~~~~~~~~~~

server/plugins/extend-html.ts:3:10 - error TS2339: Property 'head' does not exist on type 'Partial<RenderResponse>'.

3     html.head.push(`<meta name="author" content="Paul Kim" />`);
           ~~~~


Found 2 errors in the same file, starting at: server/plugins/extend-html.ts:2
```

**Comment by kimbaudi** [comment]
Since this bug report is related to the Nitro plugin, I opened an issue at https://github.com/unjs/nitro/issues/1337

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Comment by GuillaumeAmat** [comment]
@danielroe I still have the same issue with the latest 3.6.1 release (from last week). Is the release really embedding the fix?

**Comment by danielroe** [comment]
Would you provide a reproduction?

**Comment by kimbaudi** [comment]
I can confirm that this issue is resolved in nuxt v3.6.1

**Comment by GuillaumeAmat** [comment]
Here it is @danielroe:
https://stackblitz.com/edit/stackblitz-starters-trwf5t?file=src%2Fruntime%2FnitroPlugin.ts

Synced with this repo: https://github.com/GuillaumeAmat/nuxt-issue-21708-reproduction


You can see that the `src/runtime/nitroPlugin.ts` has three TS errors, which are quoted in the comments.

Also, when creating the reproduction, I figured that Stackblitz automatically runs the `dev` npm script, which actually "fixes" two of the typings errors (the remaining one is on the `#nitro` import). So, I "disabled" the npm script by renaming it, so that you can see the errors.

But:

- If you run `npm run dev:disabled` in Stackblitz, two of the errors are gone
- Running this npm script locally doesn't fix anything...

**Comment by danielroe** [comment]
The types need to be generated - you can also do this by running `nuxi prepare`. You shouldn't expect them to work before that point.

The `#nitro` import is not valid. I'm not sure where you got it from, but you should use `#imports` instead. That may require you to create a `~/src/runtime/server` folder and a `~/src/runtime/server/tsconfig.json` that points to the server tsconfig from the playground.

**Comment by GuillaumeAmat** [comment]
> The types need to be generated - you can also do this by running nuxi dev:prepare. You shouldn't expect them to work before that point.

I think you meant `npm run dev:prepare`, right?

If so, I was aware of that and I ran the command multiple times :ok_hand: But I also ran `npx nuxi prepare`, based on your comment.

Both fixes the issue in Stackblitz, after I created the `tsconfig.json` file you mentioned. But none of that works in my local clone of the reproduction repo...

I've pinned node and npm versions in `package.json` so that you can see the versions I'm using.

---

I also tried `npx nuxi typecheck`, but the result is once agin a bit odd :thinking: 

It doesn't report the types issues, even locally, which is good. But:

- Why is my local IDE still mad?
- Why is it reporting the following import errors?

![image](https://github.com/nuxt/nuxt/assets/1179174/5c075de0-a03f-4481-9382-dbf6b56a1d73)

**Comment by GuillaumeAmat** [comment]
> I would check to see if your local tsconfig.json in the root of your project is pointing to the right location, or whether you've overwritten some key options within it.

I don't, actually. Everything is as in the reproduction repo: https://github.com/GuillaumeAmat/nuxt-issue-21708-reproduction

Steps to reproduce:

1. `git clone git@github.com:GuillaumeAmat/nuxt-issue-21708-reproduction.git`
2. `npm install`
3. `npm run dev:prepare`
4. `npx nuxi typecheck`: Same import error as [above](https://github.com/nuxt/nuxt/issues/21708#issuecomment-1623727697)
5. Open VS Code with no extensions and following the project's TS version: Same errors quoted in the reproduction

**Comment by GuillaumeAmat** [comment]
Hey @danielroe, I think I found the root cause of my issue. Thanks for your inputs, by the way :pray: 

The `include` section of the `playground/.nuxt/tsconfig.json` file contains:

```json
"include": [
  "./nuxt.d.ts",
  "../**/*",
  "../../**/*"
],
```

Whereas the same `include` section of the `playground/.nuxt/tsconfig.server.json` file contains:

```json
"include": [
  "/home/guillaume.amat/tmp/nuxt-module-reproduction/nuxt-issue-21708-reproduction/playground/.nuxt/types/nitro-nuxt.d.ts",
  "./types/nitro.d.ts",
  "../**/*",
  "../server/**/*"
]
```

👉 **Notice the "missing" `"../../**/*"` path here.**

If I manually add `"../../**/*"` to the `playground/.nuxt/tsconfig.server.json` file, all the errors are gone and the types seem coherent :ok_hand:

**Comment by danielroe** [comment]
Aha! Good find.
