### ISSUE TITLE
spaLoadingTemplate = false is not honored

### ISSUE THREAD

**Issue by kanhaic** [nuxt/nuxt#21745]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.15.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@9.6.6
- Builder:          vite
- User Config:      ssr, modules, nitro, spaLoadingTemplate, app, i18n, alias, vite, css, postcss, build
- Runtime Modules:  @formkit/nuxt@1.0.0-beta.9-f64c966, @nuxtjs/i18n@8.0.0-beta.9
- Build Modules:    -
------------------------------

### Reproduction

In nuxt.config.ts

set spaLoadingTemplate: false

ssr:false

### Describe the bug

The spaloading page is shown even when spaLoadingTemplate is set to false

**Comment by elishalon** [comment]
Same here, still seeing it after disabling.

**Comment by danielroe** [comment]
Apologies. This should be resolved in https://github.com/nuxt/nuxt/pull/21739.

**Comment by graup** [comment]
@danielroe I updated to the newest version but this screen still shows on first render. Is this not this option?

<img width="1512" alt="Screenshot 2023-08-02 at 19 00 00" src="https://github.com/nuxt/nuxt/assets/898549/88c328b5-67c3-4882-8aec-74d5b10f8c4b">

**Comment by danielroe** [comment]
No, that's just the dev loading screen.

**Comment by SoCuul** [comment]
@danielroe Upon further reflection, this "dev loading screen" was what I thought `spaLoadingTemplate: false` would get rid of, along with the production loader. Maybe the [docs](https://nuxt.com/docs/api/nuxt-config#spaloadingtemplate) could reflect that this only takes effect in production builds?

**Comment by danielroe** [comment]
you're right - that is not related to the `spaLoadingTemplate`.
