### ISSUE TITLE
Error loading primeicons fonts after updating nuxt to 3.6.0

### ISSUE THREAD

**Issue by Kicshikxo** [nuxt/nuxt#21799]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      css, build, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

This is a stackblitz environment, but it happens in any environment, including linux and windows

### Reproduction

https://stackblitz.com/edit/github-shjasa

Run `npm run build && npm run preview`, after which the icon on the button will not display

### Describe the bug

I use the primevue library, and after upgrading nuxt to version 3.6.0 the icons that come with the primeicons font stopped displaying. I noticed that nuxt stopped including them in the final build. On nuxt 3.5.3 and with the same version of primevue it works fine.

### Logs

```shell-script
GET https://githubshjasa-azkj--3000--a19575a2.local-credentialless.webcontainer.io/_nuxt/primeicons.3824be50.woff2 net::ERR_ABORTED 404 (Cannot find static asset /_nuxt/primeicons.3824be50.woff2)
GET https://githubshjasa-azkj--3000--a19575a2.local-credentialless.webcontainer.io/_nuxt/primeicons.90a58d3a.woff net::ERR_ABORTED 404 (Cannot find static asset /_nuxt/primeicons.90a58d3a.woff)
GET https://githubshjasa-azkj--3000--a19575a2.local-credentialless.webcontainer.io/_nuxt/primeicons.131bc3bf.ttf 404 (Cannot find static asset /_nuxt/primeicons.131bc3bf.ttf)
```

**Comment by c-schwan** [comment]
@Kicshikxo fixed by #21790

**Comment by Kicshikxo** [comment]
@c-schwan Thanks for the answer! I will wait for the next stable version

**Comment by lehni** [comment]
I am also seeing this bug, and it's still present in Nuxt v3.6.1 that was just released. Note that this has nothing to do with primeicons, it happens with any font asset. Essentially, font files that reside in the `assets` folder are excluded form the dist folder since v3.6.0.

I've tried the edge channel, but here I can't even build, so I can't confirm that the bug has been fixed since the release of v3.6.1.

```
Nuxi 3.6.2-28130150.54a0d5e8                                                                                                                                                 6:48:09 AM
Nuxt 3.6.2-28130150.54a0d5e8 with Nitro 2.5.2-28129525.966ac34                                                                                                               6:48:09 AM

 ERROR  Nitro entry is missing! Is "static" preset correct?                                                                                                                  6:48:10 AM

  at loadOptions (node_modules/nitropack/dist/shared/nitro.a2466750.mjs:4061:11)
  at async createNitro (node_modules/nitropack/dist/shared/nitro.a2466750.mjs:4226:19)
  at async initNitro (node_modules/nuxt/dist/index.mjs:2493:17)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3201:3)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3240:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:37:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)
  ```

**Comment by lehni** [comment]
This was a duplicate of #21784
