### ISSUE TITLE
errors prerendering `/__pinceau_tokens*` routes on docus site

### ISSUE THREAD

**Issue by ChefKissInc** [nuxt/nuxt#21982]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.3.1`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@3.6.0`
- Builder:          `vite`
- User Config:      `alias`, `extends`, `css`, `colorMode`, `runtimeConfig`, `experimental`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/NootInc/NootInc.github.io

### Describe the bug

Static site generation fails with
```
Errors prerendering:
  ├─ /__pinceau_tokens_config.json (404)
  ├─ /__pinceau_tokens_schema.json (404)
```

### Logs

```shell-script
https://app.warp.dev/block/wurexttaOyc0DYa4pbqjH2
```

**Comment by ChefKissInc** [comment]
Thank you for the WA

**Comment by danielroe** [comment]
This is now resolved in the latest docus version (v1.13.1).

**Comment by 1714080902120** [comment]
i met the problem in 1.14.1 and now i update to 1.15.0, it still exists when `build`... but the prolem seems not effect the build process
