### ISSUE TITLE
useCookie doesn't change value of an object stored in cookie

### ISSUE THREAD

**Issue by sun-ergo-s** [nuxt/nuxt#22001]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      runtimeConfig, app, modules, bugsnag, pwa, cookieControl, pinia, components, css
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @vueuse/nuxt@10.2.1, @dargmuesli/nuxt-cookie-control@5.10.3, @vite-pwa/nuxt@0.0.9
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hunkey

### Describe the bug

When I store an object in a cookie using `useCookie` composable and then want to change the value of a key of that object it doesn't effect the cookie.

### Additional context

I tried Nuxt 3.5.3 and it worked.

**Comment by xibman** [comment]
Same behavior with cookie after update to 3.6.2.

Cookie is not updated after creation

**Comment by Namstel** [comment]
I noticed the same with an array. Example 2 in the docs doesn't seem to work.

https://nuxt.com/docs/api/composables/use-cookie

**Comment by sun-ergo-s** [comment]
@xibman have you tried it? It doesn't seem to work in my case

**Comment by xibman** [comment]
@sun-ergo-s it works on my side.

I use it in a form with a watcher on the form data 

```js
watch(
  () => formData,
    (newValues) => {
      // @ts-expect-error - need to stringify data for cookie update - https://github.com/nuxt/nuxt/issues/22001
     cookieData.value = JSON.stringify(newValues);
  },
  { deep: true },
);
```

**Comment by xibman** [comment]
It think the problem come from here:      https://github.com/nuxt/nuxt/blob/4b6f3e1ba11ee247906a34ea76292bf3a171ed3b/packages/nuxt/src/app/composables/cookie.ts#L42

```js
 channel?.postMessage(toRaw(cookie.value))
 ```
 toRaw not convert incoming proxy data correctly.

**Comment by BenGoetemann** [comment]
i have the same issues

**Comment by pcasaspere** [comment]
I have the same issue. I solved with JSON.stringify:

```javascript
cookie.value = JSON.stringify({
    action: true,
    analytics: true,
  });
```

**Comment by lacorde** [comment]
I can also confirm `cookie.value = JSON.parse(JSON.stringify(newValues));` is working, while waiting for the fix.
Thanks @xibman.

**Comment by GhostvOne** [comment]
It's not fixed yet. I have this issue atm with last update 3.9.0
