### ISSUE TITLE
[nuxt] Cannot load payload  /_payload.json

### ISSUE THREAD

**Issue by Timtendo12** [nuxt/nuxt#22068]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.8.0
- Builder:          vite
- User Config:      pages, debug, dev, modules, pwa, app, vue, ignore
- Runtime Modules:  @nuxt/devtools@0.2.5
- Build Modules:    -
------------------------------

### Reproduction

its a pretty big project, It always worked fine and all I did before this happened was running npm install

### Describe the bug

When using my nuxt site using a different domain navigating to other pages stops working

when I build my site and upload it to azure it comes available on multiple domains

1. the azure domain (Site works fine here)
2. Our domain with a special subdomain (usually its help.domain.app)

On our subdomain the website navigation stops working and spits out the following error:
![image](https://github.com/nuxt/nuxt/assets/41442518/20f041c2-5936-4161-b70d-0ab82f1c044e)

### Logs

```shell-script
build logs
https://hastebin.com/share/oyamipasuv.bash
```

**Comment by GitRowin** [comment]
I ran into the same issue. It works fine in Nuxt version 3.6.1. I think it's caused by this PR: #21860

**Comment by danielroe** [comment]
You can probably work around this by adding:

```ts
export default defineNuxtConfig({
  experimental: {
    payloadExtraction: false
  }
})
```

This should be properly resolved with https://github.com/nuxt/nuxt/issues/21370.

Other context: https://github.com/nuxt/nuxt/issues/15024.

**Comment by Timtendo12** [comment]
> 

This did fix the warning message, but it did not fix the navigation issue. I still get redirected back to "/". It seems like this only applies to routes with childeren. Normal routes without childeren works fine.

**Comment by danielroe** [comment]
possibly same issue as https://github.com/nuxt/nuxt/issues/22072

**Comment by JonathanDoelan** [comment]
What I’ve found out is that since `v3.6.2` we need to explicitly set `experimental.payloadExtraction` to `true`. Otherwise the `_payload.json` files are not generated (in SSG mode).

```js
export default defineNuxtConfig({
  experimental: {
    payloadExtraction: true
  }
})
```

**Comment by toniengelhardt** [comment]
> What I’ve found out is that since `v3.6.2` we need to explicitly set `experimental.payloadExtraction` to `true`. Otherwise the `_payload.json` files are not generated (in SSG mode).
> 
> ```js
> export default defineNuxtConfig({
>   experimental: {
>     payloadExtraction: true
>   }
> })
> ```

That fixes it for me 🙏🏽

**Comment by danielroe** [comment]
Would you try with the latest v3.6.3?

**Comment by toniengelhardt** [comment]
> Would you try with the latest v3.6.3?

Had the issue with `v3.6.3`

**Comment by Gonzalo-Bruna** [comment]
> What I’ve found out is that since `v3.6.2` we need to explicitly set `experimental.payloadExtraction` to `true`. Otherwise the `_payload.json` files are not generated (in SSG mode).
> 
> ```js
> export default defineNuxtConfig({
>   experimental: {
>     payloadExtraction: true
>   }
> })
> ```

This fixed it for me too! thanks a lot!

**Comment by manniL** [comment]
I think the problem is that after https://github.com/nuxt/nuxt/pull/21860, `process.env.NUXT_PAYLOAD_EXTRACTION` is not set correctly anymore as the override from the PR comes "too late".

**Comment by javokhirbekkhaydarov** [comment]
Cannot load payload  in  Nuxt 3.6.5 
 I wrote
   mounted() {
    store.dispatch("products/getProductsByCategoryId", this.$route.params.id);
  },
 it is return this warn
![image](https://github.com/nuxt/nuxt/assets/79502483/9c93ce90-5cdd-41cd-b311-10aeb10cba7e)

    
    
    here my nuxt.config.ts but when i refresh page server return 404 
    
    export default defineNuxtConfig({   
experimental: {
    payloadExtraction: false
  }, 
 nitro: {
    inlineDynamicImports: true
}});

I'm trying to fix it , still not solve this error

**Comment by niko-chaffinchicas** [comment]
@JonathanDoelan Thank you for the workaround. This worked to get `nuxt generate` outputting a static site that can be deployed to `gh-pages` with no errors (Nuxt 3.7.4). 🙌

**Comment by manniL** [comment]
> @JonathanDoelan Thank you for the workaround. This worked to get `nuxt generate` outputting a static site that can be deployed to `gh-pages` with no errors (Nuxt 3.7.4). 🙌

When using `nuxt generate`, payload extraction should be set automatically (if unset) 😋

**Comment by JonathanDoelan** [comment]
Ma workaround is not necessary since v3.6.3

**Comment by niko-chaffinchicas** [comment]
> When using `nuxt generate`, payload extraction should be set automatically (if unset) 😋

@manniL Oh interesting, I'll have to look into the docs and maybe the source code more regarding that, I guess. Thanks!
