### ISSUE TITLE
Mikroorm cli not work, nuxt is bad configured?

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23116]
### Environment

Operating System: Linux
Node Version: v20.5.0
Nuxt Version: 3.7.1
CLI Version: 3.8.0
Nitro Version: 2.6.3-28235083.5639f5b
Package Manager: pnpm@8.7.1
Builder: -
User Config: -
Build Modules: -

### Reproduction

https://github.com/imcm7/nuxt-mikroorm-ts

### Describe the bug

The running of `pnpm db:update` result in `Cannot find module '~/server/entities/index.ts'`

https://github.com/mikro-orm/mikro-orm/issues/4690#issuecomment-1713297240

**Comment by danielroe** [comment]
This isn't a Nuxt issue. `mikro-orm` doesn't seem to be able to read the Nuxt generated `tsconfig.json`.

**Comment by imcm7** [comment]
@danielroe  May be is home how nuxt problem?

The problem was in tsconfig,json

In your examples it is

"paths": {
      "~/*": ["./*"]
    }
In nuxt is

    "~": [
        ".."
      ],
      "~/*": [
        "../*"
      ]

**Comment by danielroe** [comment]
mikro-orm should resolve the paths relative to the location of the `tsconfig.json` where they are present rather than the one extending it.

**Comment by B4nan** [comment]
> mikro-orm should resolve the paths relative to the location of the tsconfig.json where they are present rather than the one extending it.

That sounds a bit weird to me, the tsconfig we use is in the root, that is the path we know about, not where the extended tsconfig lives. FYI the place we register the paths mapping is here:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/ConfigurationLoader.ts#L143-L146

**Comment by B4nan** [comment]
Well, but MikroORM does not resolve anything, it just registers the paths mapping programmatically. The paths are coming from the root tsconfig, we already get the extensions processed (via `ts-node` or one if its dependencies). Note that the user tried to register them explicitly via CLI, so outside of the MikroORM code, and it failed the same, which makes me pretty confident this is not something to fix in the ORM codebase.

**Comment by danielroe** [comment]
It might be an issue not with `mikro-orm` but with one of the tools it's using. See this small stackblitz: https://stackblitz.com/edit/stackblitz-starters-16sdmk

**Comment by B4nan** [comment]
I believe this is the culprit: https://github.com/TypeStrong/ts-node/issues/1948

**Comment by danielroe** [comment]
Nice work finding that ❤️

**Comment by imcm7** [comment]
❤️❤️❤️
