### ISSUE TITLE
.client.vue components causing bug on page navigation

### ISSUE THREAD

**Issue by JenBerry** [nuxt/nuxt#23939]
### Environment

❯ npx nuxi info
Working directory: /home/projects/github-423jt1                                       16:55:22
Nuxt project info:                                                                    16:55:22

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-423jt1?file=pages%2Findex.vue

This minimal reproduction has: Two pages, one .client.vue component on the home page, and some navigation links to navigate between the two pages.

Steps:
1. See that when the home page loads 'A Component' is displayed
2. Navigate to another Page
3. Navigate back to Home
4. See that the component is not displayed
5. Check developer tools for some error messages (shown in the 'Logs' section below)

### Describe the bug

On the homepage there is a client only component (marked with the .client.vue suffix)
This component displays on page load, but if you navigate to another page and navigate back again, it has disappeared. There are some error messages in the developer tools (copied below)

### Additional context

I want to mark relevant components as client only so that they don't get compiled into the server bundle in order reduce bundle size.

### Logs

In the developer tools we get an error message saying the following:

```shell-script
chunk-UJJZ7LWV.js:1436 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <AComponent.client> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {…} > > 
  at <RouteProvider key="/" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/', path: '/', query: {…}, hash: '', name: 'index', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=3 > 
  at <NuxtRoot>
warn2 @ chunk-UJJZ7LWV.js:1436
logError @ chunk-UJJZ7LWV.js:1610
handleError @ chunk-UJJZ7LWV.js:1602
callWithErrorHandling @ chunk-UJJZ7LWV.js:1554
flushJobs @ chunk-UJJZ7LWV.js:1755
flushJobs @ chunk-UJJZ7LWV.js:1765
Promise.then (async)
queueFlush @ chunk-UJJZ7LWV.js:1668
queuePostFlushCb @ chunk-UJJZ7LWV.js:1688
queueEffectWithSuspense @ chunk-UJJZ7LWV.js:3004
scheduler @ chunk-UJJZ7LWV.js:3171
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:603
triggerRefValue @ chunk-UJJZ7LWV.js:1202
set value @ chunk-UJJZ7LWV.js:1246
doSet @ chunk-UJJZ7LWV.js:5865
setRef @ chunk-UJJZ7LWV.js:5876
(anonymous) @ chunk-UJJZ7LWV.js:5797
setRef @ chunk-UJJZ7LWV.js:5796
unmount @ chunk-UJJZ7LWV.js:7611
unmountComponent @ chunk-UJJZ7LWV.js:7723
unmount @ chunk-UJJZ7LWV.js:7624
resolve @ chunk-UJJZ7LWV.js:2780
(anonymous) @ chunk-UJJZ7LWV.js:2906
Promise.then (async)
registerDep @ chunk-UJJZ7LWV.js:2870
mountComponent @ chunk-UJJZ7LWV.js:7034
processComponent @ chunk-UJJZ7LWV.js:6994
patch @ chunk-UJJZ7LWV.js:6467
mountChildren @ chunk-UJJZ7LWV.js:6711
mountElement @ chunk-UJJZ7LWV.js:6618
processElement @ chunk-UJJZ7LWV.js:6583
patch @ chunk-UJJZ7LWV.js:6455
componentUpdateFn @ chunk-UJJZ7LWV.js:7137
run @ chunk-UJJZ7LWV.js:422
instance.update @ chunk-UJJZ7LWV.js:7243
setupRenderEffect @ chunk-UJJZ7LWV.js:7251
mountComponent @ chunk-UJJZ7LWV.js:7041
processComponent @ chunk-UJJZ7LWV.js:6994
patch @ chunk-UJJZ7LWV.js:6467
componentUpdateFn @ chunk-UJJZ7LWV.js:7137
run @ chunk-UJJZ7LWV.js:422
instance.update @ chunk-UJJZ7LWV.js:7243
setupRenderEffect @ chunk-UJJZ7LWV.js:7251
mountComponent @ chunk-UJJZ7LWV.js:7041
processComponent @ chunk-UJJZ7LWV.js:6994
patch @ chunk-UJJZ7LWV.js:6467
patchSuspense @ chunk-UJJZ7LWV.js:2670
process @ chunk-UJJZ7LWV.js:2473
patch @ chunk-UJJZ7LWV.js:6492
componentUpdateFn @ chunk-UJJZ7LWV.js:7202
run @ chunk-UJJZ7LWV.js:422
instance.update @ chunk-UJJZ7LWV.js:7243
callWithErrorHandling @ chunk-UJJZ7LWV.js:1552
flushJobs @ chunk-UJJZ7LWV.js:1755
Promise.then (async)
queueFlush @ chunk-UJJZ7LWV.js:1668
queueJob @ chunk-UJJZ7LWV.js:1662
(anonymous) @ chunk-UJJZ7LWV.js:7239
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:603
triggerRefValue @ chunk-UJJZ7LWV.js:1202
(anonymous) @ chunk-UJJZ7LWV.js:1358
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:598
triggerRefValue @ chunk-UJJZ7LWV.js:1202
(anonymous) @ chunk-UJJZ7LWV.js:1358
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:598
triggerRefValue @ chunk-UJJZ7LWV.js:1202
(anonymous) @ chunk-UJJZ7LWV.js:1358
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:598
triggerRefValue @ chunk-UJJZ7LWV.js:1202
(anonymous) @ chunk-UJJZ7LWV.js:1358
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:598
triggerRefValue @ chunk-UJJZ7LWV.js:1202
set value @ chunk-UJJZ7LWV.js:1246
finalizeNavigation @ vue-router.js:2563
(anonymous) @ vue-router.js:2473
Promise.then (async)
pushWithRedirect @ vue-router.js:2441
push @ vue-router.js:2367
navigate @ vue-router.js:1621
callWithErrorHandling @ chunk-UJJZ7LWV.js:1552
callWithAsyncErrorHandling @ chunk-UJJZ7LWV.js:1560
invoker @ chunk-UJJZ7LWV.js:9752
```

and 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (chunk-UJJZ7LWV.js:9197:30)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-UJJZ7LWV.js:7206:11)
    at ReactiveEffect.run (chunk-UJJZ7LWV.js:422:19)
    at instance.update (chunk-UJJZ7LWV.js:7243:52)
    at callWithErrorHandling (chunk-UJJZ7LWV.js:1552:32)
    at flushJobs (chunk-UJJZ7LWV.js:1755:9)
    at flushJobs (chunk-UJJZ7LWV.js:1765:7)
parentNode @ chunk-UJJZ7LWV.js:9197
componentUpdateFn @ chunk-UJJZ7LWV.js:7206
run @ chunk-UJJZ7LWV.js:422
instance.update @ chunk-UJJZ7LWV.js:7243
callWithErrorHandling @ chunk-UJJZ7LWV.js:1552
flushJobs @ chunk-UJJZ7LWV.js:1755
flushJobs @ chunk-UJJZ7LWV.js:1765
Promise.then (async)
nextTick @ chunk-UJJZ7LWV.js:1635
onResolve @ page.js?v=2b17d26d:81
triggerEvent @ chunk-UJJZ7LWV.js:2494
resolve @ chunk-UJJZ7LWV.js:2811
(anonymous) @ chunk-UJJZ7LWV.js:2906
Promise.then (async)
registerDep @ chunk-UJJZ7LWV.js:2870
mountComponent @ chunk-UJJZ7LWV.js:7034
processComponent @ chunk-UJJZ7LWV.js:6994
patch @ chunk-UJJZ7LWV.js:6467
mountChildren @ chunk-UJJZ7LWV.js:6711
mountElement @ chunk-UJJZ7LWV.js:6618
processElement @ chunk-UJJZ7LWV.js:6583
patch @ chunk-UJJZ7LWV.js:6455
componentUpdateFn @ chunk-UJJZ7LWV.js:7137
run @ chunk-UJJZ7LWV.js:422
instance.update @ chunk-UJJZ7LWV.js:7243
setupRenderEffect @ chunk-UJJZ7LWV.js:7251
mountComponent @ chunk-UJJZ7LWV.js:7041
processComponent @ chunk-UJJZ7LWV.js:6994
patch @ chunk-UJJZ7LWV.js:6467
componentUpdateFn @ chunk-UJJZ7LWV.js:7137
run @ chunk-UJJZ7LWV.js:422
instance.update @ chunk-UJJZ7LWV.js:7243
setupRenderEffect @ chunk-UJJZ7LWV.js:7251
mountComponent @ chunk-UJJZ7LWV.js:7041
processComponent @ chunk-UJJZ7LWV.js:6994
patch @ chunk-UJJZ7LWV.js:6467
patchSuspense @ chunk-UJJZ7LWV.js:2670
process @ chunk-UJJZ7LWV.js:2473
patch @ chunk-UJJZ7LWV.js:6492
componentUpdateFn @ chunk-UJJZ7LWV.js:7202
run @ chunk-UJJZ7LWV.js:422
instance.update @ chunk-UJJZ7LWV.js:7243
callWithErrorHandling @ chunk-UJJZ7LWV.js:1552
flushJobs @ chunk-UJJZ7LWV.js:1755
Promise.then (async)
queueFlush @ chunk-UJJZ7LWV.js:1668
queueJob @ chunk-UJJZ7LWV.js:1662
(anonymous) @ chunk-UJJZ7LWV.js:7239
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:603
triggerRefValue @ chunk-UJJZ7LWV.js:1202
(anonymous) @ chunk-UJJZ7LWV.js:1358
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:598
triggerRefValue @ chunk-UJJZ7LWV.js:1202
(anonymous) @ chunk-UJJZ7LWV.js:1358
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:598
triggerRefValue @ chunk-UJJZ7LWV.js:1202
(anonymous) @ chunk-UJJZ7LWV.js:1358
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:598
triggerRefValue @ chunk-UJJZ7LWV.js:1202
(anonymous) @ chunk-UJJZ7LWV.js:1358
triggerEffect @ chunk-UJJZ7LWV.js:613
triggerEffects @ chunk-UJJZ7LWV.js:598
triggerRefValue @ chunk-UJJZ7LWV.js:1202
set value @ chunk-UJJZ7LWV.js:1246
finalizeNavigation @ vue-router.js:2563
(anonymous) @ vue-router.js:2473
Promise.then (async)
pushWithRedirect @ vue-router.js:2441
push @ vue-router.js:2367
navigate @ vue-router.js:1621
callWithErrorHandling @ chunk-UJJZ7LWV.js:1552
callWithAsyncErrorHandling @ chunk-UJJZ7LWV.js:1560
invoker @ chunk-UJJZ7LWV.js:9752
```
```

**Comment by danielroe** [comment]
This might have already been resolved in https://github.com/nuxt/nuxt/pull/23899 - would you try with the latest edge release? 🙏

**Comment by JenBerry** [comment]
Trying it here: https://stackblitz.com/edit/github-423jt1-lktqxp
The problem remains the same

**Comment by qoo1476** [comment]
for me. error is gone with latest nightly version (3.8.1-28309583.4b2608c7) but only on dev.
the error is still remains after build
*Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode') ...

**Comment by just-maik** [comment]
Error persists for me too. I have the same setup but use the client component lazily.

**Comment by just-maik** [comment]
Fixed for me in Nuxt 3.8.1-28309583.4b2608c7 with Nitro 2.8.0-28308950.fd4671c.

The first reproduction provided by @JenBerry seems to be fixed  https://stackblitz.com/edit/github-423jt1-ecdqmx?file=package.json (I just bumped nuxt to nightly)

Fixes [this reproduction](https://stackblitz.com/edit/nuxt-starter-gz3gnn?file=components%2FReseller%2FMap.client.vue) as well

**Comment by danielroe** [comment]
Thanks for checking ❤️
