### ISSUE TITLE
Setting `shamefully-hoist=false` will make nitro generated types fail

### ISSUE THREAD

**Issue by awdr74100** [nuxt/nuxt#23984]
### Environment

- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools, typescript, runtimeConfig, experimental, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.1
- Build Modules:    -

### Reproduction

repo: https://github.com/awdr74100/nuxt-bug-reproduction

`nuxt.config.ts`
```ts
export default defineNuxtConfig({
  devtools: { enabled: false },
  runtimeConfig: {
    resend: {
      apiKey: "",
    },
  },
});
```

`.npmrc`
```env
shamefully-hoist=false
```

### Describe the bug

```ts
const config = useRuntimeConfig();

_resend = new Resend(config.resend.apiKey);
```

`shamefully-hoist=true`
```ts
(property) RuntimeConfig.resend: {
    apiKey: string;
}
```

`shamefully-hoist=false`
```ts
(index) NitroRuntimeConfig[string]: any
```

**Comment by dargmuesli** [comment]
A workaround is to install `nitropack` as `devDependency`. (@danielroe this is what we had a chat about)

**Comment by 0x2c9** [comment]
The same issue appears for the `app.config.ts`

**Comment by danielroe** [comment]
We could add `nitropack` to tsconfig paths, as well as some other key packages (at least the ones we auto-import), which might also mean we don't need to use full path in `unimport`, etc.

**Comment by woldtwerk** [comment]
my current workaround is:
```
public-hoist-pattern[]=*nitropack*
```
https://github.com/nuxt/nuxt/issues/25112#issuecomment-1975249943

**Comment by danielwaltz** [comment]
Maybe already implied by the title, but I figured it was worth explicitly mentioning that this also prevents TypeScript from being aware of `import.meta.env`.

In my projects using pnpm, trying to access `import.meta.env` without an implemented workaround gives this type error: 

<img width="663" alt="image" src="https://github.com/nuxt/nuxt/assets/2197883/f6540577-4418-4964-8aca-96630101e63e">

I think this is especially damaging as `env` is missing entirely instead of at least being typed as `Record<string, any>`, possibly leading people to believe that you are unable to access environment variables with `import.meta` at all and requiring you to use either `@ts-ignore` or `@ts-expect-error` comments to disable TypeScript completely on those lines if you are already aware of its existence.

I see this is a possible barrier/blocker to getting Nuxt users to migrate from using `process` to `import.meta`, although it is good that it only impacts people using pnpm without configuring `shamefully-hoist`!

**Comment by danielroe** [comment]
This should be resolved in v3.11+.

**Comment by Sun-ZhenXing** [comment]
This problem seems to still exist in Nuxt v3.11.2. I am using pnpm 9.1.2.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by danielwaltz** [comment]
Took a crack at a reproduction myself because unfortunately I am also still observing this in my pnpm backed projects.

https://stackblitz.com/edit/pnpm-import-meta-env-typescript-reproduction?file=app.vue

Loading up that stackblitz and running `pnpm typecheck` should reveal the issue. The console.log shows the contents of `import.meta.env` at runtime as expected, but TypeScript errors with the following message:

```
app.vue:4:25 - error TS2339: Property 'env' does not exist on type 'ImportMeta'.
```

This error also appears inside your editor, though it looks like stackblitz doesn't support that.

Also if it helps my [personal site](https://github.com/danielwaltz/daniel-waltz) is using pnpm + nuxt nightly with the new `app/` directory structure and can be used as an alternative reproduction if desired. Just for giggles I like keeping it on the bleeding edge of Nuxt because I think it's fun to check out all the awesome work you and the whole team are doing early. 🤓

**Comment by Lehoczky** [comment]
I can confirm, this is still an issue with the latest version of Nuxt (3.12.2 at the time of writing). Env variables are missing from `import.meta`.

**Comment by killjoy1221** [comment]
Adding vite as a dev dependency should resolve any `import.meta.env` issues.

**Comment by andreakru** [comment]
I have still the same issue with nitropack

![Image](https://github.com/user-attachments/assets/946586d4-c690-465d-a3e4-3c45bf116b75)

I tried with .npmrc file and also by adding paths to tsconfig.ts but still the same.

tsconfig.ts

```
{
  "extends": "../.nuxt/tsconfig.server.json",
  "compilerOptions": {
    "baseUrl": ".", // Ensure baseUrl is defined at the root of the project
    "paths": {
      "nitropack": ["node_modules/nitropack"]
    }
  }
}
```

.npmrc

`public-hoist-pattern[]=*nitropack*`

**Comment by danielroe** [comment]
You should not set baseUrl

**Comment by andreakru** [comment]
> You should not set baseUrl.
> 
> I’ve just merged a fix for the vite environment issues and will investigate the repro above from [@danielwaltz](https://github.com/danielwaltz) later.

I am not sure what do you mean by not setting baseUrl.

However, it seems to works fine using:

`import type { $Fetch, NitroFetchRequest } from "nitro/types";`

NOTE: I am testing nuxt nightly with` "nuxt": "npm:nuxt-nightly@latest",`

**Comment by danielroe** [comment]
If you are using nuxt-nightly on the v4 branch (as you are) then yes, nitropack has been replaced with `nitro`.

**Comment by OrbisK** [comment]
I think this has been fixed. I have updated [the reproduction](https://github.com/nuxt/nuxt/issues/23984#issuecomment-2123720752) of @danielwaltz and am no longer getting the type error.
