### ISSUE TITLE
Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by WenisOK** [nuxt/nuxt#25179]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.9.1`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ghhe2w?file=layouts%2Fdefault.vue

### Describe the bug

When I clicke the `NuxtLink` text，the browser doesn't to display the pages, and the browser display console the error in the **Logs** section.

### Logs
```
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core . 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=3 > 
  at <NuxtRoot>
warn$1 @ chunk-FRWRVS7C.js?v=373e3ccb:1486

chunk-FRWRVS7C.js?v=373e3ccb:9605 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (chunk-FRWRVS7C.js?v=373e3ccb:9605:30)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-FRWRVS7C.js?v=373e3ccb:7513:11)
    at ReactiveEffect.run (chunk-FRWRVS7C.js?v=373e3ccb:421:19)
    at instance.update (chunk-FRWRVS7C.js?v=373e3ccb:7553:17)
    at callWithErrorHandling (chunk-FRWRVS7C.js?v=373e3ccb:1634:32)
    at flushJobs (chunk-FRWRVS7C.js?v=373e3ccb:1841:9)
```

**Comment by WenisOK** [comment]
> Looks to be an issue within the latest Vue 3 release. See [vuejs/core#10098](https://github.com/vuejs/core/issues/10098)
Oh, no, that seems to be the real problem. So is there any way to solve this problem?

**Comment by jonathan-rvezy** [comment]
Add a vue dependency to your project and pin it to the version you want. We're also in the same boat that we're avoiding vue 3.4.x right now as it's very unstable.

**Comment by manniL** [comment]
Upstream bug, as workaround use Vue 3.4.10 or lower ☺️

**Comment by rasensio** [comment]
Setting version to Vue 3.4.10 worked for me.

**Comment by AnzhiZhang** [comment]
using vue 3.4.11, downgrade to 3.4.10 works for me

**Comment by 7836246** [comment]
我也遇到了同样的问题

**Comment by adydetra** [comment]
temporarily use `v3.4.10`

**Comment by adydetra** [comment]
temporarily use vue `v3.4.10`

**Comment by Smart-Ace-Designs** [comment]
Vue `v3.4.12` just released and fixed the problem for me.

**Comment by zabavnikov** [comment]
Nuxt v3.9.1, Vue v3.4.12 - the bug is still there

**Comment by AnzhiZhang** [comment]
3.4.13 has released and this issue has been fixed: https://github.com/vuejs/core/issues/10098#issuecomment-1890407900

**Comment by WenisOK** [comment]
at this time, the bug still exist
nuxt version: 3.9.0
vue version: 3.4.14

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/25214.

**Comment by younex1** [comment]
Bug still exist on vue >=3.4.9.

**Comment by sanjarbarakayev** [comment]
In my case, the issue was fixed by checking the `Teleport` component with v-if on mount.
```
<template>
  ...
  <Teleport v-if="mounted" to="#target">
    ...
  </Teleport>
...
</template>

<script setup lang="ts">
const { mounted } = useMounted()
</script>
```

**Comment by DaDlugosch** [comment]
@sanjarbarakayev Thanks man, it works. I used build-in `<ClientOnly>` component as a wrapper and error disappeared.
