### ISSUE TITLE
Unable to add custom routes via `pages:extend` hook

### ISSUE THREAD

**Issue by bgondy** [nuxt/nuxt#25562]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.10.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.14.3`
- Builder:          `-`
- User Config:      `devtools`, `hooks`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-npkz3u?file=nuxt.config.ts

### Describe the bug

When adding a custom route using the `pages:extend` hook, get the following error : 

![CleanShot 2024-02-01 at 11 25 21@2x](https://github.com/nuxt/nuxt/assets/675238/0ef504ab-e5f5-40c0-bbea-8c42cf95b4be)

It was working as expected as of nuxt@3.9, but it's not working with nuxt@3.10 anymore.

Maybe I'm missing something, but I haven't found much information about this in docs.

### Additional context

In a context of a migration from Nuxt2 to Nuxt3, I want to add custom routes to my application with specific metadata. Those routes (which have not been migrated yet) must redirect to the legacy website. 

I've created a global middleware that performs a hard page reload when the matched route has the `{ isLegacy: true }` in client side (our reverse proxy already serves Nuxt2 or Nuxt3 depending on the requested URL in server side). This route will never be rendered, that's why the optional `file` property is not set.

### Logs

```shell-script
nuxt.js?v=4faa9c13:98 [nuxt] error caught during app initialization TypeError: aliases is not iterable
    at addRoute (vue-router.js?v=4faa9c13:1065:27)
    at vue-router.js?v=4faa9c13:1219:29
    at Array.forEach (<anonymous>)
    at createRouterMatcher (vue-router.js?v=4faa9c13:1219:10)
    at createRouter (vue-router.js?v=4faa9c13:2233:19)
    at setup (router.js?v=4faa9c13:46:20)
    at client.mjs:31:69
    at executeAsync (index.mjs?v=4faa9c13:111:19)
    at setup (client.mjs:31:43)
    at nuxt.js?v=4faa9c13:111:60
```

**Comment by danielroe** [comment]
This should be resolved in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel), or in the next release via https://github.com/nuxt/nuxt/pull/25515.

Let me know if not and I'll reopen.

**Comment by bgondy** [comment]
@danielroe The problem is still here with `nuxt@3.10.1` (see https://stackblitz.com/edit/github-4xemgn?file=nuxt.config.ts).

**Comment by bgondy** [comment]
This is now working as expected as of `nuxt@3.10.2`.
