### ISSUE TITLE
Enabling experimental typed pages breaks resolving type

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt#26232]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.3
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-kyn7kc?file=app.vue

### Describe the bug

When `experimental.typedPages` is enabled and declaring `defineProps<NuxtLinkProps>()`, Vue errors. When disabled, the error is gone.

**Comment by cpreston321** [comment]
`defineProps` is only meant to be used on a component not the root level `app.vue`. I guess the question here is why defineProps on the app.vue ?

**Comment by huang-julien** [comment]
@DamianGlowala it should be fixed on the nightly channel

**Comment by DamianGlowala** [comment]
I've updated Nuxt to v.3.11.0 in the attached reproduction and the error is still there.

**Comment by DamianGlowala** [comment]
This seems to be no longer the case in the latest version of Nuxt, closing.
