### ISSUE TITLE
dev server logging prevents `console.debug` calls from showing in browser

### ISSUE THREAD

**Issue by fabis94** [nuxt/nuxt#26369]
### Environment

[12:28:21 PM] Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  yarn@3.2.0
- Builder:          -
- User Config:      typescript, modules, runtimeConfig, alias, vite, app, routeRules, nitro, build, hooks, prometheus
- Runtime Modules:  @nuxt/devtools@0.2.5, @nuxtjs/tailwindcss@6.3.0, ~/lib/core/nuxt-modules/apollo/module.ts, @speckle/ui-components-nuxt@0.0.1, @artmizu/nuxt-prometheus@2.2.1
- Build Modules:    -
------------------------------

[12:28:21 PM] 👉 Report an issue: https://github.com/nuxt/nuxt/issues/new

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

Issue is obvious from code

### Describe the bug

The new server log streaming to client feature (https://github.com/nuxt/nuxt/pull/25936/files) has essentially made it so that all `console.*` methods are proxied through Consola on the frontend. But there's no way to configure the Consola instance meaning its using its defaults, including the default log level.

What this means in practice is that all `console.debug` calls are essentially skipped, because the `debug` log level is too low for the default log level.

### Additional context

Introduced by this feature in nuxt 3.11: https://github.com/nuxt/nuxt/pull/25936/files

**Comment by fabis94** [comment]
Btw, the workaround for now is to just disable this feature entirely w/ `devLogs: false` in the nuxt config

**Comment by danielroe** [comment]
This is fixed in v3.11.1 - just upgrade 🙏

**Comment by fabis94** [comment]
@danielroe I am on v3.11.1 already 🤔

**Comment by danielroe** [comment]
Oops - my bad!

**Comment by danielroe** [comment]
This should only be true during the initial hydration, right?

**Comment by fabis94** [comment]
@danielroe Repro: https://github.com/fabis94/nuxi-consola-breakage-repro

See the `console.debug` invocation in app.vue

**Comment by danielroe** [comment]
This has been resolved in https://github.com/nuxt/nuxt/pull/27309 in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel), or in the next release.

Let me know if not and I'll reopen.

**Comment by dia-maya** [comment]
@danielroe I'm still experiencing a variation of this issue in Nuxt 4.5.2: `console.debug` logs do not show up in the terminal when `devLogs` is active. Specifically, I'm not seeing a debug message in the terminal when calling `console.debug` in a Nitro plugin.

**Comment by danielroe** [comment]
console.debug won't show up unless you set your debug level as an env variable

does it work if you disable devLogs?
