### ISSUE TITLE
Infinite initializing JS/TS language features and automatic import errors

### ISSUE THREAD

**Issue by carvalhoms** [nuxt/nuxt#26795]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

![Captura de Tela 2024-04-15 às 19 34 02](https://github.com/nuxt/nuxt/assets/24547646/6866c9cb-5863-487e-bc39-e294341cd442)

Report this:
![Captura de Tela 2024-04-15 às 19 44 30](https://github.com/nuxt/nuxt/assets/24547646/a0f5982c-1064-44cb-b9ca-01352f8e668f)

But in my tsconfig.json I already have:

![Captura de Tela 2024-04-15 às 19 45 30](https://github.com/nuxt/nuxt/assets/24547646/61e87c61-6282-40b9-8ee0-826b8f279114)

Almost an hour and the initializing JS/TS languages ​​features haven't finished, I'm waiting to be able to print it and I can't even do that.

### Describe the bug

I would like some help on why I'm having so many problems with my nuxt 3 project. This initializing JS/TS language features takes minutes and when finished my ts and vue files are full of errors. Suddenly I'm working and this happens suddenly and this error never disappears. On my nestjs backend I never have this problem and everything looks good. But with nuxt3 I just can't get it to work.

### Additional context

I download a new nuxt project, and everything is ok, I start transferring all my code (I know what's wrong), suddenly something updates, be it the ts plugin or vue official and everything starts to go wrong, a real nightmare.

**Comment by carvalhoms** [comment]
See the number of problems:

![Captura de Tela 2024-04-15 às 19 50 16](https://github.com/nuxt/nuxt/assets/24547646/b0147832-a0cb-444a-bb18-d702f647503b)

**Comment by carvalhoms** [comment]
After more than an hour the initialization is completed and my files look like this:

![Captura de Tela 2024-04-15 às 20 47 31](https://github.com/nuxt/nuxt/assets/24547646/1882e1d8-ea82-45de-af98-356dc774362b)

**Comment by carvalhoms** [comment]
Everything seems to be associated with this extends. What a headache.

{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}

**Comment by yuhueilee** [comment]
I've also encountered similar issue, it seems to be related with the typescript version used in VS code.

Following the steps below works for me:
https://stackoverflow.com/questions/75941108/cannot-find-name-definenuxtconfig-ts2304

**Comment by danielroe** [comment]
This seems to be an IDE issue, perhaps an issue with Volar (the Vue Official extension) and not Nuxt. I hope it's resolved in the latest update 🙏

**Comment by MangMax** [comment]
This problem is a headache, it looks like it's a vscode problem, because even with a new nuxt3 project he still can't get it to work, it makes our team have to develop the nuxt3 project on webstrom, I hope someone can provide an effective solution🙏

**Comment by Serpentarius13** [comment]
I just had a similar one with Astro. But mine was complaining about VSCode's version. Maybe try adding this into your settings.json so vscode always recognizes only workspace's version?
```
"typescript.tsdk": "./node_modules/typescript/lib",
```

**Comment by Bruno1510** [comment]
Same issue developing two projects: NestJS and React.
