### ISSUE TITLE
Build failing in production (Digital Ocean) - ERROR Cannot find module '/workspace/@nuxtjs/supabase' 3.11.2 - 3.12.2

### ISSUE THREAD

**Issue by nosizejosh** [nuxt/nuxt#27782]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.4.0
- Builder:          -
- User Config:      ssr, debug, runtimeConfig, devtools, modules, ui, css, app, supabase, security
- Runtime Modules:  @nuxtjs/supabase@1.2.2, @vueuse/nuxt@10.11.0, @pinia/nuxt@0.5.1, @nuxt/ui@2.17.0, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-icon@0.6.10, @nuxtjs/device@3.1.1
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/nuxt-modules/supabase/issues/365

### Describe the bug

I have not been able to successfully deploy to production ( DO) since nuxt 3.11.2
I initially thought it was a [nuxt/supbase issue](https://github.com/nuxt-modules/supabase/issues/365) from the error logs (https://github.com/nuxt-modules/supabase/issues/365)

I have confirmed this issue happens anytime I try to update nuxt past 3.11.2
I just attempted to upgrade to 3.12.2 with and with ought upgrading nuxt/supabase and though local build is successful,  build for production failed.

Logs attached below. Please help!

### Logs

```shell-script
2024-06-23T01:23:48.758900470Z [34m╭────────────[34m[30m[44m git repo clone [0m[0m[34m───────────╼[0m
2024-06-23T01:23:48.759089513Z [34m│[0m [34m › fetching app source code[0m
2024-06-23T01:23:48.759093009Z [34m│[0m => Selecting branch "master"
2024-06-23T01:23:49.579456879Z [34m│[0m => Checking out commit "f91ac002ce505575bafaf92d8db9bb01307cd500"
2024-06-23T01:23:49.605493311Z [34m│[0m 
2024-06-23T01:23:49.606800344Z [34m│[0m [32m ✔ cloned repo to [35m/workspace[0m[0m
2024-06-23T01:23:49.620820069Z [34m╰────────────────────────────────────────╼[0m
2024-06-23T01:23:49.620831762Z 
2024-06-23T01:23:49.702025053Z [34m › configuring build-time app environment variables:[0m
2024-06-23T01:23:49.702043165Z      SUPABASE_KEY SUPABASE_SERVICE_KEY SERVER_PRESET SUPABASE_URL
2024-06-23T01:23:49.702045250Z 
2024-06-23T01:23:49.703490601Z [34m › configuring custom build command to be run at the end of the build:[0m
2024-06-23T01:23:49.705206017Z    [34m│[0m npm run build
2024-06-23T01:23:49.705317715Z 
2024-06-23T01:23:49.788621781Z [34m╭────────────[34m[30m[44m buildpack detection [0m[0m[34m───────────╼[0m
2024-06-23T01:23:49.799554243Z [34m│[0m [34m › using Ubuntu 22.04 stack[0m
2024-06-23T01:23:50.125278231Z [34m│[0m Detected the following buildpacks suitable to build your app:
2024-06-23T01:23:50.125475901Z [34m│[0m 
2024-06-23T01:23:50.125481240Z [34m│[0m    heroku/nodejs-engine   v1.5.4  
2024-06-23T01:23:50.125483774Z [34m│[0m    digitalocean/node      v0.4.0  (Node.js)
2024-06-23T01:23:50.125485597Z [34m│[0m    digitalocean/procfile  v0.0.4  (Procfile)
2024-06-23T01:23:50.125489288Z [34m│[0m    digitalocean/custom    v0.1.2  (Custom Build Command)
2024-06-23T01:23:50.125491758Z [34m│[0m 
2024-06-23T01:23:50.125495143Z [34m│[0m For documentation on the buildpacks used to build your app, please see:
2024-06-23T01:23:50.125497266Z [34m│[0m 
2024-06-23T01:23:50.125499561Z [34m│[0m    Node.js  v0.4.0  https://do.co/apps-buildpack-node
2024-06-23T01:23:50.127641802Z [34m╰─────────────────────────────────────────────╼[0m
2024-06-23T01:23:50.127661142Z 
2024-06-23T01:23:50.129827522Z [34m╭────────────[34m[30m[44m build caching [0m[0m[34m───────────╼[0m
2024-06-23T01:23:50.131429584Z [34m│[0m [34m › checking for cache from a previous build[0m
2024-06-23T01:23:50.425804684Z [34m│[0m Restoring metadata for "heroku/nodejs-engine:nodejs" from app image
2024-06-23T01:23:50.425831518Z [34m│[0m Restoring metadata for "heroku/nodejs-engine:toolbox" from cache
2024-06-23T01:23:50.425834148Z [34m│[0m Restoring metadata for "digitalocean/node:node_modules" from cache
2024-06-23T01:23:50.942355880Z [34m│[0m Restoring data for "heroku/nodejs-engine:nodejs" from cache
2024-06-23T01:23:50.942385457Z [34m│[0m Restoring data for "heroku/nodejs-engine:toolbox" from cache
2024-06-23T01:23:50.942388644Z [34m│[0m Restoring data for "digitalocean/node:node_modules" from cache
2024-06-23T01:23:54.422747906Z [34m╰───────────────────────────────────────╼[0m
2024-06-23T01:23:54.422840627Z 
2024-06-23T01:23:54.425590741Z [34m╭────────────[34m[30m[44m app build [0m[0m[34m───────────╼[0m
2024-06-23T01:23:54.448547968Z [34m│[0m [INFO] Node.js Buildpack
2024-06-23T01:23:54.450051725Z [34m│[0m [INFO] Setting NODE_ENV to production
2024-06-23T01:23:54.450290828Z [34m│[0m [INFO] Installing toolbox
2024-06-23T01:23:54.451628119Z [34m│[0m 
2024-06-23T01:23:54.451646854Z [34m│[0m [1;35m[Installing Node][0m
2024-06-23T01:23:54.451663564Z [34m│[0m [INFO] Getting Node version
2024-06-23T01:23:54.454623307Z [34m│[0m [INFO] Resolving Node version
2024-06-23T01:23:55.258833427Z [34m│[0m [INFO] Reusing Node v20.15.0
2024-06-23T01:23:55.259037736Z [34m│[0m 
2024-06-23T01:23:55.259060442Z [34m│[0m [1;35m[Parsing package.json][0m
2024-06-23T01:23:55.259064795Z [34m│[0m [INFO] Parsing package.json
2024-06-23T01:23:55.674415938Z [34m│[0m [INFO] No file to start server
2024-06-23T01:23:55.674450580Z [34m│[0m [INFO] either use 'docker run' to start container or add index.js or server.js
2024-06-23T01:23:55.685547740Z [34m│[0m Project contains package-lock.json, using npm
2024-06-23T01:23:55.787482571Z [34m│[0m Using npm v10.7.0. To configure a different version of npm, set the engines.npm property in package.json.
2024-06-23T01:23:55.787676066Z [34m│[0m   See https://do.co/apps-buildpack-node for further instructions.
2024-06-23T01:23:55.787720764Z [34m│[0m Installing node_modules using npm (from package-lock.json)
2024-06-23T01:23:55.858832572Z [34m│[0m Running npm ci
2024-06-23T01:23:55.859084691Z [34m│[0m 
2024-06-23T01:23:58.925702329Z [34m│[0m npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
2024-06-23T01:23:59.566084243Z [34m│[0m npm warn deprecated npmlog@5.0.1: This package is no longer supported.
2024-06-23T01:23:59.997735727Z [34m│[0m npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
2024-06-23T01:24:00.070447166Z [34m│[0m npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
2024-06-23T01:24:00.368618348Z [34m│[0m npm warn deprecated gauge@3.0.2: This package is no longer supported.
2024-06-23T01:24:00.547669511Z [34m│[0m npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
2024-06-23T01:24:02.089170256Z [34m│[0m npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
2024-06-23T01:24:02.216138080Z [34m│[0m npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
2024-06-23T01:24:02.445132963Z [34m│[0m npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
2024-06-23T01:24:04.511404580Z [34m│[0m 
2024-06-23T01:24:04.511639875Z [34m│[0m > postinstall
2024-06-23T01:24:04.511663152Z [34m│[0m > nuxt prepare
2024-06-23T01:24:04.511666193Z [34m│[0m 
2024-06-23T01:24:05.432913282Z [34m│[0m [nuxt] modules:before: 0.141ms
2024-06-23T01:24:05.476512675Z [34m│[0m [nuxt] kit:compatibility: 10.402ms
2024-06-23T01:24:05.476696426Z [34m│[0m [nuxt] kit:compatibility�: 10.912ms
2024-06-23T01:24:05.476820287Z [34m│[0m [nuxt] kit:compatibility��: 11.078ms
2024-06-23T01:24:05.477225003Z [34m│[0m [nuxt] kit:compatibility���: 11.142ms
2024-06-23T01:24:05.477560021Z [34m│[0m [nuxt] kit:compatibility����: 11.325ms
2024-06-23T01:24:05.477921300Z [34m│[0m [nuxt] kit:compatibility�����: 11.648ms
2024-06-23T01:24:05.478596676Z [34m│[0m [nuxt] kit:compatibility������: 12.169ms
2024-06-23T01:24:05.479051959Z [34m│[0m [nuxt] kit:compatibility�������: 12.909ms
2024-06-23T01:24:05.479726418Z [34m│[0m [nuxt] kit:compatibility��������: 13.791ms
2024-06-23T01:24:05.480222500Z [34m│[0m [nuxt] kit:compatibility���������: 13.874ms
2024-06-23T01:24:05.480826802Z [34m│[0m [nuxt] kit:compatibility����������: 14.746ms
2024-06-23T01:24:05.481425602Z [34m│[0m [nuxt] kit:compatibility�����������: 14.86ms
2024-06-23T01:24:05.540111020Z [34m│[0m 
2024-06-23T01:24:05.540318973Z [34m│[0m  ERROR  Error while requiring module @nuxtjs/supabase: Error: Cannot find module '@nuxtjs/supabase'
2024-06-23T01:24:05.540329790Z [34m│[0m Require stack:
2024-06-23T01:24:05.540333463Z [34m│[0m - /workspace/index.js
2024-06-23T01:24:05.540335671Z [34m│[0m 
2024-06-23T01:24:05.541422119Z [34m│[0m 
2024-06-23T01:24:05.541581700Z [34m│[0m  ERROR  Cannot find module '@nuxtjs/supabase'
2024-06-23T01:24:05.541594972Z [34m│[0m Require stack:
2024-06-23T01:24:05.541598456Z [34m│[0m - /workspace/index.js
2024-06-23T01:24:05.541600497Z [34m│[0m 
2024-06-23T01:24:05.541602704Z [34m│[0m   Require stack:
2024-06-23T01:24:05.541604784Z [34m│[0m   - index.js
2024-06-23T01:24:05.541607208Z [34m│[0m   at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
2024-06-23T01:24:05.541609815Z [34m│[0m   at Function.resolve (node:internal/modules/helpers:190:19)
2024-06-23T01:24:05.541611736Z [34m│[0m   at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:241814)
2024-06-23T01:24:05.541616228Z [34m│[0m   at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2225:29)
2024-06-23T01:24:05.541618071Z [34m│[0m   at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2230:24)
2024-06-23T01:24:05.541620112Z [34m│[0m   at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2509:92)
2024-06-23T01:24:05.541621975Z [34m│[0m   at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2461:47)
2024-06-23T01:24:05.541623842Z [34m│[0m   at async initNuxt (node_modules/nuxt/dist/index.mjs:4395:5)
2024-06-23T01:24:05.541625712Z [34m│[0m   at async loadNuxt (node_modules/nuxt/dist/index.mjs:4525:5)
2024-06-23T01:24:05.541627571Z [34m│[0m   at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2651:19)
2024-06-23T01:24:05.541629544Z [34m│[0m   at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:56:18)
2024-06-23T01:24:05.541743052Z [34m│[0m   at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1648:16)
2024-06-23T01:24:05.541751346Z [34m│[0m   at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)
2024-06-23T01:24:05.541753812Z [34m│[0m   at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1777:7) 
2024-06-23T01:24:05.541755951Z [34m│[0m 
2024-06-23T01:24:05.541758020Z [34m│[0m 
2024-06-23T01:24:05.541985939Z [34m│[0m 
2024-06-23T01:24:05.542109052Z [34m│[0m  ERROR  Cannot find module '@nuxtjs/supabase'
2024-06-23T01:24:05.542115562Z [34m│[0m Require stack:
2024-06-23T01:24:05.542118239Z [34m│[0m - /workspace/index.js
2024-06-23T01:24:05.542120349Z [34m│[0m 
2024-06-23T01:24:05.552400253Z [34m│[0m npm notice
2024-06-23T01:24:05.552622680Z [34m│[0m npm notice New minor version of npm available! 10.7.0 -> 10.8.1
2024-06-23T01:24:05.552642241Z [34m│[0m npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
2024-06-23T01:24:05.552645488Z [34m│[0m npm notice To update run: npm install -g npm@10.8.1
2024-06-23T01:24:05.552647975Z [34m│[0m npm notice
2024-06-23T01:24:05.553851252Z [34m│[0m npm error code 1
2024-06-23T01:24:05.554084631Z [34m│[0m npm error path /workspace
2024-06-23T01:24:05.555167444Z [34m│[0m npm error command failed
2024-06-23T01:24:05.555309904Z [34m│[0m npm error command sh -c nuxt prepare
2024-06-23T01:24:05.556420704Z [34m│[0m 
2024-06-23T01:24:05.556607370Z [34m│[0m npm error A complete log of this run can be found in: /home/apps/.npm/_logs/2024-06-23T01_23_55_892Z-debug-0.log
2024-06-23T01:24:05.567066593Z [34m│[0m 
2024-06-23T01:24:05.567262121Z [34m│[0m unable to invoke layer creator
2024-06-23T01:24:05.567270210Z [34m│[0m installing node_modules: exit status 1
2024-06-23T01:24:05.567679452Z [34m│[0m [31;1mERROR: [0mfailed to build: exit status 1
2024-06-23T01:24:05.794100144Z [34m│[0m 
2024-06-23T01:24:05.797465230Z [34m│[0m 
2024-06-23T01:24:05.797680960Z [34m│[0m For documentation on the buildpacks used to build your app, please see:
2024-06-23T01:24:05.797713399Z [34m│[0m 
2024-06-23T01:24:05.797718570Z [34m│[0m    Node.js  v0.4.0  https://do.co/apps-buildpack-node
2024-06-23T01:24:05.798498458Z [34m│[0m 
2024-06-23T01:24:05.805406801Z [34m│[0m [31m ✘ build failed[0m
```

**Comment by GalacticHypernova** [comment]
Could you please share your project? It's difficult to check it without seeing your specific config

**Comment by nosizejosh** [comment]
Thanks @GalacticHypernova. 

[package.json](https://github.com/user-attachments/files/15942867/package.json)
[package-lock.json](https://github.com/user-attachments/files/15942868/package-lock.json)

I have shared my environment above as well. Will this be enough? if not, then which other part of the project so I need to share in order for you to be able to help?
I have shared my environment above as well

**Comment by GalacticHypernova** [comment]
What if you downgrade supabase to 1.2.0? That should solve it

**Comment by nosizejosh** [comment]
production deployment still failing, as expected. I do not think its really a supabase issue

**Comment by nosizejosh** [comment]
Now production build is failing even when I downgrade nuxt to 3.11.2. I have rolled back to previous commits but build is still failing

**Comment by GalacticHypernova** [comment]
If even earlier builds fail (assuming with the same message), that reduces the chance it's from nuxt.
Have you made sure it's installed?

**Comment by nosizejosh** [comment]
even though I have tried to vert to nuxt 3.11.2 and that shows in my package.json, 
env shows it still running 3.12.2

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.4.0
- Builder:          -
- User Config:      ssr, debug, runtimeConfig, devtools, modules, ui, css, app, supabase
- Runtime Modules:  @nuxtjs/supabase@1.2.2, @vueuse/nuxt@10.11.0, @pinia/nuxt@0.5.1, @nuxt/ui@2.17.0, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-icon@0.6.10, @nuxtjs/device@3.1.1
- Build Modules:    -
------------------------------

how do i force running of 3.11.2 which is the version that passed production build

**Comment by GalacticHypernova** [comment]
Make sure to reinstall nuxt (you can use nuxi upgrade --force)

**Comment by nosizejosh** [comment]
Update: tried to deploy with netlify and build passed. However, i have a 401.
Never used netflify so I am trying to figure that out. But build passing is a good sign for now.

**Comment by GalacticHypernova** [comment]
Glad I could help!

**Comment by thisisumlaut** [comment]
To add to this, the following [URL](https://docs.digitalocean.com/support/why-am-i-receiving-a-missing-module-error-when-building-my-node.js-app-on-app-platform/) provides a reason why this is now happening. DO App Platform now prunes devDependencies.

Adding `NPM_CONFIG_PRODUCTION=false` to app-level env variables resolves the issue.
