### ISSUE TITLE
In nuxt@3.12.0 the definePageMeta function is broken

### ISSUE THREAD

**Issue by alSergey** [nuxt/nuxt#28591]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.16.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.8.1`
- Builder:          `-`
- User Config:      `compatibilityDate`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`

### nuxt@3.11.2

[StackBlitz](https://stackblitz.com/edit/nuxt-3-11-2-define-page-meta-error?file=pages%2Findex.tsx)

### nuxt@3.12.0

[StackBlitz](https://stackblitz.com/edit/nuxt-3-12-0-define-page-meta-error?file=pages%2Findex.tsx)

### nuxt@3.11.2

When using the `definePageMeta` function, I was able to change the layout on the page. In the example below, the top text is with the `no-auth` layout, and the bottom text is with the `main` page. There is also a warning that `definePageMeta` can only be used on pages.

```
definePageMeta() is a compiler-hint helper that is only usable inside the script block of a single file component which is also a page. Its arguments should be compiled away and passing it at runtime has no effect.
```

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5ca8b716-e2a8-4e53-8589-94a786ea7545">

### nuxt@3.12.0

In nuxt@3.12.0 when using `definePageMeta` it is not possible to change layout and default is used. There is also a warning about using `definePageMeta`.

```
definePageMeta() is a compiler-hint helper that is only usable inside the script block of a single file component which is also a page. Its arguments should be compiled away and passing it at runtime has no effect.
```

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/2eeb488e-f197-42fa-b72b-e55416a0208a">

**Comment by alSergey** [comment]
There is a suspicion that the behavior may have changed in this [pull request](https://github.com/nuxt/nuxt/pull/27134).

**Comment by danielroe** [comment]
This should have been resolved in v3.12.4. Let me know if you continue to experience it once you upgrade.

**Comment by alSergey** [comment]
@danielroe Hi, the problem persists on nuxt@3.12.4. You can see it [here](https://stackblitz.com/edit/nuxt-3-12-0-define-page-meta-error?file=pages%2Findex.tsx). There should be text `No auth, No auth page`, but now `Auth, No auth page`. This is precisely because the definePageMeta function does not work.

**Comment by danielroe** [comment]
Oh, yes, there was an issue with JSX support that is also resolved and will be included in v3.13 (or in the latest nightly version).

**Comment by alSergey** [comment]
Checked the work on nuxt-nightly@3x, the error is gone. Thank you very much for your help, we will wait for the release.
