### ISSUE TITLE
Provided keys by a plugin are inferred with type `unknown`

### ISSUE THREAD

**Issue by OsamaHaikal** [nuxt/nuxt#28779]
### Environment

Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, future
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-6knne9?file=app%2Fcomposables%2FuseHello.ts

## Issue

NuxtApp injections are not inferred correctly

```ts<script setup lang="ts">
// alternatively, you can also use it here
const { $hello } = useNuxtApp()

// $hello: unknown
</script>
```

## Screenshots

![image](https://github.com/user-attachments/assets/7b682545-5179-47c6-a07d-76e7ce8728c8)

**Comment by gbyesiltas** [comment]
We are facing the same problem trying to upgrade to 3.13.0

**Comment by gaisinskii** [comment]
A similar issue was already raised https://github.com/nuxt/nuxt/issues/28693 I believe the fix is still to be released

**Comment by danielroe** [comment]
This is already resolved in the latest version of nuxt/devtools:

![CleanShot 2024-09-02 at 09 58 09@2x](https://github.com/user-attachments/assets/cd06dfaf-7d09-4bd3-82b3-2c894eca34d8)

A hotfix for libraries that haven't updated to the latest module-builder is due to be released in v3.13.1.

**Comment by OsamaHaikal** [comment]
Thank you

**Comment by gbyesiltas** [comment]
Hey @danielroe we still have this problem and I could reproduce it by adding the `@nuxt-alt/auth` module to the [repro project](https://stackblitz.com/edit/github-6knne9-jq8rf1?file=app%2Fplugins%2Fhello-object-syntax.ts,app%2Fcomposables%2FuseHello.ts,nuxt.config.ts,package.json) indeed
<img width="577" alt="Screenshot 2024-09-02 at 12 01 45" src="https://github.com/user-attachments/assets/8a06f6b9-3ec2-449b-9e4d-8cdae8cccb23">

I don't think they use `module-builder` but should we still expect this to be resolved with nuxt 3.13.1 or do you think I should open an issue on the module repo?

**Comment by danielroe** [comment]
Yes, you should open an issue upstream, but the next Nuxt patch should hotfix it for now.
