### ISSUE TITLE
ERROR  Cannot start nuxt:  Nuxt module should be a function: @nuxtjs/color-mode

### ISSUE THREAD

**Issue by Rednas83** [nuxt/nuxt#29779]
When starting the dev server with nuxt 3.14.0 I get
ERROR  Cannot start nuxt:  Nuxt module should be a function: @nuxtjs/color-mode 

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v22.11.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  normalizedModule(), normalizedModule(), @vueuse/nuxt@11.2.0, @nuxt/content@2.13.4, @nuxt/eslint@0.6.1, @nuxtjs/tailwindcss@6.12.2, @nuxt/devtools@1.6.0, shadcn-nuxt@0.11.2, nuxt-meilisearch@1.3.10, @nuxt/image@1.8.1, @formkit/nuxt@1.6.7, @nuxt/icon@1.6.1
- Build Modules:    -
------------------------------
```

**Comment by InvixGG** [comment]
I get the same thing

**Comment by InvixGG** [comment]
I get the same thing.

But then when you explicitly add @nuxtjs/color-mode. It becomes:
```plaintext
 ERROR  Cannot start nuxt:  Nuxt module should be a function: [object Object]                              11:08:26 PM

  at loadNuxtModuleInstance (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2459:11)
  at async installModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.0_@parcel+watcher@2.5.0_@types+node@22.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4.24_i2sa3goc3rkwa3dnmwfqcnr7qi/node_modules/nuxt/dist/index.mjs:4669:5)
  at async NuxtDevServer._load (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/dev2.mjs:1894:5)
  at async NuxtDevServer.load (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/dev2.mjs:1828:7)
  at async NuxtDevServer.init (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/dev2.mjs:1823:5)
  at async Object.run (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/dev-child.mjs:104:5)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)
```

Not sure if it has anything to do with shadcn-nuxt? As they did add auto install for the @nuxtjs/color-mode module.
![Image](https://github.com/user-attachments/assets/5f5eb438-b440-4c8d-8fba-cae187896d66)

**Comment by InvixGG** [comment]
I get the same thing.

But then when you explicitly add @nuxtjs/color-mode. It becomes:
```plaintext
 ERROR  Cannot start nuxt:  Nuxt module should be a function: [object Object]                              11:08:26 PM

  at loadNuxtModuleInstance (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2459:11)
  at async installModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.0_@parcel+watcher@2.5.0_@types+node@22.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4.24_i2sa3goc3rkwa3dnmwfqcnr7qi/node_modules/nuxt/dist/index.mjs:4669:5)
  at async NuxtDevServer._load (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/dev2.mjs:1894:5)
  at async NuxtDevServer.load (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/dev2.mjs:1828:7)
  at async NuxtDevServer.init (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/dev2.mjs:1823:5)
  at async Object.run (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/dev-child.mjs:104:5)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)
```

Not sure if it has anything to do with shadcn-nuxt? As they did add auto install for the @nuxtjs/color-mode module.
https://github.com/unovue/shadcn-vue/pull/737

**Comment by InvixGG** [comment]
I get the same thing.

Weirdly enough updating to version 3.14.0 is fine for me. But when I either update my shadcn-nuxt version from 0.10.4 to the newest 0.11.2 I get this error:
```
 ERROR  Nuxt module should be a function: @nuxtjs/color-mode                                                                                                                                                                           12:08:44 AM  

  at loadNuxtModuleInstance (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2459:11)
  at installModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2389:53)
  at setup (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/shadcn-nuxt@0.11.2_magicast@0.3.5_rollup@4.24.4/node_modules/shadcn-nuxt/dist/module.mjs:46:11)
  at async normalizedModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2397:95)
  at async initNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.0_@parcel+watcher@2.5.0_@types+node@22.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4.24_5j6blunq47cjlgzrfcttbmiv4i/node_modules/nuxt/dist/index.mjs:4669:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.0_@parcel+watcher@2.5.0_@types+node@22.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4.24_5j6blunq47cjlgzrfcttbmiv4i/node_modules/nuxt/dist/index.mjs:4839:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2626:19)
  at async Object.run (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)
```

Maybe something to do with this?
https://github.com/unovue/shadcn-vue/pull/737

And when I try and install @nuxt/rspack-builder I get this:
```
 ERROR  Nuxt module should be a function: [object Object]                                                                                                                                                                           12:07:04 AM  

  at loadNuxtModuleInstance (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2459:11)
  at async installModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.0_@parcel+watcher@2.5.0_@types+node@22.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4.24_i2sa3goc3rkwa3dnmwfqcnr7qi/node_modules/nuxt/dist/index.mjs:4669:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.0_@parcel+watcher@2.5.0_@types+node@22.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4.24_i2sa3goc3rkwa3dnmwfqcnr7qi/node_modules/nuxt/dist/index.mjs:4839:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.0_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2626:19)
  at async Object.run (/C:/Users/leviv/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (/C:/Users/leviv/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand (/C:/Users/leviv/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:2019:10)
  at async Object.setup (/C:/Users/leviv/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/add2.mjs:197:5)
  at async runCommand$1 (/C:/Users/leviv/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1620:5)
  at async runCommand$1 (/C:/Users/leviv/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runCommand$1 (/C:/Users/leviv/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (/C:/Users/leviv/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)
```

**Comment by InvixGG** [comment]
Maybe it is also the new shadcn-nuxt version who's causing issues in your codebase @Rednas83?

**Comment by Rednas83** [comment]
Thanks. Downgrading shadcn indeed fixed the issue for me
`"shadcn-nuxt": "^0.10.4",`

**Comment by milos018** [comment]
Seems to be connected with https://github.com/unovue/shadcn-vue/issues/864

**Comment by InvixGG** [comment]
I've installed the new Nuxt version 3.14.159. But this is still an issue when updating my shadcn-nuxt from 0.10.4 to 0.11.2:
```
ERROR  Nuxt module should be a function: @nuxtjs/color-mode                                                                                                                                                                            
  at loadNuxtModuleInstance (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2460:11)
  at async installModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async setup (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/shadcn-nuxt@0.11.2_magicast@0.3.5_rollup@4.24.4/node_modules/shadcn-nuxt/dist/module.mjs:46:5)
  at async normalizedModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2397:95)
  at async initNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4._dtd72bcuvnkmstgdtddzxizlvy/node_modules/nuxt/dist/index.mjs:4669:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4._dtd72bcuvnkmstgdtddzxizlvy/node_modules/nuxt/dist/index.mjs:4839:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxt/kit/dist/index.mjs:2627:19)
  at async Object.run (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)

**Comment by milos018** [comment]
It's true, I get the same error when upgrading to 3.14.159, however it's an easy fix
Make sure you install @nuxtjs/color-mode, this could be an issue with the shadcn packages, not nuxt

**Comment by InvixGG** [comment]
> It's true, I get the same error when upgrading to 3.14.159, however it's an easy fix Make sure you install @nuxtjs/color-mode, this could be an issue with the shadcn packages, not nuxt

Yea I just found that out as well. Indeed sounds like a shadcn issue.

**Comment by InvixGG** [comment]
Weird thing is, when I install "@nuxt/rspack-builder" I get this:
```
 ERROR  Nuxt module should be a function: [object Object]                                        

  at loadNuxtModuleInstance (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2460:11)
  at async installModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_magicast@0.3.5_rollup@4._yvk4y57n46krfngabiv4qthxtq/node_modules/nuxt/dist/index.mjs:4669:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_magicast@0.3.5_rollup@4._yvk4y57n46krfngabiv4qthxtq/node_modules/nuxt/dist/index.mjs:4839:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2627:19)
  at async Object.run (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:2019:10)
  at async Object.setup (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/add2.mjs:197:5)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1620:5)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)
```

**Comment by milos018** [comment]
Strange indeed, but should be another issue if you ask me.

**Comment by InvixGG** [comment]
> Strange indeed, but should be another issue if you ask me.

Yea I think so too, will be doing that.

**Comment by danielroe** [comment]
check the latest version because i think that issue is resolved

**Comment by rogadev** [comment]
IDK why this is closed. It's still an issue.

` ERROR  Cannot start nuxt:  Nuxt module should be a function: @nuxtjs/color-mode                                               11:54:43 a.m.  `

Reverting to old version fixes it.

**Comment by danielroe** [comment]
@rogadev then please provide a reproduction 🙏

**Comment by roremdev** [comment]
@danielroe 
I've tried to run the command: `bunx nuxi@latest module add shadcn-nuxt`, then the resulting fallout into an error:

```
 ERROR  Nuxt module should be a function: @nuxtjs/color-mode                                                                                  

  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2460:11)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async setup (node_modules/shadcn-nuxt/dist/module.mjs:46:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2397:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4669:5)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:4839:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2627:19)
  at async Object.run (/private/tmp/bunx-501-nuxi@latest/node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (/private/tmp/bunx-501-nuxi@latest/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand (/private/tmp/bunx-501-nuxi@latest/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:2019:10)
  at async Object.setup (/private/tmp/bunx-501-nuxi@latest/node_modules/nuxi/dist/chunks/add2.mjs:197:5)
  at async runCommand$1 (/private/tmp/bunx-501-nuxi@latest/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1620:5)
  at async runCommand$1 (/private/tmp/bunx-501-nuxi@latest/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runCommand$1 (/private/tmp/bunx-501-nuxi@latest/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (/private/tmp/bunx-501-nuxi@latest/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)
```
Even when I omit the module addition, when I complete the initialize of the CLI the error appears with the command: `bunx shadcn-vue@latest init`:

```
bunx shadcn-vue@latest init
✔ Would you like to use TypeScript? (recommended)? … no / yes
✔ Which framework are you using? › Nuxt
✔ Which style would you like to use? › New York
✔ Which color would you like to use as base color? › Zinc
✔ Where is your tsconfig.json file? … .nuxt/tsconfig.json
✔ Where is your global CSS file? (this file will be overwritten) … src/assets/main.css
✔ Would you like to use CSS variables for colors? … no / yes
✔ Are you using a custom tailwind prefix eg. tw-? (Leave blank if not) …
✔ Where is your tailwind.config located? (this file will be overwritten) … tailwind.config.ts
✔ Configure the import alias for components: … @/components
✔ Configure the import alias for utils: … @/utils
✔ Write configuration to components.json. Proceed? … yes
                                                                                                                                              
✔ Writing components.json...
⠋ Initializing project...                                                                                                                                              
ℹ Detected a Nuxt project with 'shadcn-nuxt' v0.11.2...                                                                                      
✔ Initializing project...
⠦ Installing dependencies...
 ERROR  Command failed with exit code 1: bun add tailwindcss-animate class-variance-authority clsx tailwind-merge radix-vue @radix-icons/vue  2:31:58 PM
Resolving dependencies
Resolved, downloaded and extracted [23]
Saved lockfile

$ nuxt prepare

 ERROR  Nuxt module should be a function: @nuxtjs/color-mode

  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2460:11)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async setup (node_modules/shadcn-nuxt/dist/module.mjs:46:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2397:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4669:5)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:4839:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2627:19)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)



 ERROR  Nuxt module should be a function: @nuxtjs/color-mode

error: postinstall script from "" exited with 1
bun add v1.1.34 (5e5e7c60)
[nuxt:tailwindcss] ℹ Using default Tailwind CSS file
```

> [!NOTE]
> The dependency detected is `shadcn-nuxt@0.11.2`

**Comment by danielroe** [comment]
This is probably caused by bun hoisting an older version of nuxt/kit, though I can't say for sure without a repro.

**Comment by timbenniks** [comment]
This is similar but with a local module: https://github.com/nuxt/nuxt/issues/29848

**Comment by cuervolu** [comment]
> This is probably caused by bun hoisting an older version of nuxt/kit, though I can't say for sure without a repro.

Hey @danielroe , I know the issue is closed, but I'm still experiencing the problem. Will this [repo](https://github.com/cuervolu/shadcn-vue-error) help reproduce the error? It's literally a newly created Nuxt project

**Comment by GurovDmitriy** [comment]
Locally everything works, but in ci npm error

[nuxt-module-playground](https://github.com/GurovDmitriy/nuxt-module-playground)

Run npm ci
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v[4](https://github.com/GurovDmitriy/nuxt-module-playground/actions/runs/11765193334/job/32771230635#step:5:5) are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated eslint@8.[5](https://github.com/GurovDmitriy/nuxt-module-playground/actions/runs/11765193334/job/32771230635#step:5:6)7.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm error code 1
npm error path /home/runner/work/nuxt-module-playground/nuxt-module-playground/packages/todo-landing
npm error command failed
npm error command sh -c nuxt prepare
Error: npm error [error] Nuxt module should be a function: @todo/todo-module
npm error   at loadNuxtModuleInstance (/home/runner/work/nuxt-module-playground/nuxt-module-playground/node_modules/@nuxt/kit/dist/index.mjs:24[6](https://github.com/GurovDmitriy/nuxt-module-playground/actions/runs/11765193334/job/32771230635#step:5:7)0:11)
npm error   at async installModule (/home/runner/work/nuxt-module-playground/nuxt-module-playground/node_modules/@nuxt/kit/dist/index.mjs:2389:4[7](https://github.com/GurovDmitriy/nuxt-module-playground/actions/runs/11765193334/job/32771230635#step:5:8))
npm error   at async initNuxt (/home/runner/work/nuxt-module-playground/nuxt-module-playground/node_modules/nuxt/dist/index.mjs:4669:5)
npm error   at async loadNuxt (/home/runner/work/nuxt-module-playground/nuxt-module-playground/node_modules/nuxt/dist/index.mjs:4[8](https://github.com/GurovDmitriy/nuxt-module-playground/actions/runs/11765193334/job/32771230635#step:5:9)39:5)
npm error   at async loadNuxt (/home/runner/work/nuxt-module-playground/nuxt-module-playground/node_modules/@nuxt/kit/dist/index.mjs:2627:1[9](https://github.com/GurovDmitriy/nuxt-module-playground/actions/runs/11765193334/job/32771230635#step:5:10))
npm error   at async Object.run (/home/runner/work/nuxt-module-playground/nuxt-module-playground/node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
npm error   at async runCommand$1 (/home/runner/work/nuxt-module-playground/nuxt-module-playground/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
npm error   at async runCommand$1 (/home/runner/work/nuxt-module-playground/nuxt-module-playground/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
npm error   at async runMain$1 (/home/runner/work/nuxt-module-playground/nuxt-module-playground/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7) 
npm error
Error: npm error [error] Nuxt module should be a function: @todo/todo-module
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-11-[10](https://github.com/GurovDmitriy/nuxt-module-playground/actions/runs/11765193334/job/32771230635#step:5:11)T12_38_14_131Z-debug-0.log
Error: Process completed with exit code 1.

**Comment by kusman28** [comment]
npm install @nuxtjs/color-mode

**Comment by GurovDmitriy** [comment]
I simulated running locally and got the same error when I deleted all the output and nuxt generated directories.

so that everything works first npm i in the module folder, then dev:prepare in the module folder, then build in the module folder, then npm i in the root folder of the monorepository and everything works.

**Comment by mohamedmhiri** [comment]
**@nuxtjs/color-mode** needs to be installed manually with the  **shadcn-nuxt** package like this: `npx nuxi@latest module add @nuxtjs/color-mode shadcn-nuxt`

**Comment by darioferderber** [comment]
I ran out into the same problem and I fixed it by removing the `/` at the end of the `dir.public` in `nuxt.config`.
```js
// nuxt.config.ts
// before
dir: {
  public: '../resources/'
}

// after
dir: {
  public: '../resources'
}
```

I'm not sure if this will help, but it helped me so I'll just leave this here. Good luck

**Comment by fahhadalsubaie** [comment]
> npm install @nuxtjs/color-mode

this solved it for me.

**Comment by antoniuspj** [comment]
> npm install @nuxtjs/color-mode

finally, thanks for the suggestion

**Comment by husayt** [comment]
This error is often misleading, I also get `Nuxt module should be a function: @nuxt/devtools ` and for other modules as well. Sometime update --force fixes it, sometimes not. Often this error hides another one. @danielroe is it also possible to display root cause?

**Comment by danielroe** [comment]
Yes, this error message needs to be improved.

**Comment by rogadev** [comment]
This hasn't been fixed...

```bash
 ERROR  Cannot start nuxt:  Nuxt module should be a function: @nuxtjs/color-mode                                                       6:26:04 p.m.  

  at loadNuxtModuleInstance (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/@nuxt/kit/dist/index.mjs:2466:11)
  at async installModule (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async setup (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/shadcn-nuxt/dist/module.mjs:46:5)
  at async normalizedModule (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/@nuxt/kit/dist/index.mjs:2397:95)
  at async initNuxt (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/nuxt/dist/index.mjs:4684:5)
  at async NuxtDevServer._load (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/nuxi/dist/chunks/dev2.mjs:1894:5)
  at async NuxtDevServer.load (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/nuxi/dist/chunks/dev2.mjs:1828:7)
  at async NuxtDevServer.init (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/nuxi/dist/chunks/dev2.mjs:1823:5)
  at async Object.run (/C:/Users/ryanr/Documents/dev/ezeval.app/node_modules/nuxi/dist/chunks/dev-child.mjs:104:5)
```

If I revert to 0.10.4 it's fine.
```json
    "shadcn-nuxt": "^0.10.4",
```

**Comment by rogadev** [comment]
Reproduction.
https://stackblitz.com/edit/github-bbdmxt?file=nuxt.config.ts

**Comment by danielroe** [comment]
See https://github.com/unovue/shadcn-vue/issues/945#issuecomment-2523235188.
