### ISSUE TITLE
Dart Sass 2.0.0 Deprecation Warning

### ISSUE THREAD

**Issue by drusellers** [nuxt/nuxt#30007]
### Environment

```
❯ npx nuxi info
Working directory: /Users/drusellers/dev/drusellers/learning/NuxtScss                                                                                                    6:55:28 AM
Nuxt project info: (copied to clipboard)                                                                                                                                 6:55:28 AM

------------------------------
- Operating System: Darwin
- Node Version:     v20.16.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

                                                                                                                                                                         6:55:28 AM
👉 Report an issue: https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com
```

### Reproduction

```
npx nuxi@latest init NuxtScss
cd NuxtScss
npm i sass
mkdir assets && touch assets/index.scss
```

Edit nuxt.config.ts to look like
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  css: [ '~/assets/index.scss' ]
})
```

The run `npm run build` you should see a Deprecation warning in the console output. A full log run is provided below.

### Describe the bug

The issue is that the API that Nuxt appears to be using by default to load Sass/Scss is to be retired. and after searching the issues and discussions I haven't seen any mention of this and so was curious if Nuxt has plans to fix it or not.

```
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
```

### Logs

```shell-script
npm run build

> build
> nuxt build

Nuxt 3.14.1592 with Nitro 2.10.4                                                                                                                                         6:58:23 AM
ℹ Building client...                                                                                                                                                    6:58:24 AM
ℹ vite v5.4.11 building for production...                                                                                                                               6:58:24 AM
transforming (1) node_modules/nuxt/dist/app/entry.jsDeprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

ℹ ✓ 134 modules transformed.                                                                                                                                            6:58:25 AM
ℹ .nuxt/dist/client/manifest.json                   1.06 kB │ gzip:  0.29 kB                                                                                            6:58:25 AM
ℹ .nuxt/dist/client/_nuxt/error-500.D6506J9O.css    1.88 kB │ gzip:  0.72 kB                                                                                            6:58:25 AM
ℹ .nuxt/dist/client/_nuxt/error-404.CoZKRZXM.css    3.56 kB │ gzip:  1.10 kB                                                                                            6:58:25 AM
ℹ .nuxt/dist/client/_nuxt/entry.Dhfs5r89.css       12.41 kB │ gzip:  2.57 kB                                                                                            6:58:25 AM
ℹ .nuxt/dist/client/_nuxt/CaZCQHx-.js               3.39 kB │ gzip:  1.53 kB                                                                                            6:58:25 AM
ℹ .nuxt/dist/client/_nuxt/Dinan-YS.js               9.31 kB │ gzip:  3.74 kB                                                                                            6:58:25 AM
ℹ .nuxt/dist/client/_nuxt/CxRuTHMJ.js             219.37 kB │ gzip: 62.71 kB                                                                                            6:58:25 AM
ℹ ✓ built in 600ms                                                                                                                                                      6:58:25 AM
✔ Client built in 605ms                                                                                                                                                 6:58:25 AM
ℹ Building server...                                                                                                                                                    6:58:25 AM
ℹ vite v5.4.11 building SSR bundle for production...                                                                                                                    6:58:25 AM
transforming (2) node_modules/nuxt/dist/app/entry.jsDeprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

ℹ ✓ 50 modules transformed.                                                                                                                                             6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/welcome-styles.BnaSUkR4.mjs           0.08 kB                                                                                                 6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/error-404-styles.DRLC0U6S.mjs         0.08 kB                                                                                                 6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/error-500-styles.DqmriZ_b.mjs         0.08 kB                                                                                                 6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/entry-styles.BdhOd56W.mjs             0.15 kB                                                                                                 6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/welcome-styles.DLHuNznc.mjs           0.15 kB                                                                                                 6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/error-404-styles.BcoFjqgl.mjs         0.15 kB                                                                                                 6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/error-500-styles.DPP87-Dp.mjs         0.15 kB                                                                                                 6:58:25 AM
ℹ .nuxt/dist/server/styles.mjs                                  1.11 kB                                                                                                 6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-Dvj5b8CJ.js        0.11 kB │ map:   0.11 kB                                                                                6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-DiWYPNRc.js    2.10 kB │ map:   0.12 kB                                                                                6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-D8Sw_W7I.js    3.80 kB │ map:   0.12 kB                                                                                6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/error-500-DBmARhSQ.js                 4.54 kB │ map:   5.35 kB                                                                                6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/entry-styles-2.mjs-qoWoZyO1.js       12.67 kB │ map:   0.11 kB                                                                                6:58:25 AM
ℹ .nuxt/dist/server/_nuxt/error-404-CrStZ1l5.js                15.45 kB │ map:  28.66 kB                                                                                6:58:25 AM
ℹ .nuxt/dist/server/server.mjs                                124.49 kB │ map: 181.25 kB                                                                                6:58:25 AM
ℹ ✓ built in 224ms                                                                                                                                                      6:58:25 AM
✔ Server built in 226ms                                                                                                                                                 6:58:25 AM
✔ Generated public .output/public                                                                                                                                 nitro 6:58:25 AM
ℹ Building Nuxt Nitro server (preset: node-server, compatibility date: 2024-10-24)                                                                                nitro 6:58:25 AM
✔ Nuxt Nitro server built                                                                                                                                         nitro 6:58:26 AM
  ├─ .output/server/chunks/_/error-500.mjs (4.77 kB) (2.02 kB gzip)
  ├─ .output/server/chunks/_/error-500.mjs.map (190 B) (157 B gzip)
  ├─ .output/server/chunks/build/client.manifest.mjs (1.79 kB) (431 B gzip)
  ├─ .output/server/chunks/build/client.manifest.mjs.map (1.54 kB) (365 B gzip)
  ├─ .output/server/chunks/build/entry-styles-2.mjs-qoWoZyO1.mjs (12.7 kB) (2.67 kB gzip)
  ├─ .output/server/chunks/build/entry-styles-2.mjs-qoWoZyO1.mjs.map (118 B) (119 B gzip)
  ├─ .output/server/chunks/build/entry-styles.BdhOd56W.mjs (325 B) (212 B gzip)
  ├─ .output/server/chunks/build/entry-styles.BdhOd56W.mjs.map (231 B) (179 B gzip)
  ├─ .output/server/chunks/build/error-404-CrStZ1l5.mjs (15.7 kB) (4.74 kB gzip)
  ├─ .output/server/chunks/build/error-404-CrStZ1l5.mjs.map (338 B) (197 B gzip)
  ├─ .output/server/chunks/build/error-404-styles-1.mjs-D8Sw_W7I.mjs (3.79 kB) (1.22 kB gzip)
  ├─ .output/server/chunks/build/error-404-styles-1.mjs-D8Sw_W7I.mjs.map (122 B) (125 B gzip)
  ├─ .output/server/chunks/build/error-404-styles.BcoFjqgl.mjs (373 B) (209 B gzip)
  ├─ .output/server/chunks/build/error-404-styles.BcoFjqgl.mjs.map (238 B) (177 B gzip)
  ├─ .output/server/chunks/build/error-404-styles.DRLC0U6S.mjs (315 B) (205 B gzip)
  ├─ .output/server/chunks/build/error-404-styles.DRLC0U6S.mjs.map (216 B) (168 B gzip)
  ├─ .output/server/chunks/build/error-500-DBmARhSQ.mjs (4.64 kB) (1.92 kB gzip)
  ├─ .output/server/chunks/build/error-500-DBmARhSQ.mjs.map (196 B) (167 B gzip)
  ├─ .output/server/chunks/build/error-500-styles-1.mjs-DiWYPNRc.mjs (2.09 kB) (836 B gzip)
  ├─ .output/server/chunks/build/error-500-styles-1.mjs-DiWYPNRc.mjs.map (122 B) (124 B gzip)
  ├─ .output/server/chunks/build/error-500-styles.DPP87-Dp.mjs (371 B) (210 B gzip)
  ├─ .output/server/chunks/build/error-500-styles.DPP87-Dp.mjs.map (238 B) (178 B gzip)
  ├─ .output/server/chunks/build/error-500-styles.DqmriZ_b.mjs (315 B) (204 B gzip)
  ├─ .output/server/chunks/build/error-500-styles.DqmriZ_b.mjs.map (216 B) (165 B gzip)
  ├─ .output/server/chunks/build/server.mjs (124 kB) (23.2 kB gzip)
  ├─ .output/server/chunks/build/server.mjs.map (2.17 kB) (561 B gzip)
  ├─ .output/server/chunks/build/styles.mjs (1.14 kB) (377 B gzip)
  ├─ .output/server/chunks/build/styles.mjs.map (699 B) (251 B gzip)
  ├─ .output/server/chunks/build/welcome-styles.BnaSUkR4.mjs (305 B) (201 B gzip)
  ├─ .output/server/chunks/build/welcome-styles.BnaSUkR4.mjs.map (212 B) (165 B gzip)
  ├─ .output/server/chunks/build/welcome-styles.DLHuNznc.mjs (362 B) (207 B gzip)
  ├─ .output/server/chunks/build/welcome-styles.DLHuNznc.mjs.map (234 B) (177 B gzip)
  ├─ .output/server/chunks/nitro/nitro.mjs (175 kB) (42.5 kB gzip)
  ├─ .output/server/chunks/nitro/nitro.mjs.map (3.38 kB) (822 B gzip)
  ├─ .output/server/chunks/routes/renderer.mjs (13.2 kB) (4.24 kB gzip)
  ├─ .output/server/chunks/routes/renderer.mjs.map (359 B) (213 B gzip)
  ├─ .output/server/chunks/virtual/_virtual_spa-template.mjs (94 B) (100 B gzip)
  ├─ .output/server/chunks/virtual/_virtual_spa-template.mjs.map (112 B) (111 B gzip)
  ├─ .output/server/index.mjs (287 B) (189 B gzip)
  └─ .output/server/package.json (599 B) (292 B gzip)
Σ Total size: 1.8 MB (431 kB gzip)
✔ You can preview this build using node .output/server/index.mjs
```

**Comment by drusellers** [comment]
That removes the error and hopefully if that is telling vite to use the new "modern" api https://sass-lang.com/documentation/breaking-changes/legacy-js-api/ - then that's a double win! Hopefully it can become the default.

**Comment by franklin-tina** [comment]
@drusellers 
[Vite also recommends ](https://vite.dev/config/shared-options.html#css-preprocessoroptions:~:text=For%20the%20best%20performance%2C%20it%27s%20recommended%20to%20use%20api%3A%20%22modern%2Dcompiler%22%20with%20sass%2Dembedded%20package.)you use `sass-embedded` (maintained by the same dart-sass team) for better performance

**Comment by SwenenzY** [comment]
vite

    css: {
      preprocessorOptions: {
        scss: {
          quietDeps: true,
          api: 'modern-compiler', // or 'modern'
        },
      },
    },
not working

**Comment by danielroe** [comment]
This should be resolved with the next Nuxt release (with Vite v6)

**Comment by letuananh1873** [comment]
I tried upgrade with version 3.15.0 (vite6) but still show message
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

(Changed from 2.0.0 to 3.0.0)

**Comment by TheAlexLichter** [comment]
@jhonyjss Repro + new issue would be the easiest. Do you have a custom sass config?

**Comment by TheAlexLichter** [comment]
@jiangmaniu This is no reproduction.

 Please post a **new issue** with a reproduction (StackBlitz, GitHub repo) and the latest nuxt version ☺️
