### ISSUE TITLE
HRM does not work when using jsx/tsx

### ISSUE THREAD

**Issue by hdy1023** [nuxt/nuxt#30709]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.15.2
- CLI Version:      3.20.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.15.0
- Builder:          -
- User Config:      compatibilityDate, ssr, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-gnqfdasj?file=pages%2Fpage1.vue

### Describe the bug

1.HRM does not work when using jsx/tsx.
2.HRM is working when not using jsx/tsx.
3.The same problem occurs at Nuxt@3.14.1592, and the browser console will report an error  when useing jsx/tsx.

![Image](https://github.com/user-attachments/assets/8c36c7ae-fa83-439b-b654-574c909f43d3)

### Logs

```shell-script

```

**Comment by Suniron** [comment]
I got the following error in the UI when the HMR crash:

![Image](https://github.com/user-attachments/assets/29bd5a54-48cb-44dc-a7bd-fb4d54730b03)

Also, in the terminal, I got this message:

```
│   [cause]: Connect Timeout Error (attempted address: npm.antfu.dev:443, timeout: 10000ms)
│ 
│       at onConnectTimeout (node:internal/deps/undici/undici:2599:28)
│       at Immediate._onImmediate (node:internal/deps/undici/undici:2583:11)
│       at process.processImmediate (node:internal/timers:491:21)
```

![Image](https://github.com/user-attachments/assets/6656dc88-c2fa-4ad5-88d7-7a554ae7af27)

**Comment by danielroe** [comment]
@Suniron  that is already resolved - it’ll be included in the next nuxt patch release

**Comment by yschroe** [comment]
Still broken in v4.5.0
https://stackblitz.com/edit/github-gnqfdasj-tnw1yofe?file=app%2Fpages%2Fpage1.vue
