### ISSUE TITLE
mismatching versions of `ohash` lead to hydration failures

### ISSUE THREAD

**Issue by bozicstefan** [nuxt/nuxt#31355]
### Environment

- Operating System: `Linux`
- Node Version:     `v22.11.0`
- Nuxt Version:     `3.16.0`
- CLI Version:      `3.23.0`
- Nitro Version:    `2.11.6`
- Package Manager:  `npm@11.0.0`
- Builder:          `-`
- User Config:      `vite`, `delayHydration`, `seo`, `site`, `sitemap`, `robots`, `schemaOrg`, `image`, `experimental`, `build`, `compatibilityDate`, `devtools`, `nitro`, `routeRules`, `turnstile`, `runtimeConfig`, `modules`, `app`, `css`, `postcss`
- Runtime Modules:  `@bootstrap-vue-next/nuxt@0.28.0`, `vue3-carousel-nuxt@1.1.5`, `@nuxtjs/turnstile@0.9.15`, `@nuxtjs/seo@3.0.0-beta.3`, `@vueuse/nuxt@12.8.2`, `@nuxt/scripts@0.11.2`, `@nuxt/image@1.9.0`, `nuxt-delay-hydration@1.3.8`
- Build Modules:    `-`

### Reproduction

After upgrading Nuxt to v3.16 and used dependencies to latest versions:
- when previewing build either with 'npx nuxi preview' or  'node .output/server/index.mjs' my app displays 404 page. WHen redirecting from 404 page to home, the app works as intended, but as soon as browser is refreshed it's 404 page again.

 There are no errors reported, except for some hydration mismatch

### Additional context

I tried with removing all the modules but the error and bug persist. 

### Logs

```shell-script

-  server logs the following:

Listening on http://[::]:3000
[nitro-runtime] request: 0.538ms
[nitro-runtime] site-config:init: 0.027ms
[nitro-runtime] render:before: 0.021ms
[Vue Router warn]: No match found for location with path "/_nuxt/"
[Vue Router warn]: No match found for location with path "/_nuxt/"
[nuxt-app] page:loading:start: 0.036ms
[nuxt-app] app:created: 3.05ms
[nuxt-app] vue:setup: 0.046ms
[nuxt-app] app:rendered: 0.813ms
[nitro-runtime] error: 0.714ms
[nitro-runtime] request: 0.14ms
[nitro-runtime] site-config:init: 0.066ms
[nitro-runtime] render:before: 0.023ms

```

I have no idea what might be causing this behavior, since everything worked perfectly in v3.15.4.

**Comment by bozicstefan** [comment]
Having added new useful option in nuxt.config 'debug:true', I was able to dig a little deeper into this issue.

Now there are plenty of console logs and I found this one:

vue:error
[nuxt-app] vue:error: 0.287109375 ms
0: TypeError: Cannot read properties of null (reading 'items') at setup (http://localhost:3000/_nuxt/DG9wkyKX.js:1:917)
1: Proxy(Object) {_: {…}}
2: "https://vuejs.org/error-reference/#runtime-0"

The file log refers to at index 0, named 'DG9wkyKX.js' is build artefact that I see in .output/public/_nuxt, and is in a correspondingly messy format...

**Comment by agracia-foticos** [comment]
same issue, in dev works fine, but in prod build fails

**Comment by 4KDA** [comment]
Same problem. On the page in setup useFetch is used. We get the data successfully, but then something happens to its structure. Because of which we get an error.

**Comment by bozicstefan** [comment]
> same issue, in dev works fine, but in prod build fails

Would you please check out my environment in case we have some common settings aside from nuxt 3.16?

**Comment by bozicstefan** [comment]
> Same problem. On the page in setup useFetch is used. We get the data successfully, but then something happens to its structure. Because of which we get an error.

Would you please check out my environment in case we have some common settings aside from nuxt 3.16?

**Comment by agracia-foticos** [comment]
> > same issue, in dev works fine, but in prod build fails
> 
> Would you please check out my environment in case we have some common settings aside from nuxt 3.16?

Where is your environment? @bozicstefan

**Comment by bozicstefan** [comment]
> > > same issue, in dev works fine, but in prod build fails
> > 
> > 
> > Would you please check out my environment in case we have some common settings aside from nuxt 3.16?
> 
> Where is your environment? [@bozicstefan](https://github.com/bozicstefan)

Please, take a look at the top of the post. 
It was derived with 'npx nuxi info'

**Comment by bozicstefan** [comment]
> // Works prod and dev
> const { data } = await useAsyncData(
>   'featured-cars',
>   () => $fetch(url + '/api/public/featured-cars', {
>     method: 'GET',
>     params: {
>       customerSegment: 'B2B',
>       vehicleCategory: 'used_cars',
>       vehicleType: 'van',
>       publicId: 'pca00itcvnx2aiv',
>     },
>   }),
> ) 
> 
> // Works in dev but not in prod (causes hydration issue)
> const { data } = await useFetch(url + '/api/public/featured-cars', {
>   method: 'GET',
>   params: {
>     customerSegment: 'B2B',
>     vehicleCategory: 'used_cars',
>     vehicleType: 'van',
>     publicId: 'pca00itcvnx2aiv',
>   },
> })

Thanks for pointing out to this one!
I refactored several useFetch funcs on my index page and prod build seems to be running the way it's supposed to.

**Comment by dulnan** [comment]
Same issue here. The problem seems to be that the way the key is generated for the payload is broken: On a page that uses `useFetch`, I can see that instead of loading the response from payload on hydration it performs a new request. And indeed, the key that is calculated on the client side does not match the key that has been calculated on the server side, which leads to making the request again.

It seems to work when manually defining a key in useFetch like this:

```ts
const { data } = await useFetch('/api/foobar', {
  key: 'define-custom-key',
})
```

**Comment by bozicstefan** [comment]
> Same issue here. The problem seems to be that the way the key is generated for the payload is broken: On a page that uses `useFetch`, I can see that instead of loading the response from payload on hydration it performs a new request. And indeed, the key that is calculated on the client side does not match the key that has been calculated on the server side, which leads to making the request again.
> 
> It seems to work when manually defining a key in useFetch like this:
> 
> const { data } = await useFetch('/api/foobar', {
>   key: 'define-custom-key',
> })

Thanks for sharing your experience

**Comment by maximepvrt** [comment]
@danielroe I feel like this is a major regression.

**Comment by danielroe** [comment]
It is indeed a major issue, and it is due to mismatching versions of `ohash` in projects.

until resolved in Nuxt, you can likely work around by upgrading any dependencies that are hoisting an old version of ohash into the top level of your project.

**Comment by marioklassen** [comment]
I have the same issue. In the meantime I fixed it by add this to the package.json:
```
"overrides": {
    "ohash": "2.0.11"
}
```
And then a fresh install: `rm -rf node_modules package-lock.json && npm install`

**Comment by bozicstefan** [comment]
> I have the same issue. In the meantime I fixed it by add this to the package.json:
> 
> ```
> "overrides": {
>     "ohash": "2.0.11"
> }
> ```
> 
> And then a fresh install: `rm -rf node_modules package-lock.json && npm install`

It doesn't work for me, unfortunately:

Even after updating to latest patch v3.16.1 errors persist, although error trace is somewhat different:

[request error] [unhandled] [GET] http://localhost:3000/services/test-service

 
ℹ Error: Cannot convert undefined or null to object

 ⁃ at sanitizeObject (node_modules/unhead/dist/shared/unhead.DQc16pHI.mjs:68:36)

   63 ┃    const updated = key.replace(/([A-Z])/g, "-$1").toLowerCase();
   64 ┃    const prefixIndex = updated.indexOf("-");
   65 ┃    return prefixIndex === -1 ? updated : NAMESPACES.META.has(updated.slice(0, prefixIndex)) || NAMESPACES.OG.has(updated.slice(0, prefixIndex)) ? key.replace(/([A-Z])/g, ":$1").toLowerCase() : updated;
   66 ┃  }
   67 ┃  function sanitizeObject(input) {
 ❯ 68 ┃    return Object.fromEntries(Object.entries(input).filter(([k, v]) => String(v) !== "false" && k));
   69 ┃  }
   70 ┃  function transformObject(obj) {
   71 ┃    return Array.isArray(obj) ? obj.map(transformObject) : !obj || typeof obj !== "object" ? obj : Object.fromEntries(Object.entries(obj).map(([k, v]) => [fixKeyCase(k), transformObject(v)]));
   72 ┃  }
   73 ┃  function unpackToString(value, options = {}) {

 ⁃ at handleObjectEntry (node_modules/unhead/dist/shared/unhead.DQc16pHI.mjs:86:26)
 ⁃ at unpackMeta (node_modules/unhead/dist/shared/unhead.DQc16pHI.mjs:143:77)
 ⁃ (node_modules/unhead/dist/shared/unhead.CApf5sj3.mjs:16:24)
 ⁃ at entries:normalize (node_modules/unhead/dist/shared/unhead.CApf5sj3.mjs:12:27)
 ⁃ (node_modules/hookable/dist/index.mjs:48:66)
 ⁃ (node_modules/hookable/dist/index.mjs:48:56)
 ⁃ at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

[CAUSE]
TypeError {
  stack: 'Cannot convert undefined or null to object\n' +
  'at sanitizeObject (./node_modules/unhead/dist/shared/unhead.DQc16pHI.mjs:68:36)\n' +
  'at handleObjectEntry (./node_modules/unhead/dist/shared/unhead.DQc16pHI.mjs:86:26)\n' +
  'at unpackMeta (./node_modules/unhead/dist/shared/unhead.DQc16pHI.mjs:143:77)\n' +
  'at ./node_modules/unhead/dist/shared/unhead.CApf5sj3.mjs:16:24)\n' +
  'at entries:normalize (./node_modules/unhead/dist/shared/unhead.CApf5sj3.mjs:12:27)\n' +
  'at ./node_modules/hookable/dist/index.mjs:48:66)\n' +
  'at ./node_modules/hookable/dist/index.mjs:48:56)\n' +
  '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)',
  message: 'Cannot convert undefined or null to object',
}

**Comment by danielroe** [comment]
@bozicstefan  that seems like a different issue. can you reproduce?

**Comment by maximepvrt** [comment]
Perfect for me @danielroe

**Comment by bozicstefan** [comment]
> [@bozicstefan](https://github.com/bozicstefan) that seems like a different issue. can you reproduce?

Sorry, not succeeding in  reproduction, but in short words here's what's happening:

Both in dev and prod:

- when you hit '/services/some-service' route from navigating inside the app, you get the data requested and everything gets rendered without problems.

- When you refresh the same page, or when you navigate browser to the exact path of '/services/some-service'

What I find strange is that there are absolutely no such problems with route  '/services/some-service/related-service' which renders as supposed to...
