### ISSUE TITLE
aliases not working in layers

### ISSUE THREAD

**Issue by fabianwohlfart** [nuxt/nuxt#32036]
### Environment

(stackblitz)

------------------------------
- Operating System: Linux
- Node Version:     v20.19.1
- Nuxt Version:     3.17.2
- CLI Version:      3.25.0
- Nitro Version:    2.11.11
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-cczohr3c-2xhz6lkt?file=layers%2Ftest%2Fserver%2Fapi%2Ftest-layer.get.js&issueNumber=32034&issueRepo=nuxt/nuxt

### Describe the bug

running /api/test-server imports the do-something function.
running /api/test-layer fails to import the function due to alias @ is not available. (?!)

server/utils auto importing are also not working if inside a layer

### Logs

```shell-script

```

**Comment by danielroe** [comment]
`@` and `~` alias within a layer are resolved to that layer's `srcDir`

**Comment by fabianwohlfart** [comment]
unfortunately also a custom alias does not resolve correctly

```
  alias: {
    '@helper': fileURLToPath(new URL('./helper', import.meta.url)),
  },
```

```
Cannot find package '@helper/do-something.js' imported from /home/projects/github-cczohr3c-2xhz6lkt/layers/test/server/api/test-layer.get.js
```

the problem is like in the other issue i opened that the api file has no .ts extension
https://github.com/nuxt/nuxt/issues/32034
