### ISSUE TITLE
Incorrect component style order

### ISSUE THREAD

**Issue by cernymatej** [nuxt/nuxt#33041]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.17.0`
- Nuxt Version:     `4.0.3`
- CLI Version:      `3.28.0`
- Nitro Version:    `2.12.4`
- Package Manager:  `pnpm@10.12.1`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Vue SSR (correct order): https://stackblitz.com/edit/github-ifxk7hsj?file=src/components/BlueSquare.vue,src/pages/Home.vue

Vue (correct order in dev mode): https://stackblitz.com/edit/vitejs-vite-h4thdsyp?file=src/components/BlueSquare.vue,src/App.vue&terminal=dev

Nuxt (wrong order in prod): https://stackblitz.com/edit/github-ristas3f-hetgu6mm?file=app%2Fcomponents%2FBlueSquare.vue,app%2Fapp.vue

### Describe the bug

This is a follow-up on:
- https://github.com/nuxt/nuxt/issues/25229
- https://github.com/nuxt/nuxt/issues/23785

The styles are now correctly ordered in the `entry.css` file, but the rendered `<style>` tags are not.
Styles from the parent component should always have a higher priority _(in the case of equal specificity - be defined later)_ than the styles from children.

Currently, after the `entry.css` file loads, the correct styles get applied, however, **while the css file is loading**, the styles are broken due to the rendered `<style>` tags being ordered incorrectly. This can cause layout shifts / flashes / etc.

```vue
// CHILD
<template>
  <div class="blue" />
</template>

<style scoped>
.blue { background-color: blue; }
</style>
```

```vue
// PARENT
<template>
  <div>
      <BlueSquare class="red" />
  </div>
</template>

<style scoped>
.red { background-color: red; }
</style>
```

Both plain Vue and Vue with SSR have the correct order:

**Vue**
<img width="714" height="163" alt="Image" src="https://github.com/user-attachments/assets/fa26e7f4-3f89-4bae-b0b1-1fd19f383a02" />

**Vue SSR**
<img width="601" height="190" alt="Image" src="https://github.com/user-attachments/assets/7e1dc7cc-4b32-4ccc-957c-dd207b7a836d" />

But in Nuxt, the order is incorrect when built:

**Nuxt**
<img width="596" height="85" alt="Image" src="https://github.com/user-attachments/assets/62458e07-886e-4c0b-b569-db6e08805f35" />

---

Is this Nuxt related or not?

### Logs

```shell-script

```

**Comment by danielroe** [comment]
this was resolved in #35720

pushed a regression test 🙏

**Comment by andreyshivas** [comment]
@danielroe 
The regression test only covers the entry-chunk case: SomeComponent isn't rendered at all (v-if="visible", visible = false), its CSS reaches the <style> tags via the entry module's bundle-ordered CSS list. When the child component is a separate chunk (a shared component used on several pages), the order is still reversed:


```
<style>.from-parent{color:green}</style>  <!-- page (parent) -->
<style>.child-box{color:red}</style>      <!-- child wins on first paint -->
```
The client loads ChildBox.css → page.css, so the element flips red → green at hydration (green right away on client-side navigation). Same with nuxt@4.5.2, nuxt-nightly@4.6.0-29812804 and nuxt-nightly@5.0.0-29811423: renderInlineStyles walks ssrContext.modules in setup() order and nothing re-sorts across chunks.

Repro: https://github.com/andreyshivas/nuxt-repro-33041 — could this be reopened?

**Comment by cernymatej** [comment]
I also think this isn't fully resolved. I should have a wip fix for this on my macbook somewhere, I'll try to find it and open a draft PR.
