### ISSUE TITLE
addImportsDir types are not added to auto imports in user project

### ISSUE THREAD

**Issue by DLFrontDev** [nuxt/nuxt#33195]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.14.0`
- Nuxt Version:     `4.1.1`
- CLI Version:      `3.28.0`
- Nitro Version:    `2.12.5`
- Package Manager:  `npm@10.9.2`
- Builder:          `-`
- User Config:      `devtools`, `features`, `app`, `modules`, `storyblok`, `robots`, `i18n`, `pinia`, `site`, `sitemap`, `linkChecker`, `ogImage`, `image`, `fonts`, `googleFonts`, `runtimeConfig`, `vite`, `alias`, `css`, `hooks`, `gtag`, `viewport`, `extends`, `imports`, `booster`, `vitalizer`, `experimental`, `sourcemap`, `compatibilityDate`
- Runtime Modules:  `@nuxtjs/i18n@9.5.6`, `@nuxt/image@1.11.0`, `@nuxtjs/seo@3.1.0`, `@nuxt/scripts@0.11.13`, `@pinia/nuxt@0.11.2`, `@nuxtjs/google-fonts@3.2.0`, `@storyblok/nuxt@8.0.8`, `@nuxt/fonts@0.11.4`, `nuxt-viewport@2.3.1`, `nuxt-gtag@4.0.0`, `nuxt-booster@3.3.0`, `nuxt-seo-utils@7.0.14`, `nuxt-vitalizer@0.10.0`, `cja-phoenix@1.2.1`
- Build Modules:    `-`

### Reproduction

[Reproduction with local module and custom module installed](https://codesandbox.io/p/devbox/heuristic-lamport-h8yn44)

### Describe the bug

When I add a directory containing type exports using `addImportsDir` inside the custom module `cja-phoenix`, those exports are then not added to the `imports.d.ts` inside the user project's `.nuxt` directory when installed. It seems that types specifically are being ignored somehow, a class and an array inside said directory are not ignored.

All the .ts files are being correctly transformed into .d.ts files and seem to be correct inside the dist file after module installation, they're simply not referred in the `imports.d.ts` in the user project.

Auto imports for local modules work correctly however, only when a package is installed do the types not get detected.

### Logs

```shell-script

```

**Comment by Flo0806** [comment]
@danielroe nuxt ignores `d.ts`. I think that should be the problem. It is not a bug, It is by design. I'm not sure is this intentional? (`module.ts`) If **not** unimport handles `d.ts` files also wrong.

**Comment by cernymatej** [comment]
This is most likely the same thing as https://github.com/unjs/unimport/issues/490 and should be resolved in the next version of unimport.

**Comment by Flo0806** [comment]
@cernymatej This patch doesn't fix the "issue" at all. Nuxt itself filters the `d.ts` before they come to `unimport` here:

```typescript
// common.js
ignore: {
    $resolve: async (val, get): Promise<string[]> => {
      const [rootDir, ignorePrefix, analyzeDir, buildDir] = await Promise.all([get('rootDir'), get('ignorePrefix'), get('analyzeDir'), get('buildDir')])
      const ignore = new Set<string>([
        '**/*.stories.{js,cts,mts,ts,jsx,tsx}', // ignore storybook files
        '**/*.{spec,test}.{js,cts,mts,ts,jsx,tsx}', // ignore tests
        '**/*.d.{cts,mts,ts}', // ignore type declarations
        '**/*.d.vue.{cts,mts,ts}',
        '**/.{pnpm-store,vercel,netlify,output,git,cache,data}',
        '**/*.sock',
        relative(rootDir, analyzeDir),
        relative(rootDir, buildDir),
      ])
      if (ignorePrefix) {
        ignore.add(`**/${ignorePrefix}*.*`)
      }
      if (Array.isArray(val)) {
        for (const pattern of val) {
          if (pattern) {
            ignore.add(pattern)
          }
        }
      }
      return [...ignore]
    },
  },

```

**Comment by cernymatej** [comment]
Ah, I see. Sorry about that! I missed the part about .d.ts

**Comment by danielroe** [comment]
I think we do need to ignore `.d.ts` files. Consider the typical scenario when we have a `.js` and `.d.ts` file - they have the 'same exports', and so we only want to auto-import from the actual `.js` file.
