### ISSUE TITLE
[v4.1.3] rolldown-vite: Nuxt does not initialize correctly

### ISSUE THREAD

**Issue by yschroe** [nuxt/nuxt#33418]
### Environment

Seems to be broken? It only returns:
`Working directory: /home/projects/owailojmxz.github `

<img width="397" height="63" alt="Image" src="https://github.com/user-attachments/assets/55e84ddc-3a7e-4c95-9ef9-db4c895bd55c" />

### Reproduction

https://stackblitz.com/edit/github-d9hmldmr?file=app%2Fplugins%2Fsome-plugin.ts

### Describe the bug

Hello,
after updating to v4.1.3 my project using rolldown-vite does not fully initialize anymore. If I open a page in the browser the normal console logs like "Suspense is a experimental feature" and the Nuxt dev tools init message never appear. Also custom plugins are never triggered. Instead I only see this warning:
```terminal
The resource https://owailojmxzgithub-q3m1--3000--96435430.local-credentialless.webcontainer.io/_nuxt/builds/meta/dev.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

### Using vite
<img width="793" height="185" alt="Image" src="https://github.com/user-attachments/assets/7cf964c6-3790-4638-87de-3b87851bbde4" />

### Using rolldown-vite
<img width="792" height="258" alt="Image" src="https://github.com/user-attachments/assets/5ce98109-16fa-4b59-a8ba-f8d55a49475d" />

### Additional context

Not sure if this is related, but if I enable `debug: true` in the nuxt config in my real project I get this error message:
```sh
[2:18:09 PM]  ERROR  Cannot start nuxt:  Given napi value is not an array on BindingViteResolvePluginResolveOptions.extensions on BindingViteResolvePluginConfig.resolveOptions

    at makeBuiltinPluginCallable (node_modules/rolldown/dist/shared/src-CUdyD4rb.mjs:233:23)
    at viteResolvePlugin (node_modules/rolldown/dist/experimental-index.mjs:131:9)
    at node_modules/vite/dist/node/chunks/dep-CEfDS7Lp.js:10542:10
    at Object.applyToEnvironment (node_modules/vite/dist/node/chunks/dep-CEfDS7Lp.js:10524:11)
    at resolveEnvironmentPlugins (node_modules/vite/dist/node/chunks/dep-CEfDS7Lp.js:2780:33)
    at async resolveConfig (node_modules/vite/dist/node/chunks/dep-CEfDS7Lp.js:35484:95)
    at async _createServer (node_modules/vite/dist/node/chunks/dep-CEfDS7Lp.js:27119:67)
    at async buildClient (node_modules/@nuxt/vite-builder/dist/index.mjs:1017:24)
    at async withLogs (node_modules/@nuxt/vite-builder/dist/index.mjs:1910:3)
    at async bundle (node_modules/@nuxt/vite-builder/dist/index.mjs:1902:3)
    at async bundle (node_modules/nuxt/dist/index.mjs:7504:5)
    at async build (node_modules/nuxt/dist/index.mjs:7364:3)
    at async Promise.all (index 1)
    at async NuxtDevServer._load (node_modules/@nuxt/cli/dist/chunks/index.mjs:262:5)
    at async NuxtDevServer.load (node_modules/@nuxt/cli/dist/chunks/index.mjs:156:7)
    at async NuxtDevServer.init (node_modules/@nuxt/cli/dist/chunks/index.mjs:146:5)
    at async initialize (node_modules/@nuxt/cli/dist/chunks/index.mjs:458:3)
    at async Object.run (node_modules/@nuxt/cli/dist/chunks/dev.mjs:313:43)
    at async runCommand (node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (node_modules/citty/dist/index.mjs:307:11)
    at async runMain (node_modules/citty/dist/index.mjs:445:7)
```

Also those warnings show up
```sh
WARN  Some values provided to replacePlugin are not strings. They will be converted to strings, but for better performance consider converting them manually.
```

**Comment by billyadelphia** [comment]
I have somewhat same issue too, but only on a page where the SSR is set to false, the page is just white blank.
rolling back to 4.1.2 fix the issue

**Comment by oltov** [comment]
I also have a warning in the console. Among the visible problems, the SVG sprite stopped loading and Nuxt devtools doesn't work. On version 4.1.2 everything is fine.

**Comment by TheAlexLichter** [comment]
Glad to see so many ppl trying out Rolldown-Vite - I'll look into it 👍

**Comment by billyadelphia** [comment]
@TheAlexLichter I have always using rolldown vite since it announced

```
"overrides": {
    "vite": "npm:rolldown-vite@latest"
  }
```

should I disable that on v4.1.3 ?
Because that override is working fine on any version below v4.1.3 ..

**Comment by alaxcc** [comment]
Yes, it's exactly the same. I've been tormented by this issue for a full day and night. There are no error messages in the console whatsoever, leaving me with no starting point for troubleshooting. The new version appears extremely unstable. I'm currently attempting to roll back to 3.19. The 4.x series carries significant risks, and this particular 4.1.13 release is a veritable worm bomb that has completely wrecked my project.

**Comment by mickosi** [comment]
> Yes, it's exactly the same. I've been tormented by this issue for a full day and night. There are no error messages in the console whatsoever, leaving me with no starting point for troubleshooting. The new version appears extremely unstable. I'm currently attempting to roll back to 3.19. The 4.x series carries significant risks, and this particular 4.1.13 release is a veritable worm bomb that has completely wrecked my project.

Never use the last version in production. I have feelings that they test naked nuxt without modules and other shit.

**Comment by alaxcc** [comment]
> > Yes, it's exactly the same. I've been tormented by this issue for a full day and night. There are no error messages in the console whatsoever, leaving me with no starting point for troubleshooting. The new version appears extremely unstable. I'm currently attempting to roll back to 3.19. The 4.x series carries significant risks, and this particular 4.1.13 release is a veritable worm bomb that has completely wrecked my project.
> 
> Never use the last version in production. I have feelings that they test naked nuxt without modules and other shit.

They call it's **Stable**

**Comment by TheAlexLichter** [comment]
You are using an unstable / technical preview package (`rolldown-vite`), so I'm not sure what your expectations are here exactly. This is everything but stable.

**Comment by Charles5277** [comment]
> > > Yes, it's exactly the same. I've been tormented by this issue for a full day and night. There are no error messages in the console whatsoever, leaving me with no starting point for troubleshooting. The new version appears extremely unstable. I'm currently attempting to roll back to 3.19. The 4.x series carries significant risks, and this particular 4.1.13 release is a veritable worm bomb that has completely wrecked my project.
> > 
> > 
> > Never use the last version in production. I have feelings that they test naked nuxt without modules and other shit.
> 
> They call it's **Stable**

Dude, who told you rolldown-vite already stable?

**Comment by Charles5277** [comment]
> Glad to see so many ppl trying out Rolldown-Vite - I'll look into it 👍

Nuxt 4.1.2 (with Nitro 2.12.7, Rolldown-Vite 7.1.16, and Vue 3.5.22)
→ Works normally 

When upgrading to Nuxt 4.1.3, the following error occurs

**Comment by wemod123** [comment]
> 
> Nuxt 4.1.2 (with Nitro 2.12.7, Rolldown-Vite 7.1.16, and Vue 3.5.22) → Works normally
> 
> When upgrading to Nuxt 4.1.3, the following error occurs

After upgrade to Nuxt 4.1.3, it occasionally just stacked somewhere and Nut server stop response, I can not debug since there are no logs outputs anywhere.

**Comment by alaxcc** [comment]
> > Nuxt 4.1.2 (with Nitro 2.12.7, Rolldown-Vite 7.1.16, and Vue 3.5.22) → Works normally
> > When upgrading to Nuxt 4.1.3, the following error occurs
> 
> After upgrade to Nuxt 4.1.3, it occasionally just stacked somewhere and Nut server stop response, I can not debug since there are no logs outputs anywhere.

Stay on 4.1.2, wait 5.0.

**Comment by alaxcc** [comment]
> You are using an unstable / technical preview package (`rolldown-vite`), so I'm not sure what your expectations are here exactly. This is everything but stable.

Do you have a release date for version 5.0? I see Nitro V3.0 is already out; I'm waiting for a stable version 5.0. Thank you.

**Comment by TheAlexLichter** [comment]
No. Also, Nuxt 5 is not related to Vite 8 (aka a "stable" rolldown-vite).

**Comment by alaxcc** [comment]
> No. Also, Nuxt 5 is not related to Vite 8 (aka a "stable" rolldown-vite).

Okay, I'll stick to 3.19/4.1.12 and consider other frameworks. Vite based on oxc-based is widely used. You ignore it today and face it tomorrow. This cannot be avoided. Thank you for your contribution at Nuxt!

**Comment by TheAlexLichter** [comment]
> You ignore it today and face it tomorrow. This cannot be avoided.

Rolldown-Vite (+ it's integration) is still experimental, so you have to expect that there might be issues compared to plain Vite Nuxt for now. We are on it to fix it 😉

**Comment by yschroe** [comment]
Hello,

I have just updated to v4.2 and unfortunately the issue still remains. 
I tried to debug the problem some more and think the problem is that the rolldown version of the replace plugin is not callable.
If you compare the return types of the rolldown and rollup versions of the plugin, it looks like this:

```ts
// rollup
{ 
  name: 'replace',                                                                    
  buildStart: [Function: buildStart],
  renderChunk: [Function: renderChunk],
  transform: [Function: transform] 
}

// rolldown
BuiltinPlugin { 
  name: 'builtin:replace', 
  _options: { preventAssignment: true, values: {} } 
}
```

The rolldown version seems to miss the actual transform functions that are being called by vite. There is a `makeBuiltinPluginCallable` in the rolldown package though and if I try patching the plugin like this, the page now loads correctly for me:

#### nuxt.config.ts
```ts
// Function and file name might be different due to minification/chunking (works for rolldown 7.1.19).
// Not exported via package.json so full path is necessary here.
import { b as makeBuiltinPluginCallable } from './node_modules/rolldown/dist/shared/src-DY4_vVWu.mjs';

export default defineNuxtConfig({
  ...,
  hooks: {
    // Some ts errors here due to writing to a readonly property etc
    'vite:extendConfig'(config) {
      const replacePlugin = config.plugins?.find(
        (p) => p?.name === 'nuxt:replace',
      );
      // Save reference to original `applyToEnvironment`
      const originalApply = replacePlugin.applyToEnvironment;
  
      // Patch `applyToEnvironment`
      replacePlugin.applyToEnvironment = async (environment: unknown) => {
        const originalPlugin = await originalApply(environment)
        return makeBuiltinPluginCallable(originalPlugin);
      };
    }
  },
  ...
}
```

@TheAlexLichter Could you check if this indeed could be the reason for the rolldown replace plugin breaking nuxt or if I did something completely wrong and disabled the replace plugin altogether by accident or something like that? Thanks! 🙏🏻

**Comment by antfu** [comment]
Reopen as the issue seems still persists on 4.2

**Comment by Charles5277** [comment]
Same problem when upgrade to 4.2

**Comment by Vinyrw** [comment]
> Hello,
> 
> I have just updated to v4.2 and unfortunately the issue still remains. I tried to debug the problem some more and think the problem is that the rolldown version of the replace plugin is not callable. If you compare the return types of the rolldown and rollup versions of the plugin, it looks like this:
> 
> // rollup
> { 
>   name: 'replace',                                                                    
>   buildStart: [Function: buildStart],
>   renderChunk: [Function: renderChunk],
>   transform: [Function: transform] 
> }
> 
> // rolldown
> BuiltinPlugin { 
>   name: 'builtin:replace', 
>   _options: { preventAssignment: true, values: {} } 
> }
> The rolldown version seems to miss the actual transform functions that are being called by vite. There is a `makeBuiltinPluginCallable` in the rolldown package though and if I try patching the plugin like this, the page now loads correctly for me:
> 
> #### nuxt.config.ts
> // Function and file name might be different due to minification/chunking (works for rolldown 7.1.19).
> // Not exported via package.json so full path is necessary here.
> import { b as makeBuiltinPluginCallable } from './node_modules/rolldown/dist/shared/src-DY4_vVWu.mjs';
> 
> export default defineNuxtConfig({
>   ...,
>   hooks: {
>     // Some ts errors here due to writing to a readonly property etc
>     'vite:extendConfig'(config) {
>       const replacePlugin = config.plugins?.find(
>         (p) => p?.name === 'nuxt:replace',
>       );
>       // Save reference to original `applyToEnvironment`
>       const originalApply = replacePlugin.applyToEnvironment;
>   
>       // Patch `applyToEnvironment`
>       replacePlugin.applyToEnvironment = async (environment: unknown) => {
>         const originalPlugin = await originalApply(environment)
>         return makeBuiltinPluginCallable(originalPlugin);
>       };
>     }
>   },
>   ...
> }
> [@TheAlexLichter](https://github.com/TheAlexLichter) Could you check if this indeed could be the reason for the rolldown replace plugin breaking nuxt or if I did something completely wrong and disabled the replace plugin altogether by accident or something like that? Thanks! 🙏🏻

The problem persists in version 4.2.0.
My project only started working correctly again after adding the solution implemented by @yschroe .

I had to change the line to make it work:

import { b as makeBuiltinPluginCallable } from './node_modules/rolldown/dist/shared/src-CPA2meNe.mjs';

My Nuxt 4.2.0 is using Rolldown-Vite 7.1.20.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/33615.

**Comment by yschroe** [comment]
Thanks for the fix. Updating to rolldown-vite@7.2.0-beta.2 also resolves the issue without a Nuxt update being necessary.

**Comment by Zebnastien** [comment]
Upgraded to Nuxt 4.2 and rolldown-vite@7.2.0-beta.2 and the issue is still happening.

**Comment by TheAlexLichter** [comment]
@Zebnastien A fix should be available in the latest nuxt nightly.

**Comment by Zebnastien** [comment]
@TheAlexLichter, for now, trying with Nuxt nightly does not fix the issue on my side. Here is some versions I tried:
- Using latest bun or latest node lts.
- Using Nuxt 4.2 or latest nightly.
- Using rolldown-vite latest or 7.2.0-beta.2

If I can help in any way, just ask.

[nuxi 11:54:01 AM] Nuxt 4.2.1-29370847.26aaf83d (with Nitro 2.12.9, Rolldown-Vite 7.2.0-beta.2 and Vue 3.5.22)

**Comment by TheAlexLichter** [comment]
Just checked locally and it works fine for me with nightly + rolldown-vite.

`Nuxt 4.2.1-29370847.26aaf83d (with Nitro 2.12.9, Rolldown-Vite 7.1.20 and Vue 3.5.22)                                              nuxi 12:26:27 PM`

<img width="337" height="56" alt="Image" src="https://github.com/user-attachments/assets/236c5769-3ce6-45f5-bc65-6830390c825a" />

`package.json`

```json
{
  "devDependencies": {
    "@nuxt/devtools": "^2.6.2",
    "nuxt": "npm:nuxt-nightly@latest",
    "vue": "^3.5.18",
    "vue-router": "^4.5.1"
  },
  "overrides": {
    "vite": "npm:rolldown-vite@latest"
  }
}
```

**Comment by yschroe** [comment]
> [@TheAlexLichter](https://github.com/TheAlexLichter), for now, trying with Nuxt nightly does not fix the issue on my side. Here is some versions I tried:
> 
> * Using latest bun or latest node lts.
> * Using Nuxt 4.2 or latest nightly.
> * Using rolldown-vite latest or 7.2.0-beta.2
> 
> If I can help in any way, just ask.
> 
> [nuxi 11:54:01 AM] Nuxt 4.2.1-29370847.26aaf83d (with Nitro 2.12.9, Rolldown-Vite 7.2.0-beta.2 and Vue 3.5.22)

Can you double check in your node_modules folder if the correct versions are installed? Or try deleting node_modules (and maybe your lockfile as well) and then reinstall. And stupid question but did you remove the `makeBuiltinPluginCallable` workaround if you have used it prior? This is now done directly in the rolldown package (since v1.0.0-beta.46 which rolldown-vite@7.2.0-beta.2 uses).

For me Nuxt 4.2 + rolldown-vite@7.2.0-beta.2 works out of the box now.

**Comment by Zebnastien** [comment]
@yschroe, I always delete .nuxt, node_modules and bun.lock between intents.
I double checked, the issue is solved on a fresh nuxt project indeed. I never used the mentioned workaround.

But it is still happening on a project with these dependencies:

<img width="403" height="349" alt="Image" src="https://github.com/user-attachments/assets/ab95d50b-3579-4567-801d-9a073deffb76" />

<img width="740" height="22" alt="Image" src="https://github.com/user-attachments/assets/ac7c3f94-bebc-4e3e-ad88-66b2779d466f" />

<img width="427" height="95" alt="Image" src="https://github.com/user-attachments/assets/3395d1d1-2f1a-462a-9792-8d5a9af6402a" />

EDIT : Installed dependencies and one by one and found the faulty one: @nuxt/supabase is causing theses two errors:

<img width="408" height="187" alt="Image" src="https://github.com/user-attachments/assets/654accb4-cd54-460e-86d4-06737ee15ff5" />

Nuxt fix works fine without this module, many thanks to the team.

**Comment by jakubkoje** [comment]
Can confirm, that the nightly version of Nuxt fixes the issue.

**Comment by billyadelphia** [comment]
4.2.1 fixed the issue for me
and rolldown-vite v7.2.1

**Comment by alanscodelog** [comment]
I'm on nightly and running into this but only when I pass DEBUG=* before the command. Very weird. Could not replicate on stackblitz unfortunately so maybe it's something in my deps, but idk what I should even be looking for.
