### ISSUE TITLE
Memory leak in Vue

### ISSUE THREAD

**Issue by ac-shadow** [nuxt/nuxt#33644]
### Environment

- Operating System: Linux
- Node Version:     v22.19.0
- Nuxt Version:     4.2.0
- CLI Version:      3.29.3
- Nitro Version:    2.12.9
- Package Manager:  [pnpm@10.18.3](mailto:pnpm@10.18.3)
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

[https://stackblitz.com/edit/github-z3g1tibv?file=app%2Fapp.vue](https://stackblitz.com/edit/github-z3g1tibv?file=app%2Fapp.vue)

### Describe the bug

After upgrading our app from 4.1.3 to 4.2.0 it started to consume a lot of memory until it crashes.
It seems to me like the issue is caused by `useFetch` / `useAsyncData` and the recent addition of signals.

### Additional context

To isolate the issue I created a minimal app using `pnpm create nuxt@latest` and updated the `app.vue` like this:

```vue
<script setup lang="ts">
const { data } = await useFetch('https://jsonplaceholder.typicode.com/todos/')
// const { data } = await useAsyncData('todos', (_nuxtApp, { signal }) => $fetch('https://jsonplaceholder.typicode.com/todos/', { signal }))
// const data = await $fetch('https://jsonplaceholder.typicode.com/todos/')
</script>

<template>
  <div>
    <NuxtRouteAnnouncer />
    <pre>{{ data }}}</pre>
  </div>
</template>
```

I used the node inspector and ran 10k requests with `ab -n 10000 -c 5 http://127.0.0.1:3000/`

Nuxt 4.1.3:

![Image](https://github.com/user-attachments/assets/b07a52af-3134-4023-a930-797d7ebf4d8d)

Nuxt 4.2.0 - `useFetch`:

![Image](https://github.com/user-attachments/assets/982a2119-e53c-4c55-bfab-d92bd4f4f61a)

Nuxt 4.2.0 - `useAsyncData`:

![Image](https://github.com/user-attachments/assets/393724dd-dff3-4207-8d27-615cc796fefd)

Nuxt 4.2.0 - `$fetch`:

![Image](https://github.com/user-attachments/assets/f2706969-27c2-4bcd-99ab-17b08ab6975f)

More context:

![Image](https://github.com/user-attachments/assets/0d8730f3-ed2f-4503-982e-0b75c443bf01)

### Logs

```shell-script

```

&nbsp;

**Comment by maximepvrt** [comment]
This issue occurs when using a vue version higher than `3.5.13` but lower than the `3.6` pre-release. Vue should be pinned to version `3.5.13`.

linking #32240 #33080

**Comment by ac-shadow** [comment]
@maximepvrt ran the same test with vue `3.5.13` and `3.6.0-alpha.2` but its still the same behaviour. This problem also doesn't occur with nuxt `4.1.3` and vue `3.5.22`.

**Comment by lacoste-sochi** [comment]
> [@maximepvrt](https://github.com/maximepvrt) ran the same test with vue `3.5.13` and `3.6.0-alpha.2` but its still the same behaviour. This problem also doesn't occur with nuxt `4.1.3` and vue `3.5.22`.

Thanks - you made my day. I spent the whole day yesterday fighting with memory leaks....

 The combination of nuxt 4.1.3 and vue 3.5.22 did its job. There are no leaks, and it even takes up less memory than usual.

It was:
<img width="1399" height="1028" alt="Image" src="https://github.com/user-attachments/assets/3c602661-bba9-4f23-865b-cb474ac4578d" />

Become after npx autocannon -c 20 -d 60 -p 10 http://127.0.0.1:3000/:
<img width="1614" height="750" alt="Image" src="https://github.com/user-attachments/assets/46b12f7e-62b4-4b65-94d4-1ccf3e5ee70b" />

**Comment by danielroe** [comment]
as you found, this is an upstream vue issue which is already resolved....

**Comment by ac-shadow** [comment]
@danielroe sorry maybe my message was worded a bit weird or i am misunderstanding something. But for me the issue is not resolved. Unless i am doing something wrong i can't get nuxt `4.2.0` to work, even with vue pinned to `3.5.13`. The only solution for me right now is to stick with nuxt `4.1.3` which doesn't seem to have the memory issue regardless of the vue version i use.

**Comment by AlejandroMut** [comment]
Same here... Memory leak issue. It is a fairly simple website and it started this behavior right after updating to Nuxt  4.2.0.

<img width="1588" height="451" alt="Image" src="https://github.com/user-attachments/assets/cf40dfb6-7e3d-439a-b5ef-951b74c983c3" />

**Comment by arkoannuk** [comment]
In my case, memory leak was also present when going from Nuxt version `3.19.3` to `3.2.0`

**Comment by JulianMar** [comment]
Same issue here. It is almost impossible to fix vue to 3.5.13. 
For example @unhead/vue has as peerDependency vue >= 3.5.18 and unhead is required by the @nuxt/nitro-server.

For the issue:
It seems to me that the issue appears in the vue-routers addRoute function and it's three sub functions (tokensToParser, tokenizePath and normalizeRoutePaths).

<img width="2053" height="1388" alt="Image" src="https://github.com/user-attachments/assets/dd8a08ed-675e-4d46-849c-5736196f7e15" />

**Comment by danielroe** [comment]
it's very helpful if you can pin vue or vue-router _via resolutions_ to identify whether the issue is coming from either of them.

**Comment by JulianMar** [comment]
After downgrading vue-router nothing happend. After downgrading vue the memory leak was still present as well. The issue has to appear in some other library which might be interacting wrongly with vue-router.

**Comment by JulianMar** [comment]
Weird. I fixed the issue by migrating away from this way of using i18n  https://vue-i18n.intlify.dev/guide/integrations/nuxt3.html and to the nuxt module https://nuxt.com/modules/i18n. No more issue on nuxt 4.1.3

**Comment by ac-shadow** [comment]
I investigated this a bit more and may have found the issue. Correct me if I am wrong but it seems like this EventListener in `useAsyncData` doesn't get removed if the abort event is never triggered.

https://github.com/nuxt/nuxt/blob/6b6ea5faa1bcea7ad27ab1203e15b1d4e07eda99/packages/nuxt/src/app/composables/asyncData.ts#L716-L719

 I also ran the same test as above in the playground with these lines commented out and the memory leak disappeared.

**Comment by danielroe** [comment]
thanks for the nice spot!

if you want to try with a pkg.pr.new version, I've pushed a PR and you can use the following `nuxt` package version to test:

```shell
npm i https://pkg.pr.new/nuxt@33665
```

**Comment by ac-shadow** [comment]
I tried it again with the pkg.pr.new version and the memory leak is gone. Thanks :)

**Comment by OrbisK** [comment]
@ac-shadow 

Could you please check if my [followup](https://github.com/nuxt/nuxt/pull/33667) is still working for you? 
```
npm i https://pkg.pr.new/nuxt@33667
```

**Comment by ac-shadow** [comment]
@OrbisK yeah it still works fine with that version

**Comment by thomashohn** [comment]
Was this also an issue in 3.20.0?

**Comment by OrbisK** [comment]
> Was this also an issue in 3.20.0?

<img width="989" height="637" alt="Image" src="https://github.com/user-attachments/assets/9e520d3b-6b09-4311-96f5-af7f701d21a1" />

Yes, the same issue was introduced in version 3.20. The fixes will be backported to Nuxt 3.

**Comment by SprayDev** [comment]
In my project of nuxt 4.2.2 I still have memory leak if I use wrapper for useAsyncData.
If I do ab -n 100 -c 50 to my page where I have wrapper for useAsyncData that has server: false 
My memory goes up to 1gb and than after ab finishes memory got stack at 800mb till the end

**Comment by OrbisK** [comment]
> In my project of nuxt 4.2.2 I still have memory leak if I use wrapper for useAsyncData. If I do ab -n 100 -c 50 to my page where I have wrapper for useAsyncData that has server: false My memory goes up to 1gb and than after ab finishes memory got stack at 800mb till the end

Please create a new issue with a minimal reproduction 🙏🏽

**Comment by SprayDev** [comment]
> > In my project of nuxt 4.2.2 I still have memory leak if I use wrapper for useAsyncData. If I do ab -n 100 -c 50 to my page where I have wrapper for useAsyncData that has server: false My memory goes up to 1gb and than after ab finishes memory got stack at 800mb till the end
> 
> Please create a new issue with a minimal reproduction 🙏🏽

Created new issue with reproduction repo 
https://github.com/nuxt/nuxt/issues/34112

**Comment by simonmaass** [comment]
i am using nuxt 4.3.0 and we still have memory leaks and webserver restarts every 30 minutes

**Comment by danielroe** [comment]
@simonmaass are you using any of the nuxt-seo modules?

**Comment by simonmaass** [comment]
@danielroe yes we are using @nuxtjs/seo v3.3.0

**Comment by danielroe** [comment]
let's track in https://github.com/harlan-zw/nuxt-seo/issues/510

**Comment by simonmaass** [comment]
@danielroe i am not using a wrapper around useAsyncData like "useApiData" mentioned in the issue...

**Comment by danielroe** [comment]
@simonmaass I'm aware of two issues:

- latest version of vue has a memory leak, resolved by pinning to `3.5.13` or v3.6 beta
- nuxt-seo has a memory leak

does yours reproduce if you pin vue + remove nuxt-seo?

(reopening pending response)

**Comment by SprayDev** [comment]
@danielroe The problem disappeared after I downgraded my Vue version to 3.5.13 in this repo:
https://github.com/SprayDev/nuxt-seo-memory/tree/master

(There’s no commit for the Vue downgrade, unfortunately.)

However, I have a live website built with Nuxt 4.2.2 (vue 3.5.13), and I’m seeing some strange behavior there. Right after building the project, Nuxt allocates around 400 MB of memory. Over the course of the day, this memory usage keeps increasing, and by the next morning—when the website has no traffic—the Nuxt app is using around 1.4 GB, and it never goes down afterward. So I’m thinking there might be a memory leak somewhere in Nuxt or in one of the packages.

Unfortunately, I can’t create a reliable reproduction. My repro builds usually start with 30–40 MB, and then climb to around 70–100 MB with regular requests.

**Comment by bgarcias-cp** [comment]
@SprayDev do you have `experimental.asyncContext = true`?

I found a memory leak when you have that feature enabled: 
https://github.com/nuxt/nuxt/issues/34071#issuecomment-3809564524

**Comment by SprayDev** [comment]
@bgarcias-cp No, I dont have this option

**Comment by simonmaass** [comment]
@danielroe the memory leak seams to have resolved after hard pinning vue `3.5.13`

<img width="373" height="167" alt="Image" src="https://github.com/user-attachments/assets/c2695067-94d0-4775-a58f-b91ab1ae6e61" />

**Comment by hansemannn** [comment]
I was just about to mention a similar finding: Simply downgrading to `3.15.3` doesn't work. You have to override all vue core modules in your package.json:

### For pnpm
```json
  "pnpm": {
    "overrides": {
      "@vue/compiler-core": "3.5.13",
      "@vue/compiler-dom": "3.5.13",
      "@vue/compiler-sfc": "3.5.13",
      "@vue/compiler-ssr": "3.5.13",
      "@vue/reactivity": "3.5.13",
      "@vue/runtime-core": "3.5.13",
      "@vue/runtime-dom": "3.5.13",
      "@vue/server-renderer": "3.5.13",
      "@vue/shared": "3.5.13",
      "vue": "3.5.13"
    }
  }
```

### For npm 
```json
    "overrides": {
      "@vue/compiler-core": "3.5.13",
      "@vue/compiler-dom": "3.5.13",
      "@vue/compiler-sfc": "3.5.13",
      "@vue/compiler-ssr": "3.5.13",
      "@vue/reactivity": "3.5.13",
      "@vue/runtime-core": "3.5.13",
      "@vue/runtime-dom": "3.5.13",
      "@vue/server-renderer": "3.5.13",
      "@vue/shared": "3.5.13",
      "vue": "3.5.13"
    }
```

This fixed our memory leak immediately, after spending weeks on other approaches.

**Comment by JustinFeng** [comment]
> I was just about to mention a similar finding: Simply downgrading to `3.15.3` doesn't work. You have to override all vue core modules in your package.json:
> 
> ### For pnpm
>   "pnpm": {
>     "overrides": {
>       "@vue/compiler-core": "3.5.13",
>       "@vue/compiler-dom": "3.5.13",
>       "@vue/compiler-sfc": "3.5.13",
>       "@vue/compiler-ssr": "3.5.13",
>       "@vue/reactivity": "3.5.13",
>       "@vue/runtime-core": "3.5.13",
>       "@vue/runtime-dom": "3.5.13",
>       "@vue/server-renderer": "3.5.13",
>       "@vue/shared": "3.5.13",
>       "vue": "3.5.13"
>     }
>   }
> ### For npm
>     "overrides": {
>       "@vue/compiler-core": "3.5.13",
>       "@vue/compiler-dom": "3.5.13",
>       "@vue/compiler-sfc": "3.5.13",
>       "@vue/compiler-ssr": "3.5.13",
>       "@vue/reactivity": "3.5.13",
>       "@vue/runtime-core": "3.5.13",
>       "@vue/runtime-dom": "3.5.13",
>       "@vue/server-renderer": "3.5.13",
>       "@vue/shared": "3.5.13",
>       "vue": "3.5.13"
>     }
> This fixed our memory leak immediately, after spending weeks on other approaches.

This fix the memory leak in our project as well, what we had was

- "vue": "^3.5.17"
- "nuxt": "^3.17.6"
- "vue-router": "^4.5.1"

**Comment by edison1105** [comment]
> [@danielroe](https://github.com/danielroe) The problem disappeared after I downgraded my Vue version to 3.5.13 in this repo: [SprayDev/nuxt-seo-memory@`master`](https://github.com/SprayDev/nuxt-seo-memory/tree/master)
> 
> (There’s no commit for the Vue downgrade, unfortunately.)
> 
> However, I have a live website built with Nuxt 4.2.2 (vue 3.5.13), and I’m seeing some strange behavior there. Right after building the project, Nuxt allocates around 400 MB of memory. Over the course of the day, this memory usage keeps increasing, and by the next morning—when the website has no traffic—the Nuxt app is using around 1.4 GB, and it never goes down afterward. So I’m thinking there might be a memory leak somewhere in Nuxt or in one of the packages.
> 
> Unfortunately, I can’t create a reliable reproduction. My repro builds usually start with 30–40 MB, and then climb to around 70–100 MB with regular requests.

@SprayDev Thanks for your reproduction. I've fixed the memory in your reproduction. PR https://github.com/vuejs/core/pull/14445
- try `pnpm add https://pkg.pr.new/vue@14445`

But there is a mistake in your reproduction. in `app/composables/useApiData.ts`
```diff
-  return {
-    ...asyncData,
-    loading
-  }
+  // Keep useAsyncData's thenable identity. Spreading (`...asyncData`) strips Promise behavior
+  // and changes await timing in async setup, which can break runtime-core scope reset pairing.
+  // return Object.assign(asyncData, { loading })
```

With these changes and `pnpm add https://pkg.pr.new/vue@14445`, the memory leak disappears.

**Comment by ynte** [comment]
I think I had a similar problem, all the objects created in an ssr request were being retained in memory. This caused continuous spikes in memory uses and OOM crashes.

Pinning to a specific vue `3.5.x` version did not work for me. The memory leak persisted. I force installed vue `3.6.0-beta.5` and now my memory usage is low and stable. Might we worth a try if you're also struggling with pinning the right `3.5.x`. In my app the beta version did not break any of my tests.

**Comment by SebbeJohansson** [comment]
The upstream bug-fix seems to be merged now.

Mainly for those that find this issue and also use Sentry (like my company does), there is a similar issue in Sentry which is also fixed in later versions of their nuxt package: https://github.com/getsentry/sentry-javascript/issues/17555

**Comment by simonmaass** [comment]
@SebbeJohansson are u sure the sentry reference is correct? I am not sure what u exactly mean...

**Comment by SebbeJohansson** [comment]
> @SebbeJohansson are u sure the sentry reference is correct? I am not sure what u exactly mean...

Yes it should be the right reference.

**Comment by SaeedNezafat** [comment]
Hi 👋

I was able to resolve this issue in my project by applying a custom patch to Nuxt SSR / Vue EffectScope handling.

This script performs two main actions:

Patches @vue/reactivity: It registers every EffectScope created during SSR using AsyncLocalStorage.

Patches the Nuxt SSR renderer output: It wraps renderToString so that each render runs inside its own isolated AsyncLocalStorage context, and once rendering is complete, all collected scopes are properly stop()ped and cleaned up.

The goal of this patch is to ensure that SSR effect scopes do not leak across requests, preventing memory leaks and scope accumulation between renders.

Below is the patch script I used:

```
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const PATCH_MARKER = "/* nuxt-ssr-effectscope-patch */";
const GLOBAL_ALS_KEY = "__NUXT_SSR_EFFECT_SCOPE_ALS__";

function walkFiles(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  const stack = [dir];
  while (stack.length) {
    const current = stack.pop();
    let entries;
    try {
      entries = fs.readdirSync(current, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else {
        out.push(full);
      }
    }
  }
  return out;
}

function replaceOnce(content, pattern, replacement, label) {
  const next = content.replace(pattern, replacement);
  if (next === content) {
    throw new Error(`Failed to apply patch: ${label}`);
  }
  return next;
}

function patchReactivityFile(filePath) {
  let content = fs.readFileSync(filePath, "utf8");
  if (content.includes(PATCH_MARKER)) {
    return { filePath, changed: false };
  }

  const activeScopeDecl = /\b(?:let|var)\s+activeEffectScope\b[^;]*;/;
  if (!activeScopeDecl.test(content)) {
    throw new Error(`Could not find activeEffectScope in ${filePath}`);
  }

  const alsBlock = `${PATCH_MARKER}
const { AsyncLocalStorage } = require("node:async_hooks");
const __nuxtEffectScopeAls = globalThis.${GLOBAL_ALS_KEY} || (globalThis.${GLOBAL_ALS_KEY} = new AsyncLocalStorage());
function __nuxtRegisterScope(scope) {
  const store = __nuxtEffectScopeAls.getStore && __nuxtEffectScopeAls.getStore();
  if (store && store.scopes) store.scopes.add(scope);
}
`;

  content = replaceOnce(
    content,
    activeScopeDecl,
    (match) => `${match}\n${alsBlock}`,
    "insert ALS helpers in reactivity"
  );

  if (!content.includes("__nuxtRegisterScope(this)")) {
    content = replaceOnce(
      content,
      /this\.parent\s*=\s*activeEffectScope\s*;/,
      (match) => `${match}\n    __nuxtRegisterScope(this);`,
      "register EffectScope instances"
    );
  }

  fs.writeFileSync(filePath, content, "utf8");
  return { filePath, changed: true };
}

function findReactivityTargets() {
  const targets = [];
  const roots = [
    path.join(ROOT, "node_modules"),
    path.join(ROOT, ".output", "server", "node_modules"),
  ];
  const names = ["reactivity.cjs.js", "reactivity.cjs.prod.js"];
  for (const root of roots) {
    const dist = path.join(root, "@vue", "reactivity", "dist");
    if (!fs.existsSync(dist)) continue;
    for (const name of names) {
      const filePath = path.join(dist, name);
      if (fs.existsSync(filePath)) targets.push(filePath);
    }
  }
  return targets;
}

function pickRendererFile(serverDir) {
  const files = walkFiles(serverDir).filter((file) =>
    /\.(mjs|js)$/.test(file)
  );
  const candidates = [];
  for (const file of files) {
    const content = fs.readFileSync(file, "utf8");
    if (!content.includes("renderToString(")) continue;
    if (!content.includes("vue/server-renderer")) continue;
    candidates.push({ file, content });
  }
  if (!candidates.length) return null;

  const scored = candidates
    .map((item) => {
      let score = 0;
      if (/renderer/i.test(path.basename(item.file))) score += 2;
      if (item.content.includes("createSSRApp")) score += 1;
      return { ...item, score };
    })
    .sort((a, b) => b.score - a.score);

  if (scored.length > 1 && scored[0].score === scored[1].score) {
    const preferred = scored.find((item) =>
      /[\\/]chunks[\\/]routes[\\/]renderer\.mjs$/.test(item.file)
    );
    if (preferred) return preferred;
    const list = scored.map((item) => item.file).join(", ");
    throw new Error(
      `Multiple renderer candidates found. Please refine selection: ${list}`
    );
  }
  return scored[0];
}

function insertAfterImports(content, block) {
  const importRegex = /^(?:\uFEFF)?import[\s\S]*?;[ \t]*$/gm;
  let match;
  let lastIndex = 0;
  while ((match = importRegex.exec(content))) {
    lastIndex = importRegex.lastIndex;
  }
  if (lastIndex === 0) return `${block}\n${content}`;
  return `${content.slice(0, lastIndex)}\n${block}\n${content.slice(
    lastIndex
  )}`;
}

function patchRenderer(filePath, originalContent) {
  if (originalContent.includes(PATCH_MARKER)) {
    return { filePath, changed: false };
  }

  if (!/\brenderToString\s*\(/.test(originalContent)) {
    throw new Error(`renderToString call not found in ${filePath}`);
  }

  const renderOwnerMatch = originalContent.match(
    /([A-Za-z_$][\w$]*)\.renderToString\s*\(/
  );
  if (!renderOwnerMatch) {
    throw new Error(`renderToString method usage not found in ${filePath}`);
  }
  const renderOwner = renderOwnerMatch[1];

  const assignmentRegex = new RegExp(
    `const\\s+${renderOwner}\\s*=\\s*await\\s+[^;]+;`
  );
  if (!assignmentRegex.test(originalContent)) {
    throw new Error(
      `Unable to locate renderer assignment for ${renderOwner} in ${filePath}`
    );
  }

  let content = replaceOnce(
    originalContent,
    assignmentRegex,
    (match) => `${match}__nuxtWrapRenderToString(${renderOwner});`,
    "insert renderToString wrapper call"
  );

  const helperBlock = `${PATCH_MARKER}
import { AsyncLocalStorage } from "node:async_hooks";
const __nuxtEffectScopeAls = globalThis.${GLOBAL_ALS_KEY} || (globalThis.${GLOBAL_ALS_KEY} = new AsyncLocalStorage());
function __nuxtWrapRenderToString(renderer) {
  if (!renderer || renderer.__nuxtEffectScopeWrapped) return;
  renderer.__nuxtEffectScopeWrapped = true;
  const original = renderer.renderToString;
  renderer.renderToString = async (...args) => {
    return __nuxtEffectScopeAls.run({ scopes: new Set() }, async () => {
      const store = __nuxtEffectScopeAls.getStore();
      try {
        return await original(...args);
      } finally {
        if (store && store.scopes) {
          for (const scope of store.scopes) {
            try { scope.stop(); } catch {}
          }
          store.scopes.clear();
        }
      }
    });
  };
}
`;

  content = insertAfterImports(content, helperBlock);

  fs.writeFileSync(filePath, content, "utf8");
  return { filePath, changed: true };
}

function main() {
  const reactivityTargets = findReactivityTargets();
  if (!reactivityTargets.length) {
    throw new Error(
      "No @vue/reactivity dist files found. Run `nuxt build` before patching."
    );
  }

  const reactivityResults = reactivityTargets.map((filePath) =>
    patchReactivityFile(filePath)
  );

  const serverDir = path.join(ROOT, ".output", "server");
  if (!fs.existsSync(serverDir)) {
    throw new Error(
      "Nuxt output not found. Expected .output/server after nuxt build."
    );
  }

  const renderer = pickRendererFile(serverDir);
  if (!renderer) {
    throw new Error("Unable to locate SSR renderer file to patch.");
  }
  const rendererResult = patchRenderer(renderer.file, renderer.content);

  const patched = [
    ...reactivityResults.filter((r) => r.changed).map((r) => r.filePath),
    ...(rendererResult.changed ? [rendererResult.filePath] : []),
  ];

  if (!patched.length) {
    console.log("patch-renderer.mjs: already patched.");
  } else {
    console.log("patch-renderer.mjs: patched files:");
    for (const file of patched) console.log(`- ${file}`);
  }
}

try {
  main();
} catch (error) {
  console.error("patch-renderer.mjs: failed");
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
```
If anyone is experiencing similar SSR memory issues in Nuxt, this workaround may help until an official fix is available.

**Comment by danielroe** [comment]
@SaeedNezafat does the current nightly of nuxt (with edison's fix) address the issue for you?

**Comment by simonmaass** [comment]
I upgraded to vue 3.5.29 and the memory leaks are back:

<img width="950" height="473" alt="Image" src="https://github.com/user-attachments/assets/f29e45a6-c64f-4062-b1a1-e8bf40927cbe" />

when pin pointing to vue 3.5.13 the leak is gone

just an update. after reverting again back to vue 3.5.13 it is gone again:

<img width="911" height="461" alt="Image" src="https://github.com/user-attachments/assets/a81c7074-6582-418d-b588-5812c622d917" />

**Comment by kamilpula** [comment]
Hi folks,

I can confirm that the custom patcher written by @SaeedNezafat worked in our case as well (thanks!) - sharing this to provide an additional data point.

We tested the Vue versions mentioned in this thread (3.5.13 and 3.5.29), but unfortunately saw no improvement. Earlier in our investigation, we also tried several configuration changes that we thought might be related, including:

- Disabling the `nuxt-api-shield` module  
- Enabling `vite.build.rollupOptions.treeshake` (it had previously been disabled due to CI pipelines getting stuck during the transform step)  
- Disabling ISR for all pages defined in `routeRules`  

None of the above mitigated the memory growth.

If I find more time to continue debugging, I’ll test additional combinations discussed here (Nuxt nightly, Vue 3.6) and will report back with any findings. For now, the patcher is the only solution that has stabilized memory usage for us.

### Test setup

Tests were conducted on a GCP Cloud Run instance using:

```bash
autocannon -m GET -c 20 -p 30 -d 300 "https://example-internal-machine-ip.com"
```

After applying the patch, RAM usage stabilized at around ~30% and remained steady throughout the test duration. The visible peaks correspond to the instance starting to return timeouts, at which point the load test was stopped manually.

<img width="1146" height="408" alt="Image" src="https://github.com/user-attachments/assets/a4adb35b-cf4e-494d-a05d-3aa312cba41b" />

### Current stack

- Nuxt 4.1.2 
- Vue 3.5.25  
- TypeScript 5.9.3  
- Vite 7.2.7

**Comment by SebbeJohansson** [comment]
@kamilpula might be worth it to send this info in related issues (or a new issue) on github.

**Comment by SprayDev** [comment]
I used last version of vue and I still have same memory leaks

**Comment by SprayDev** [comment]
@cernymatej I think we should reopen this issue
In my repository (https://github.com/SprayDev/nuxt-seo-memory) I can easy reproduce memory leak issue
just ran docker stats and do ab -c 100 -n 1000 http://127.0.0.1:3000 and see how memory grow and stack later

**Comment by maximepvrt** [comment]
@SprayDev you must use nightly version of Nuxt

**Comment by zavodptica** [comment]
**SSR Memory Leak — Solved (Nuxt 4 + Vue 3.6-beta)**

  We've been fighting SSR memory leaks in production for several days. Sharing our findings in case it helps others.

  Environment: 6 CPU, 16 GB RAM, Docker, NITRO_PRESET=node-cluster (4 workers)

  The Problem

  Two separate memory leaks:

  1. Vue 3.5.x EffectScope leak — await in <script setup> doesn't release scope after SSR render. JS heap grows
  linearly, OOM within minutes under real traffic. We hit 36 OOM crashes in 40 minutes on production.
  2. Nuxt 4.2+ native memory leak — RSS grows ~5 MB/min even after Vue heap leak is fixed. Related to tokensToParser
  regression in vue-router. 10-minute tests don't catch it — only visible after 20+ minutes of sustained load.

  Initial Setup (broken)

```
  {
    "nuxt": "4.3.x",
    "vue": "3.6.0-beta.7"
  }
```
  Node 25, --max-old-space-size=1024, watchdog at 768 MB RSS.

  Result: slow native memory leak, workers restarting every few minutes via watchdog.

  We then tried Nuxt 4.1.3 + Vue 3.5.13 + Node 22 — stable in Docker tests (19 RPS, 30 min, no leak). But on production
  with real diverse traffic, Vue 3.5.x EffectScope leak caused instant OOM. Docker stress tests with curl don't
  replicate real concurrent browser/bot traffic patterns.

  Final Setup (stable)

```
  {
    "nuxt": "4.1.3",
    "vue": "3.6.0-beta.7",
    "overrides": {
      "vue": "3.6.0-beta.7",
      "@vue/compiler-core": "3.6.0-beta.7",
      "@vue/compiler-dom": "3.6.0-beta.7",
      "@vue/compiler-sfc": "3.6.0-beta.7",
      "@vue/compiler-ssr": "3.6.0-beta.7",
      "@vue/reactivity": "3.6.0-beta.7",
      "@vue/runtime-core": "3.6.0-beta.7",
      "@vue/runtime-dom": "3.6.0-beta.7",
      "@vue/server-renderer": "3.6.0-beta.7",
      "@vue/shared": "3.6.0-beta.7"
    }
  }
```

  Node 22, --max-old-space-size=2048, watchdog at 1800 MB RSS, 4 workers.

  Key insight: Nuxt 4.1.3 avoids the native memory regression from 4.2+, while Vue 3.6-beta.7 fixes the EffectScope leak
   from 3.5.x. You need both.

  Test Results

  - 30 min, 20 curl workers, 173 real URLs, Googlebot UA (SSR): RSS stable 486–559 MB, 34,767 requests, 0 errors, 0
  watchdog restarts
  - autocannon 600 concurrent SSR requests (5 min): peak 3.94 GB across 4 workers, RSS returned to 306 MB after, 0
  restarts
  - With Redis cache: same stability, 0 restarts

  What Didn't Help

  - Removing <NuxtLoadingIndicator/>
  - Updating nuxt-i18n-micro, @unhead/vue, mongoose
  - Nuxt nightly 4.4.0 (slightly better but still leaks)
  - Disabling 9 of 14 Nuxt modules (slowed the leak, didn't fix)
  - Limiting i18n cache size/TTL
  - Reducing number of locales (1 vs 12 — no difference)

**Comment by maximepvrt** [comment]
I am still experiencing persistent Out of Memory issues after upgrading to Nuxt 4.4.2 and Vue 3.5.32.

<img width="1187" height="341" alt="Image" src="https://github.com/user-attachments/assets/02da0e4a-8b83-4279-acf7-1dc0006a0a10" />

**Comment by maximepvrt** [comment]
Hi @danielroe,

Just a heads-up that @edison1105 identified a memory leak issue in `unctx`. I've just applied the patch to my project; I’ll let you know in the coming days if it resolves the issue on my end.

https://github.com/vuejs/core/issues/14706#issuecomment-4221209927
https://github.com/unjs/unctx/issues/125#issuecomment-4175970389

Best,

**Comment by cernymatej** [comment]
Possibly related, there's another memory leak in Vue, which will probably be fixed in the next minor patch - https://github.com/vuejs/core/issues/14733

**Comment by maximepvrt** [comment]
Huge thanks for the amazing work ! 💚

Quick update on the memory leak: after upgrading to Nuxt 4.4.6 and Vue 3.5.34, it is significantly better. The app used to crash within 24 hours, and now it lasts about 6 days.

<img width="1408" height="337" alt="Image" src="https://github.com/user-attachments/assets/a12176cf-69a6-4132-b69d-46705a4ee866" />

However, the leak isn't fully gone yet.

@danielroe @pi0 @edison1105, could you please take a look at this issue? It seems closely related to what's happening here: https://github.com/unjs/unctx/issues/125#issuecomment-4175970389
Same for https://github.com/nuxt/nuxt/pull/35011

Could we reopen this issue until the leak is completely resolved? Thanks again!

**Comment by DamianGlowala** [comment]
@maximepvrt would you be happy to try out pkg.pr.new release for the 4.x branch with unctx v3 addressing this issue and let us know whether there is a noticeable difference? 🙏 

https://github.com/nuxt/nuxt/pull/35541#issuecomment-4954293279

**Comment by coolxinshaoye** [comment]
Did you get this sorted out yet? Asked on July 14, 2026

**Comment by iersah123** [comment]
I confirm that nuxt 4.5.1 fixed the issue. We also updated every dependent package so that they use unctx v3, for a good measure. 
i really appreciated the work went into this!

**Comment by maximepvrt** [comment]
<img width="1548" height="332" alt="Image" src="https://github.com/user-attachments/assets/fb4eaa80-ea3c-4346-ac06-0c9a9c6da3f5" />

@DamianGlowala @danielroe I am still experiencing a memory leak with Nuxt 3.5.2 and forced `unctx` v3, with application memory climbing over 90% after sitting in production for a week without any new deployments.

**Comment by danielroe** [comment]
@maximepvrt I'm afraid that there are so many things outside of nuxt that can cause a memory leak, I can't help by just seeing a screenshot.

**Comment by cernymatej** [comment]
Adding to Daniel's comment - please don't add any more comments to this issue. The problem this issue was related to has been resolved, and adding additional comments here makes it very difficult to keep track of things.
If there's a leak and you think it's related to Nuxt, please open a new issue with a minimal reproduction.
