### ISSUE TITLE
html.replace is not a function

### ISSUE THREAD

**Issue by jeannen** [nuxt/nuxt#33748]
### Environment

- Operating System: Darwin
- Node Version:     v23.7.0
- Nuxt Version:     4.2.1
- CLI Version:      3.30.0
- Nitro Version:    2.12.7
- Package Manager:  npm@11.4.2
- Builder:          -
- User Config:      compatibilityDate, devtools, extends, modules, css, components, runtimeConfig, site, googleTracking, clarityTracking, ui, colorMode, imports, fonts, nitro, sitemap, routeRules, vite
- Runtime Modules:  @nuxt/eslint@1.9.0, @nuxt/ui@4.1.0, @nuxt/fonts@0.11.4, @nuxtjs/seo@3.2.2, @nuxt/image@1.11.0, @nuxt/content@3.7.1, @pinia/nuxt@0.11.2, nuxt-mongoose@1.0.6, @vue-email/nuxt@0.8.19
- Build Modules:    -

### Reproduction

It's a private repo, I can give access tho

### Describe the bug

Impossible to start Nuxt via npm run dev. The page shows for 1-2 sec then show the error screen:

<img width="1121" height="981" alt="Image" src="https://github.com/user-attachments/assets/f83ee62b-8cd8-474e-bf90-03694582badc" />

In the server console, I get this:
```
 ERROR  html.replace is not a function                                   10:31:56 AM

    at generateErrorOverlayHTML (.nuxt/dev/index.mjs:1961:26)
    at errorhandler (.nuxt/dev/index.mjs:2024:53)
    at async errorHandler (.nuxt/dev/index.mjs:2156:7)
    at async Server.toNodeHandle (/Users/jeannen/Dev/apps/Adkit/adkit-all/node_modules/h3/dist/index.mjs:2304:9)
```

### Additional context

Seems to happen on 2 unrelated projects

### Logs

```shell-script
ERROR  html.replace is not a function                                   10:31:56 AM

    at generateErrorOverlayHTML (.nuxt/dev/index.mjs:1961:26)
    at errorhandler (.nuxt/dev/index.mjs:2024:53)
    at async errorHandler (.nuxt/dev/index.mjs:2156:7)
    at async Server.toNodeHandle (/Users/jeannen/Dev/apps/Adkit/adkit-all/node_modules/h3/dist/index.mjs:2304:9)
```

**Comment by L4stIdi0t** [comment]
i got the same issue

node: v22.20.0 and v24.11.1
os: macos 26.1
package manager: npm@11.6.3
nuxt: 4.0.3 and 4.2.1

```
 ERROR  html.replace is not a function                                                                     5:17:34 PM

    at generateErrorOverlayHTML (.nuxt/dev/index.mjs:1140:26)
    at errorhandler (.nuxt/dev/index.mjs:1203:51)
    at async errorHandler (.nuxt/dev/index.mjs:1335:7)
    at async Server.toNodeHandle (node_modules/h3/dist/index.mjs:2304:9)
```

give me a sec to make a repo with a minimal creation

**Comment by L4stIdi0t** [comment]
<img width="658" height="769" alt="Image" src="https://github.com/user-attachments/assets/d1f400a4-5160-49cc-8085-fead58d1f59d" />


https://github.com/L4stIdi0t/nuxt-v4-htmlReplace-issue

i tried different versions of "@vue/devtools-core" and "@vue/devtools-kit", also disabling the devtools in nuxt.config.ts

it only happens if ssr is enabled

**Comment by tsukusu** [comment]
I just encountered the same error.

In my case, the root cause was that a catch-all route (`pages/[...slug].vue`) was intercepting requests for development Service Worker files like `/dev-sw.js?dev-sw`.  
It may be helpful to inspect `req.url` in your own environment to confirm what is being received before `async Server.toNodeHandle` (node_modules/h3/dist/index.mjs:2304:9).

As a workaround, I blocked these paths at the server layer using Nitro middleware:

```ts
// server/middleware/ignorePath.ts
export default defineEventHandler((event) => {
  const ignorePathList = ['/dev-sw.js', ]

  if (ignorePathList.some(path => event.node.req.url?.startsWith(path))) {
    return send(event, null, '404')
  }
})
```

Hope this helps someone facing the same situation.

**Comment by L4stIdi0t** [comment]
that fixes it for me as well, but it was a different service worker for me, it was one from a different project of mine

**Comment by jeannen** [comment]
Any way to ignore service workers automatically in Nuxt?

**Comment by yk-eta** [comment]
this error happen when there is error in server side, turn off SSR in nuxt.config.ts will help on investigate the actual error

**Comment by danielroe** [comment]
this was fixed in the latest nuxt release

**Comment by FabianRzepka** [comment]
I still have this problem on the latest version 4.2.2. It appeared after updating to nuxt4.

<img width="712" height="197" alt="Image" src="https://github.com/user-attachments/assets/c02fde78-920a-4655-9600-60c8d0210aa2" />

Only adding sw.js to the files prevented this error from appearing.

**Comment by itsserbin** [comment]
works for me

```typescript
export default defineNuxtConfig({
  nitro: {
    devProxy: {
      '/sw.js': { target: '/sw.js' }
    }
  }
})
```

**Comment by YoSoySergio** [comment]
@danielroe The fix in f70b70c97 checks `typeof html === 'string'` for the SSR response, but the error is occurring **inside** `generateErrorOverlayHTML` on a different variable.

Stack trace shows the error at line 1961 which is inside `generateErrorOverlayHTML`:
```typescript
const errorPage = html.replace('<head>', ...)  // html here is prettyResponse.body
```

The `prettyResponse.body` passed to `generateErrorOverlayHTML` can be non-string in some cases. 

PR #33977 adds a type check for `prettyResponse.body` before passing it to the function.

**Comment by danielroe** [comment]
@YoSoySergio can you tell me how to reproduce the case where it is not a string?

**Comment by YoSoySergio** [comment]
@danielroe Traced it down - the issue is in `nitropack/dist/runtime/internal/error/dev.mjs`:

```javascript
const useJSON = opts?.json || !getRequestHeader(event, "accept")?.includes("text/html");
```

When we call `defaultHandler(error, event, { json: false })`, `opts.json` is falsy so it still checks the `Accept` header. Requests like `/sw.js` don't have `Accept: text/html`, so `useJSON` ends up `true` and returns an object instead of HTML string.

Probably needs `opts?.json ?? !getRequestHeader(...)` in Nitro to respect explicit `false`. My PR adds a defensive check on the Nuxt side in the meantime.

**Comment by devonik** [comment]
fixed in the latest nuxt 4.3.0. Thanks 💯
